package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;

public class AutoGeneratedBuff_011 implements Buff, Updatable, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, 30000, 45000, 60000, 75000, 90000, 105000, 120000, 135000, 150000, 165000
    };
    public static int[] MP_SHIELD_TOTAL = {
        0, 1800, 2200, 2600, 3000, 3400, 3800, 4200, 4600, 5000, 5400
    };
    public static float[] MP_SHIELD_DPERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] MP_SHIELD_PERCENT = {
        0.0f, 50.0f, 55.0f, 60.0f, 65.0f, 70.0f, 75.0f, 80.0f, 85.0f, 90.0f, 95.0f
    };
    public static float[] MP_SHIELD_PRICE = {
        0.0f, 60.0f, 58.0f, 56.0f, 54.0f, 52.0f, 50.0f, 48.0f, 46.0f, 44.0f, 42.0f
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int mp_shield_total;
    float mp_shield_dpercent;
    float mp_shield_percent;
    float mp_shield_price;

    public AutoGeneratedBuff_011(int lvl, Unit src, Unit tgt, int dmg) {
        if (src != null) {
            source = src.ref();
        }
        if (tgt != null) {
            owner = tgt.ref();
        }
        instanceID = BuffUtil.getNextID();
        level = lvl;
        endTime = Time.currTime + BuffUtil.enhanceParam(src, tgt, 11, "buffTime", DURATION[level]);
        multiple = 1;
        mp_shield_total = MP_SHIELD_TOTAL[level];
        mp_shield_total = BuffUtil.enhanceParam(src, tgt, 11, "mp_shield_total", mp_shield_total);
        mp_shield_dpercent = MP_SHIELD_DPERCENT[level];
        mp_shield_dpercent = BuffUtil.enhanceParam(src, tgt, 11, "mp_shield_dpercent", mp_shield_dpercent);
        mp_shield_percent = MP_SHIELD_PERCENT[level];
        mp_shield_percent = BuffUtil.enhanceParam(src, tgt, 11, "mp_shield_percent", mp_shield_percent);
        mp_shield_price = MP_SHIELD_PRICE[level];
        mp_shield_price = BuffUtil.enhanceParam(src, tgt, 11, "mp_shield_price", mp_shield_price);
        remainAbsorb = mp_shield_total;
        remainAbsorb += mp_shield_dpercent * dmg / 100.0f;
    }

    public int getId() {
        return 11;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "氣血俱動";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("消耗精力抵消{0}所受傷害", CommonUtil.formatPercent(mp_shield_percent * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return endTime;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return true;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return 32 | 0x1000000;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_011) {
            AutoGeneratedBuff_011 other = (AutoGeneratedBuff_011)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                mp_shield_total = other.mp_shield_total;
                mp_shield_dpercent = other.mp_shield_dpercent;
                mp_shield_percent = other.mp_shield_percent;
                mp_shield_price = other.mp_shield_price;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
    }

    public boolean update(int diff) {
        if (endTime <= Time.currTime) {
            return true;
        }
        if (remainAbsorb <= 0) {
            return true;
        }
        return false;
    }

    public void load(byte[] bytes) {
        ByteBuffer buf = ByteBuffer.wrap(bytes);
        owner = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        source = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        level = buf.getInt();
        endTime = Time.elapseTime(buf.getLong());
        multiple = buf.getInt();
        mp_shield_total = MP_SHIELD_TOTAL[level];
        mp_shield_dpercent = MP_SHIELD_DPERCENT[level];
        mp_shield_percent = MP_SHIELD_PERCENT[level];
        mp_shield_price = MP_SHIELD_PRICE[level];
        remainSeconds = buf.getInt();
        tickInterval = buf.getInt();
        remainCure = buf.getInt();
        remainDamage = buf.getInt();
        remainMPCure = buf.getInt();
        remainMPDamage = buf.getInt();
        remainAbsorb = buf.getInt();
        effectTimes = buf.getInt();
    }

    public byte[] save() {
        ByteBuffer buf = ByteBuffer.allocate(66, false);
        buf.put(owner.type);
        buf.putInt(owner.id);
        buf.putInt(owner.instanceId);
        buf.put(source.type);
        buf.putInt(source.id);
        buf.putInt(source.instanceId);
        buf.putInt(level);
        buf.putLong(Time.currentTimeMillis(endTime));
        buf.putInt(multiple);
        buf.putInt(remainSeconds);
        buf.putInt(tickInterval);
        buf.putInt(remainCure);
        buf.putInt(remainDamage);
        buf.putInt(remainMPCure);
        buf.putInt(remainMPDamage);
        buf.putInt(remainAbsorb);
        buf.putInt(effectTimes);
        return buf.array();
    }

    public boolean update2(int time) {
        if (endTime <= Time.currTime) {
            return false;
        }
        return true;
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (!isActive && context.isDamage()) {
            int absorb = (int)(context.damage * mp_shield_percent / 100.0f);
            if (absorb > remainAbsorb) {
                absorb = remainAbsorb;
            }
            int needMp = (int)(absorb * mp_shield_price / 100.0f);
            if (needMp > context.target.mp) {
                needMp = context.target.mp;
                absorb = (int)(needMp * 100.0f / mp_shield_price);
            }
            if (absorb > 0) {
                context.damage -= absorb;
                remainAbsorb -= absorb;
                context.target.setMp(context.target.mp - needMp, true);
            }
            effectTimes++;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

}
