package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import peony.game.attendant.*;

public class AutoGeneratedSkill_397 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 0, 0, 0
    };
    public static float[] MP_USE = {
        0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] ACT_TIME = {
        0, 2000, 2000, 2000
    };
    public static int[] CD_TIME = {
        0, 0, 0, 0
    };
    public static int[] DISTANCE = {
        0, 120, 120, 120
    };
    public static int[] RANGE = {
        0, 120, 120, 120
    };
    public static int[] CHANGE_MAGIC_AP_VALUE = {
        0, 3000, 5000, 7000
    };
    public static float[] CHANGE_MAGIC_AP_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_WEAPON_MATK_VALUE = {
        0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] INTERRUPT_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f
    };
    public static int[] IGNORE_MAGIC_ARMOR_VALUE = {
        0, 0, 0, 0
    };
    public static float[] IGNORE_MAGIC_ARMOR_PERCENT = {
        0.0f, 50.0f, 60.0f, 70.0f
    };
    int change_magic_ap_value;
    float change_magic_ap_percent;
    float change_weapon_matk_value;
    float interrupt_rate;
    int ignore_magic_armor_value;
    float ignore_magic_armor_percent;

    public AutoGeneratedSkill_397(int lvl) {
        super(397, "ÈºÄ§ÂÒÎè", lvl);
        if (lvl > 3) {
            throw new IllegalArgumentException();
        }
        change_magic_ap_value = CHANGE_MAGIC_AP_VALUE[lvl];
        change_magic_ap_percent = CHANGE_MAGIC_AP_PERCENT[lvl];
        change_weapon_matk_value = CHANGE_WEAPON_MATK_VALUE[lvl];
        interrupt_rate = INTERRUPT_RATE[lvl];
        ignore_magic_armor_value = IGNORE_MAGIC_ARMOR_VALUE[lvl];
        ignore_magic_armor_percent = IGNORE_MAGIC_ARMOR_PERCENT[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 397;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = -1;
        prepareAnimation = -1;
        castAnimation = -1;
        hitAnimation = 112;
        clazz = -1;
        mp = MP_USE[lvl];
        type = TYPE_ATTACK;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_AOE_ATTACK_TARGET;
    }

    public String getDesc(Unit owner) {
        return "";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_MAGIC;
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        context.attackPower += context.getSkillParam(this, "change_magic_ap_value", change_magic_ap_value);
        context.attackPowerRate += context.getSkillParam(this, "change_magic_ap_percent", change_magic_ap_percent) / 100.0f;
        if (context.source.equipments != null && context.source.equipments.getWeapon() != null) {
            GameItem weapon = context.source.equipments.getWeapon();
            context.attackPower += weapon.getMagicPower() * context.getSkillParam(this, "change_weapon_matk_value", change_weapon_matk_value) / 100.0f;
        }
        if (context.damageType == CombatContext.DAMAGE_MAGIC) {
            context.armor -= context.getSkillParam(this, "ignore_magic_armor_value", ignore_magic_armor_value);
            context.armorRate -= context.getSkillParam(this, "ignore_magic_armor_percent", ignore_magic_armor_percent) / 100.0f;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited()) {
            int rate = (int)(100 * context.getSkillParam(this, "interrupt_rate", interrupt_rate));
            if (CommonUtil.hit(RND, rate, 10000)) {
                context.activeSkills.add(new BreakAttackSkill());
            }
        }
    }

}
