package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import peony.game.attendant.*;

public class AutoGeneratedSkill_396 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 0, 0, 0
    };
    public static float[] MP_USE = {
        0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] ACT_TIME = {
        0, 2000, 2000, 2000
    };
    public static int[] CD_TIME = {
        0, 0, 0, 0
    };
    public static int[] DISTANCE = {
        0, 120, 120, 120
    };
    public static int[] RANGE = {
        0, 0, 0, 0
    };
    public static int[] CHANGE_PHYSICAL_AP_VALUE = {
        0, 3000, 5000, 7000
    };
    public static float[] CHANGE_PHYSICAL_AP_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] APPEND_MAGIC_DAMAGE = {
        0, 2000, 4000, 6000
    };
    public static float[] FEAR_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f
    };
    public static String[] FEAR_RATE_VAR = {
        "", "", "", ""
    };
    public static int[] FEAR_TIME = {
        0, 2000, 4000, 6000
    };
    public static float[] REPEAT_RATE = {
        0.0f, 70.0f, 80.0f, 90.0f
    };
    int change_physical_ap_value;
    float change_physical_ap_percent;
    int append_magic_damage;
    float fear_rate;
    String fear_rate_var;
    int fear_time;
    float repeat_rate;

    public AutoGeneratedSkill_396(int lvl) {
        super(396, "惊天一击增强版", lvl);
        if (lvl > 3) {
            throw new IllegalArgumentException();
        }
        change_physical_ap_value = CHANGE_PHYSICAL_AP_VALUE[lvl];
        change_physical_ap_percent = CHANGE_PHYSICAL_AP_PERCENT[lvl];
        append_magic_damage = APPEND_MAGIC_DAMAGE[lvl];
        fear_rate = FEAR_RATE[lvl];
        fear_rate_var = FEAR_RATE_VAR[lvl];
        fear_time = FEAR_TIME[lvl];
        repeat_rate = REPEAT_RATE[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 0;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = -1;
        prepareAnimation = -1;
        castAnimation = -1;
        hitAnimation = 101;
        clazz = -1;
        mp = MP_USE[lvl];
        type = TYPE_ATTACK;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_SINGLE_ATTACK;
    }

    public String getDesc(Unit owner) {
        return "";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_PHYSICAL;
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        context.attackPower += context.getSkillParam(this, "change_physical_ap_value", change_physical_ap_value);
        context.attackPowerRate += context.getSkillParam(this, "change_physical_ap_percent", change_physical_ap_percent) / 100.0f;
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        context.appendSpellDamage(context.getSkillParam(this, "append_magic_damage", append_magic_damage));
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited()) {
            boolean hit = false;
            if (fear_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(100 * context.getSkillParam(this, "fear_rate", fear_rate)), 10000);
            } else {
                Float vo = context.skillParams.get(fear_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(100 * (vo.floatValue() + context.getSkillParam(this, "fear_rate", fear_rate))), 10000);
                }
            }
            if (hit) {
                context.activeSkills.add(new FearSkill(context.getSkillParam(this, "fear_time", fear_time)));
            }
        }
        if (context.hited()) {
            if (CommonUtil.hit(RND, (int)(100 * context.getSkillParam(this, "repeat_rate", repeat_rate)), 10000)) {
                context.activeSkills.add(context.skill);
            }
        }
    }

}
