package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import peony.game.attendant.*;

public class AutoGeneratedSkill_011 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 54, 67, 80, 93, 106
    };
    public static float[] MP_USE = {
        0.0f, -2.3f, -2.4f, -2.5000002f, -2.6000004f, -2.7000005f
    };
    public static int[] ACT_TIME = {
        0, 0, 0, 0, 0, 0
    };
    public static int[] CD_TIME = {
        0, 300000, 300000, 300000, 300000, 300000
    };
    public static int[] DISTANCE = {
        0, 0, 0, 0, 0, 0
    };
    public static int[] RANGE = {
        0, 0, 0, 0, 0, 0
    };
    public static int[] CHANGE_THREAT_VALUE = {
        0, 254, 380, 506, 632, 758
    };
    public static float[] CHANGE_THREAT_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] ADD_BUFF_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f
    };
    public static String[] ADD_BUFF_RATE_VAR = {
        "", "", "", "", "", ""
    };
    public static int[] ADD_BUFF_ID = {
        0, 2, 2, 2, 2, 2
    };
    public static int[] ADD_BUFF_LEVEL = {
        0, 1, 2, 3, 4, 5
    };
    public static float[] ADD_HPIM_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f
    };
    public static int[] ADD_HPIM_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] ADD_HPIM_PERCENT_OF_MAX = {
        0.0f, 10.0f, 11.0f, 12.0f, 13.0f, 14.0f
    };
    public static float[] ADD_HPIM_PERCENT_OF_DAMAGE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    int change_threat_value;
    float change_threat_percent;
    float add_buff_rate;
    String add_buff_rate_var;
    int add_buff_id;
    int add_buff_level;
    float add_hpim_rate;
    int add_hpim_value;
    float add_hpim_percent_of_max;
    float add_hpim_percent_of_damage;

    public AutoGeneratedSkill_011(int lvl) {
        super(11, "跃空提升", lvl);
        if (lvl > 5) {
            throw new IllegalArgumentException();
        }
        change_threat_value = CHANGE_THREAT_VALUE[lvl];
        change_threat_percent = CHANGE_THREAT_PERCENT[lvl];
        add_buff_rate = ADD_BUFF_RATE[lvl];
        add_buff_rate_var = ADD_BUFF_RATE_VAR[lvl];
        add_buff_id = ADD_BUFF_ID[lvl];
        add_buff_level = ADD_BUFF_LEVEL[lvl];
        add_hpim_rate = ADD_HPIM_RATE[lvl];
        add_hpim_value = ADD_HPIM_VALUE[lvl];
        add_hpim_percent_of_max = ADD_HPIM_PERCENT_OF_MAX[lvl];
        add_hpim_percent_of_damage = ADD_HPIM_PERCENT_OF_DAMAGE[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 11;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = 10;
        prepareAnimation = 7864322;
        castAnimation = -65534;
        hitAnimation = 1;
        clazz = Unit.CLASS_1;
        mp = MP_USE[lvl];
        type = TYPE_AID;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_AID_SELF;
    }

    public String getDesc(Unit owner) {
        return java.text.MessageFormat.format("运功强化自身，暂时提升生命上限{0}，并能缓慢恢复生命值，持续{1}", CommonUtil.formatPercent(peony.game.buff.AutoGeneratedBuff_002.CHANGE_MAXHP_PERCENT[add_buff_level]), CommonUtil.formatSecond(peony.game.buff.AutoGeneratedBuff_002.HOT_SECONDS[add_buff_level]));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_BUFF;
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        context.threatAdd += context.getSkillParam(this, "change_threat_value", change_threat_value);
        context.threatAddRate += context.getSkillParam(this, "change_threat_percent", change_threat_percent) / 100.0f;
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited()) {
            boolean hit = false;
            if (add_buff_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(100 * context.getSkillParam(this, "add_buff_rate", add_buff_rate)), 10000);
            } else {
                Float vo = context.skillParams.get(add_buff_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(100 * (vo.floatValue() + context.getSkillParam(this, "add_buff_rate", add_buff_rate))), 10000);
                }
            }
            if (hit) {
                context.source.buffs.addBuff(BuffUtil.createBuff(add_buff_id, add_buff_level, context.source, context.source, context.damage));
            }
        }
        if (context.hited()) {
            int rate = (int)(100 * context.getSkillParam(this, "add_hpim_rate", add_hpim_rate));
            if (CommonUtil.hit(RND, rate, 10000)) {
                int addhp = context.getSkillParam(this, "add_hpim_value", add_hpim_value);
                addhp += context.source.maxhp * context.getSkillParam(this, "add_hpim_percent_of_max", add_hpim_percent_of_max) / 100.0f;
                addhp += context.damage * context.getSkillParam(this, "add_hpim_percent_of_damage", add_hpim_percent_of_damage) / 100.0f;
                context.target.setHp(context.target.hp + addhp, true);
            }
        }
    }

}
