package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import peony.game.attendant.*;

public class AutoGeneratedSkill_003 extends AbstractSkill {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93
    };
    public static float[] MP_USE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] ACT_TIME = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static int[] CD_TIME = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static int[] DISTANCE = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static int[] RANGE = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };

    public AutoGeneratedSkill_003(int lvl) {
        super(3, "武神强化", lvl);
        if (lvl > 15) {
            throw new IllegalArgumentException();
        }
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 0;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = 5;
        prepareAnimation = -1;
        castAnimation = -1;
        hitAnimation = -1;
        clazz = Unit.CLASS_1;
        mp = MP_USE[lvl];
        type = TYPE_PASSIVE;
        targetType = TARGET_AID_SELF;
    }

    public String getDesc(Unit owner) {
        return java.text.MessageFormat.format("提升战斗力，提升{0}点物理攻击力", CommonUtil.formatValue(peony.game.buff.AutoGeneratedBuff_015.CHANGE_PHYSICAL_AP_VALUE[level]));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        return null;
    }

    public Buff newBuff() {
        if (level == 0) {
            return null;
        }
        return BuffUtil.createSkillBuff(15, this);
    }

    public Buff getAreaBuff() {
        return null;
    }

}
