package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import peony.game.attendant.*;

public class AutoGeneratedSkill_224 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] MP_USE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] ACT_TIME = {
        0, 0, 0, 0, 0, 0
    };
    public static int[] CD_TIME = {
        0, 0, 0, 0, 0, 0
    };
    public static int[] DISTANCE = {
        0, 96, 96, 96, 96, 96
    };
    public static int[] RANGE = {
        0, 0, 0, 0, 0, 0
    };
    public static int[] CHANGE_PHYSICAL_AP_VALUE = {
        0, 1000, 2000, 4000, 8000, 16000
    };
    public static float[] CHANGE_PHYSICAL_AP_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PHYSICAL_HIT = {
        0.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f
    };
    public static float[] CHANGE_PHYSICAL_CRIT = {
        0.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f
    };
    public static float[] DISPEL_BUFF_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f
    };
    public static float[] INTERRUPT_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f
    };
    public static int[] FIRST_THREAT_TEMP_KEEPTIME = {
        0, 5000, 6000, 7000, 8000, 9000
    };
    int change_physical_ap_value;
    float change_physical_ap_percent;
    float change_physical_hit;
    float change_physical_crit;
    float dispel_buff_rate;
    float interrupt_rate;
    int first_threat_temp_keeptime;

    public AutoGeneratedSkill_224(int lvl) {
        super(224, "狂乱攻击", lvl);
        if (lvl > 5) {
            throw new IllegalArgumentException();
        }
        change_physical_ap_value = CHANGE_PHYSICAL_AP_VALUE[lvl];
        change_physical_ap_percent = CHANGE_PHYSICAL_AP_PERCENT[lvl];
        change_physical_hit = CHANGE_PHYSICAL_HIT[lvl];
        change_physical_crit = CHANGE_PHYSICAL_CRIT[lvl];
        dispel_buff_rate = DISPEL_BUFF_RATE[lvl];
        interrupt_rate = INTERRUPT_RATE[lvl];
        first_threat_temp_keeptime = FIRST_THREAT_TEMP_KEEPTIME[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 224;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = -1;
        prepareAnimation = -1;
        castAnimation = -1;
        hitAnimation = 100;
        clazz = -1;
        mp = MP_USE[lvl];
        type = TYPE_ATTACK;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_SINGLE_ATTACK;
    }

    public String getDesc(Unit owner) {
        return java.text.MessageFormat.format("跳起奋力猛劈，造成100%命中的普通攻击伤害及{0}点物理伤害，驱散目标一个有益状态，打断目标施法；同时使目标在{1}内成为第一仇恨", CommonUtil.formatValue(change_physical_ap_value), CommonUtil.formatMillSecond(first_threat_temp_keeptime));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_PHYSICAL;
        if (!checkWeapon(context.source)) {
            return;
        }
        context.hitRate += context.getSkillParam(this, "change_physical_hit", change_physical_hit) / 100.0f;
        context.critRate += context.getSkillParam(this, "change_physical_crit", change_physical_crit) / 100.0f;
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        context.attackPower += context.getSkillParam(this, "change_physical_ap_value", change_physical_ap_value);
        context.attackPowerRate += context.getSkillParam(this, "change_physical_ap_percent", change_physical_ap_percent) / 100.0f;
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited()) {
            int rate = (int)(100 * context.getSkillParam(this, "dispel_buff_rate", dispel_buff_rate));
            if (CommonUtil.hit(RND, rate, 10000)) {
                context.target.buffs.dispelGoodBuff(false);
            }
        }
        if (context.hited()) {
            int rate = (int)(100 * context.getSkillParam(this, "interrupt_rate", interrupt_rate));
            if (CommonUtil.hit(RND, rate, 10000)) {
                context.activeSkills.add(new BreakAttackSkill());
            }
        }
        if (context.hited()) {
            int keepTime = context.getSkillParam(this, "first_threat_temp_keeptime", first_threat_temp_keeptime);
            Attack.makeFirstThreat(context.target, context.source, keepTime);
        }
    }

}
