package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import peony.game.attendant.*;

public class AutoGeneratedSkill_404 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 0, 0, 0
    };
    public static float[] MP_USE = {
        0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] ACT_TIME = {
        0, 0, 0, 0
    };
    public static int[] CD_TIME = {
        0, 0, 0, 0
    };
    public static int[] DISTANCE = {
        0, 120, 120, 120
    };
    public static int[] RANGE = {
        0, 160, 160, 160
    };
    public static float[] DUMB_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f
    };
    public static String[] DUMB_RATE_VAR = {
        "", "", "", ""
    };
    public static int[] DUMB_TIME = {
        0, 3000, 5000, 7000
    };
    float dumb_rate;
    String dumb_rate_var;
    int dumb_time;

    public AutoGeneratedSkill_404(int lvl) {
        super(404, "È«Ìå³ÁÄ¬", lvl);
        if (lvl > 3) {
            throw new IllegalArgumentException();
        }
        dumb_rate = DUMB_RATE[lvl];
        dumb_rate_var = DUMB_RATE_VAR[lvl];
        dumb_time = DUMB_TIME[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 0;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = -1;
        prepareAnimation = -1;
        castAnimation = -1;
        hitAnimation = -1;
        clazz = -1;
        mp = MP_USE[lvl];
        type = TYPE_ATTACK;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_AOE_ATTACK_TARGET;
    }

    public String getDesc(Unit owner) {
        return "";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_MAGIC;
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited()) {
            boolean hit = false;
            if (dumb_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(100 * context.getSkillParam(this, "dumb_rate", dumb_rate)), 10000);
            } else {
                Float vo = context.skillParams.get(dumb_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(100 * (vo.floatValue() + context.getSkillParam(this, "dumb_rate", dumb_rate))), 10000);
                }
            }
            if (hit) {
                context.activeSkills.add(new DumbSkill(context.getSkillParam(this, "dumb_time", dumb_time)));
            }
        }
    }

}
