package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import peony.game.attendant.*;

public class AutoGeneratedSkill_001 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 5, 11, 17, 23, 29, 35, 41, 47, 53, 59, 65, 71, 77, 83, 89
    };
    public static float[] MP_USE = {
        0.0f, -2.1f, -2.07f, -2.04f, -2.01f, -1.98f, -1.95f, -1.9200001f, -1.8900001f, -1.8600001f, -1.8300002f, -1.8000002f, -1.7700002f, -1.7400002f, -1.7100003f, -1.6800003f
    };
    public static int[] ACT_TIME = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static int[] CD_TIME = {
        0, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000
    };
    public static int[] DISTANCE = {
        0, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40
    };
    public static int[] RANGE = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static int[] CHANGE_PHYSICAL_AP_VALUE = {
        0, 100, 166, 232, 298, 364, 430, 496, 562, 628, 694, 760, 826, 892, 958, 1024
    };
    public static float[] CHANGE_PHYSICAL_AP_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_WEAPON_ATK_VALUE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] CHANGE_THREAT_VALUE = {
        0, 86, 130, 174, 218, 262, 306, 350, 394, 438, 482, 526, 570, 614, 658, 702
    };
    public static float[] CHANGE_THREAT_PERCENT = {
        0.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f
    };
    public static float[] ADD_DEBUFF_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f
    };
    public static String[] ADD_DEBUFF_RATE_VAR = {
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""
    };
    public static int[] ADD_DEBUFF_ID = {
        0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    };
    public static int[] ADD_DEBUFF_LEVEL = {
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
    };
    public static float[] DISPEL_BUFF_RATE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    int change_physical_ap_value;
    float change_physical_ap_percent;
    float change_weapon_atk_value;
    int change_threat_value;
    float change_threat_percent;
    float add_debuff_rate;
    String add_debuff_rate_var;
    int add_debuff_id;
    int add_debuff_level;
    float dispel_buff_rate;

    public AutoGeneratedSkill_001(int lvl) {
        super(1, "霸王卸甲", lvl);
        if (lvl > 15) {
            throw new IllegalArgumentException();
        }
        change_physical_ap_value = CHANGE_PHYSICAL_AP_VALUE[lvl];
        change_physical_ap_percent = CHANGE_PHYSICAL_AP_PERCENT[lvl];
        change_weapon_atk_value = CHANGE_WEAPON_ATK_VALUE[lvl];
        change_threat_value = CHANGE_THREAT_VALUE[lvl];
        change_threat_percent = CHANGE_THREAT_PERCENT[lvl];
        add_debuff_rate = ADD_DEBUFF_RATE[lvl];
        add_debuff_rate_var = ADD_DEBUFF_RATE_VAR[lvl];
        add_debuff_id = ADD_DEBUFF_ID[lvl];
        add_debuff_level = ADD_DEBUFF_LEVEL[lvl];
        dispel_buff_rate = DISPEL_BUFF_RATE[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 1;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = 3;
        prepareAnimation = -65536;
        castAnimation = -65536;
        hitAnimation = 101;
        clazz = Unit.CLASS_1;
        mp = MP_USE[lvl];
        type = TYPE_ATTACK;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_SINGLE_ATTACK;
    }

    public String getDesc(Unit owner) {
        return java.text.MessageFormat.format("击碎目标护甲，造成普通攻击伤害及{0}点物理伤害；减少目标{1}护甲值，持续{2}，可叠加", CommonUtil.formatValue(change_physical_ap_value), CommonUtil.formatValue(peony.game.buff.AutoGeneratedBuff_001.CHANGE_ARMOR_VALUE[add_debuff_level]), CommonUtil.formatMillSecond(peony.game.buff.AutoGeneratedBuff_001.DURATION[add_debuff_level]));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public boolean isAutoLearn() {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_PHYSICAL;
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        context.attackPower += context.getSkillParam(this, "change_physical_ap_value", change_physical_ap_value);
        context.attackPowerRate += context.getSkillParam(this, "change_physical_ap_percent", change_physical_ap_percent) / 100.0f;
        if (context.source.equipments != null && context.source.equipments.getWeapon() != null) {
            GameItem weapon = context.source.equipments.getWeapon();
            int addDamage = CommonUtil.getCount(RND, weapon.getMinAttack(), weapon.getMaxAttack());
            context.attackPower += addDamage * context.getSkillParam(this, "change_weapon_atk_value", change_weapon_atk_value) / 100.0f;
        }
        context.threatAdd += context.getSkillParam(this, "change_threat_value", change_threat_value);
        context.threatAddRate += context.getSkillParam(this, "change_threat_percent", change_threat_percent) / 100.0f;
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited()) {
            boolean hit = false;
            if (add_debuff_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(100 * context.getSkillParam(this, "add_debuff_rate", add_debuff_rate)), 10000);
            } else {
                Float vo = context.skillParams.get(add_debuff_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(100 * (vo.floatValue() + context.getSkillParam(this, "add_debuff_rate", add_debuff_rate))), 10000);
                }
            }
            if (hit) {
                context.target.buffs.addBuff(BuffUtil.createBuff(add_debuff_id, add_debuff_level, context.source, context.target, context.damage));
            }
        }
        if (context.hited()) {
            int rate = (int)(100 * context.getSkillParam(this, "dispel_buff_rate", dispel_buff_rate));
            if (CommonUtil.hit(RND, rate, 10000)) {
                context.target.buffs.dispelGoodBuff(false);
            }
        }
    }

}
