package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import peony.game.attendant.*;

public class AutoGeneratedSkill_341 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 0
    };
    public static float[] MP_USE = {
        0.0f, 0.0f
    };
    public static int[] ACT_TIME = {
        0, 0
    };
    public static int[] CD_TIME = {
        0, 0
    };
    public static int[] DISTANCE = {
        0, 0
    };
    public static int[] RANGE = {
        0, 0
    };
    public static float[] ADD_BUFF_RATE = {
        0.0f, 100.0f
    };
    public static String[] ADD_BUFF_RATE_VAR = {
        "", ""
    };
    public static int[] ADD_BUFF_ID = {
        0, 436
    };
    public static int[] ADD_BUFF_LEVEL = {
        0, 1
    };
    float add_buff_rate;
    String add_buff_rate_var;
    int add_buff_id;
    int add_buff_level;

    public AutoGeneratedSkill_341(int lvl) {
        super(341, "²âÊÔÃâ±¬", lvl);
        if (lvl > 1) {
            throw new IllegalArgumentException();
        }
        add_buff_rate = ADD_BUFF_RATE[lvl];
        add_buff_rate_var = ADD_BUFF_RATE_VAR[lvl];
        add_buff_id = ADD_BUFF_ID[lvl];
        add_buff_level = ADD_BUFF_LEVEL[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 341;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = -1;
        prepareAnimation = -1;
        castAnimation = -1;
        hitAnimation = -1;
        clazz = -1;
        mp = MP_USE[lvl];
        type = TYPE_AID;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_AID_SELF;
    }

    public String getDesc(Unit owner) {
        return "";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_BUFF;
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited()) {
            boolean hit = false;
            if (add_buff_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(100 * context.getSkillParam(this, "add_buff_rate", add_buff_rate)), 10000);
            } else {
                Float vo = context.skillParams.get(add_buff_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(100 * (vo.floatValue() + context.getSkillParam(this, "add_buff_rate", add_buff_rate))), 10000);
                }
            }
            if (hit) {
                context.source.buffs.addBuff(BuffUtil.createBuff(add_buff_id, add_buff_level, context.source, context.source, context.damage));
            }
        }
    }

}
