package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;

public class AutoGeneratedSkill_190 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 0
    };
    public static float[] MP_USE = {
        0.0f, 0.0f
    };
    public static int[] ACT_TIME = {
        0, 0
    };
    public static int[] CD_TIME = {
        0, 2000
    };
    public static int[] DISTANCE = {
        0, 48
    };
    public static int[] RANGE = {
        0, 0
    };
    public static float[] DEC_MP_RATE = {
        0.0f, 100.0f
    };
    public static int[] DEC_MP_VALUE = {
        0, 20000
    };
    public static float[] DEC_MP_PERCENT_OF_MAX = {
        0.0f, 100.0f
    };
    public static float[] DEC_MP_PERCENT_OF_DAMAGE = {
        0.0f, 100.0f
    };
    public static int[] CHANGE_PHYSICAL_AP_VALUE = {
        0, 3000
    };
    public static float[] CHANGE_PHYSICAL_AP_PERCENT = {
        0.0f, 0.0f
    };
    float dec_mp_rate;
    int dec_mp_value;
    float dec_mp_percent_of_max;
    float dec_mp_percent_of_damage;
    int change_physical_ap_value;
    float change_physical_ap_percent;

    public AutoGeneratedSkill_190(int lvl) {
        super(190, "董卓小兵_大燒藍", lvl);
        if (lvl > 1) {
            throw new IllegalArgumentException();
        }
        dec_mp_rate = DEC_MP_RATE[lvl];
        dec_mp_value = DEC_MP_VALUE[lvl];
        dec_mp_percent_of_max = DEC_MP_PERCENT_OF_MAX[lvl];
        dec_mp_percent_of_damage = DEC_MP_PERCENT_OF_DAMAGE[lvl];
        change_physical_ap_value = CHANGE_PHYSICAL_AP_VALUE[lvl];
        change_physical_ap_percent = CHANGE_PHYSICAL_AP_PERCENT[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 190;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = -1;
        prepareAnimation = -1;
        castAnimation = -65536;
        hitAnimation = 1;
        clazz = -1;
        mp = MP_USE[lvl];
        type = TYPE_ATTACK;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_SINGLE_ATTACK;
    }

    public String getDesc(Unit owner) {
        return "攻擊敵人時造成20000點藍傷害及3000點絕對值傷害";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_PHYSICAL;
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        context.attackPower += context.getSkillParam(this, "change_physical_ap_value", change_physical_ap_value);
        context.attackPowerRate += context.getSkillParam(this, "change_physical_ap_percent", change_physical_ap_percent) / 100.0f;
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited() && context.isDamage()) {
            int rate = (int)(100 * context.getSkillParam(this, "dec_mp_rate", dec_mp_rate));
            if (CommonUtil.hit(RND, rate, 10000)) {
                int decmp = context.getSkillParam(this, "dec_mp_value", dec_mp_value);
                decmp += context.target.maxmp * context.getSkillParam(this, "dec_mp_percent_of_max", dec_mp_percent_of_max) / 100.0f;
                decmp += context.damage * context.getSkillParam(this, "dec_mp_percent_of_damage", dec_mp_percent_of_damage) / 100.0f;
                context.activeSkills.add(new FixedDecMPSkill(decmp));
            }
        }
    }

}
