package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_404 implements Buff, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1
    };
    public static int[] IGNORE_ARMOR_VALUE = {
        0, 0
    };
    public static float[] IGNORE_ARMOR_PERCENT = {
        0.0f, 2.0f
    };
    public static int[] IGNORE_MAGIC_ARMOR_VALUE = {
        0, 0
    };
    public static float[] IGNORE_MAGIC_ARMOR_PERCENT = {
        0.0f, 2.0f
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int ignore_armor_value;
    float ignore_armor_percent;
    int ignore_magic_armor_value;
    float ignore_magic_armor_percent;

    public AutoGeneratedBuff_404(int lvl) {
        int dmg = 0;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        ignore_armor_value = IGNORE_ARMOR_VALUE[level];
        ignore_armor_percent = IGNORE_ARMOR_PERCENT[level];
        ignore_magic_armor_value = IGNORE_MAGIC_ARMOR_VALUE[level];
        ignore_magic_armor_percent = IGNORE_MAGIC_ARMOR_PERCENT[level];
    }

    public int getId() {
        return 404;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "攻击无视护甲法防";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("攻击无视目标{0}护甲和法术防御", CommonUtil.formatPercent(ignore_armor_percent * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return true;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_404) {
            AutoGeneratedBuff_404 other = (AutoGeneratedBuff_404)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                ignore_armor_value = other.ignore_armor_value;
                ignore_armor_percent = other.ignore_armor_percent;
                ignore_magic_armor_value = other.ignore_magic_armor_value;
                ignore_magic_armor_percent = other.ignore_magic_armor_percent;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        ignore_armor_value = IGNORE_ARMOR_VALUE[level];
        ignore_armor_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 404, "ignore_armor_value", ignore_armor_value);
        ignore_armor_percent = IGNORE_ARMOR_PERCENT[level];
        ignore_armor_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 404, "ignore_armor_percent", ignore_armor_percent);
        ignore_magic_armor_value = IGNORE_MAGIC_ARMOR_VALUE[level];
        ignore_magic_armor_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 404, "ignore_magic_armor_value", ignore_magic_armor_value);
        ignore_magic_armor_percent = IGNORE_MAGIC_ARMOR_PERCENT[level];
        ignore_magic_armor_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 404, "ignore_magic_armor_percent", ignore_magic_armor_percent);
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive && context.damageType == CombatContext.DAMAGE_PHYSICAL) {
            context.armor -= multiple * ignore_armor_value;
            context.armorRate -= multiple * ignore_armor_percent / 100.0f;
            effectTimes++;
        }
        if (isActive && context.damageType == CombatContext.DAMAGE_MAGIC) {
            context.armor -= multiple * ignore_magic_armor_value;
            context.armorRate -= multiple * ignore_magic_armor_percent / 100.0f;
            effectTimes++;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

}
