package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_023 implements Buff, SkillBuff, PropertyEnhancer {
    private static final int[] WEAPON = {
        7
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
    public static float[] CHANGE_PHYSICAL_HIT = {
        0.0f, 1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f, 9.0f, 10.0f
    };
    public static float[] CHANGE_PHYSICAL_CRIT = {
        0.0f, 6.0f, 7.0f, 8.0f, 9.0f, 10.0f, 11.0f, 12.0f, 13.0f, 14.0f, 15.0f
    };
    Skill skill;
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    float change_physical_hit;
    float change_physical_crit;

    public AutoGeneratedBuff_023(Skill skl, int lvl) {
        int dmg = 0;
        skill = skl;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        change_physical_hit = CHANGE_PHYSICAL_HIT[level];
        change_physical_crit = CHANGE_PHYSICAL_CRIT[level];
    }

    public int getId() {
        return skill.getId();
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "心如止水（废弃）";
    }

    public String getDesc() {
        return "提升弓箭攻击命中率和暴击率";
    }

    public Skill getSkill() {
        return skill;
    }

    private boolean checkWeapon(Unit unit) {
        if (unit == null || unit.equipments == null || unit.equipments.getWeapon() == null) {
            return false;
        }
        int type = unit.equipments.getWeapon().template.equipment.minorType;
        for (int t : WEAPON) {
            if (t == type) {
                return true;
            }
        }
        return false;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_023) {
            AutoGeneratedBuff_023 other = (AutoGeneratedBuff_023)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                change_physical_hit = other.change_physical_hit;
                change_physical_crit = other.change_physical_crit;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        change_physical_hit = CHANGE_PHYSICAL_HIT[level];
        change_physical_hit = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 23, "change_physical_hit", change_physical_hit);
        change_physical_crit = CHANGE_PHYSICAL_CRIT[level];
        change_physical_crit = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 23, "change_physical_crit", change_physical_crit);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.hit += multiple * change_physical_hit / 100.0f;
        pc.critical += multiple * change_physical_crit / 100.0f;
    }

}
