package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_178 implements Buff, PropertyEnhancer {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1
    };
    public static int[] CHANGE_ARMOR_VALUE = {
        0, 0
    };
    public static float[] CHANGE_ARMOR_PERCENT = {
        0.0f, 2.0f
    };
    public static int[] CHANGE_MAGIC_ARMOR_VALUE = {
        0, 0
    };
    public static float[] CHANGE_MAGIC_ARMOR_PERCENT = {
        0.0f, 2.0f
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_armor_value;
    float change_armor_percent;
    int change_magic_armor_value;
    float change_magic_armor_percent;

    public AutoGeneratedBuff_178(int lvl) {
        int dmg = 0;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        change_armor_value = CHANGE_ARMOR_VALUE[level];
        change_armor_percent = CHANGE_ARMOR_PERCENT[level];
        change_magic_armor_value = CHANGE_MAGIC_ARMOR_VALUE[level];
        change_magic_armor_percent = CHANGE_MAGIC_ARMOR_PERCENT[level];
    }

    public int getId() {
        return 178;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "结义防御2%";
    }

    public String getDesc() {
        return "护甲和法防提升2%";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_178) {
            AutoGeneratedBuff_178 other = (AutoGeneratedBuff_178)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                change_armor_value = other.change_armor_value;
                change_armor_percent = other.change_armor_percent;
                change_magic_armor_value = other.change_magic_armor_value;
                change_magic_armor_percent = other.change_magic_armor_percent;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        change_armor_value = CHANGE_ARMOR_VALUE[level];
        change_armor_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 178, "change_armor_value", change_armor_value);
        change_armor_percent = CHANGE_ARMOR_PERCENT[level];
        change_armor_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 178, "change_armor_percent", change_armor_percent);
        change_magic_armor_value = CHANGE_MAGIC_ARMOR_VALUE[level];
        change_magic_armor_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 178, "change_magic_armor_value", change_magic_armor_value);
        change_magic_armor_percent = CHANGE_MAGIC_ARMOR_PERCENT[level];
        change_magic_armor_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 178, "change_magic_armor_percent", change_magic_armor_percent);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.defenseRate += multiple * change_armor_percent / 100.0f;
        pc.defense += multiple * change_armor_value;
        if (pc.defense < 0) {
            pc.defense = 0;
        }
        pc.spellDefenseRate += multiple * change_magic_armor_percent / 100.0f;
        pc.spelldefense += multiple * change_magic_armor_value;
        if (pc.spelldefense < 0) {
            pc.spelldefense = 0;
        }
    }

}
