package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_248 implements Buff, Updatable, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, 10000, 15000, 20000, 25000, 30000
    };
    public static int[] REDUCE_PHYSICAL_DAMAGE_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] REDUCE_PHYSICAL_DAMAGE_PERCENT = {
        0.0f, 10.0f, 20.0f, 30.0f, 40.0f, 50.0f
    };
    public static int[] REDUCE_MAGIC_DAMAGE_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] REDUCE_MAGIC_DAMAGE_PERCENT = {
        0.0f, 10.0f, 20.0f, 30.0f, 40.0f, 50.0f
    };
    public static float[] BOUNCE_RATE = {
        0.0f, 20.0f, 40.0f, 60.0f, 80.0f, 100.0f
    };
    public static int[] BOUNCE_DAMAGE_TYPE = {
        0, 0, 0, 0, 0, 0
    };
    public static int[] BOUNCE_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] BOUNCE_PERCENT_OF_DAMAGE = {
        0.0f, 10.0f, 20.0f, 30.0f, 40.0f, 50.0f
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int reduce_physical_damage_value;
    float reduce_physical_damage_percent;
    int reduce_magic_damage_value;
    float reduce_magic_damage_percent;
    float bounce_rate;
    int bounce_damage_type;
    int bounce_value;
    float bounce_percent_of_damage;

    public AutoGeneratedBuff_248(int lvl, Unit src, Unit tgt, int dmg) {
        if (src != null) {
            source = src.ref();
        }
        if (tgt != null) {
            owner = tgt.ref();
        }
        instanceID = BuffUtil.getNextID();
        level = lvl;
        endTime = Time.currTime + BuffUtil.enhanceParam(src, tgt, 248, "buffTime", DURATION[level]);
        multiple = 1;
        reduce_physical_damage_value = REDUCE_PHYSICAL_DAMAGE_VALUE[level];
        reduce_physical_damage_value = BuffUtil.enhanceParam(src, tgt, 248, "reduce_physical_damage_value", reduce_physical_damage_value);
        reduce_physical_damage_percent = REDUCE_PHYSICAL_DAMAGE_PERCENT[level];
        reduce_physical_damage_percent = BuffUtil.enhanceParam(src, tgt, 248, "reduce_physical_damage_percent", reduce_physical_damage_percent);
        reduce_magic_damage_value = REDUCE_MAGIC_DAMAGE_VALUE[level];
        reduce_magic_damage_value = BuffUtil.enhanceParam(src, tgt, 248, "reduce_magic_damage_value", reduce_magic_damage_value);
        reduce_magic_damage_percent = REDUCE_MAGIC_DAMAGE_PERCENT[level];
        reduce_magic_damage_percent = BuffUtil.enhanceParam(src, tgt, 248, "reduce_magic_damage_percent", reduce_magic_damage_percent);
        bounce_rate = BOUNCE_RATE[level];
        bounce_rate = BuffUtil.enhanceParam(src, tgt, 248, "bounce_rate", bounce_rate);
        bounce_damage_type = BOUNCE_DAMAGE_TYPE[level];
        bounce_damage_type = BuffUtil.enhanceParam(src, tgt, 248, "bounce_damage_type", bounce_damage_type);
        bounce_value = BOUNCE_VALUE[level];
        bounce_value = BuffUtil.enhanceParam(src, tgt, 248, "bounce_value", bounce_value);
        bounce_percent_of_damage = BOUNCE_PERCENT_OF_DAMAGE[level];
        bounce_percent_of_damage = BuffUtil.enhanceParam(src, tgt, 248, "bounce_percent_of_damage", bounce_percent_of_damage);
    }

    public int getId() {
        return 248;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "减伤又反伤";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("一段时间内，受到的伤害减少{0}，并且{1}几率反弹{2}伤害", CommonUtil.formatPercent(reduce_physical_damage_percent * multiple), CommonUtil.formatPercent(bounce_rate * multiple), CommonUtil.formatPercent(bounce_percent_of_damage * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return endTime;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return true;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return 38 | 0x1000000;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_248) {
            AutoGeneratedBuff_248 other = (AutoGeneratedBuff_248)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                reduce_physical_damage_value = other.reduce_physical_damage_value;
                reduce_physical_damage_percent = other.reduce_physical_damage_percent;
                reduce_magic_damage_value = other.reduce_magic_damage_value;
                reduce_magic_damage_percent = other.reduce_magic_damage_percent;
                bounce_rate = other.bounce_rate;
                bounce_damage_type = other.bounce_damage_type;
                bounce_value = other.bounce_value;
                bounce_percent_of_damage = other.bounce_percent_of_damage;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
    }

    public boolean update(int diff) {
        if (endTime <= Time.currTime) {
            return true;
        }
        return false;
    }

    public void load(byte[] bytes) {
        ByteBuffer buf = ByteBuffer.wrap(bytes);
        owner = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        source = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        level = buf.getInt();
        endTime = Time.elapseTime(buf.getLong());
        multiple = buf.getInt();
        reduce_physical_damage_value = REDUCE_PHYSICAL_DAMAGE_VALUE[level];
        reduce_physical_damage_percent = REDUCE_PHYSICAL_DAMAGE_PERCENT[level];
        reduce_magic_damage_value = REDUCE_MAGIC_DAMAGE_VALUE[level];
        reduce_magic_damage_percent = REDUCE_MAGIC_DAMAGE_PERCENT[level];
        bounce_rate = BOUNCE_RATE[level];
        bounce_damage_type = BOUNCE_DAMAGE_TYPE[level];
        bounce_value = BOUNCE_VALUE[level];
        bounce_percent_of_damage = BOUNCE_PERCENT_OF_DAMAGE[level];
        remainSeconds = buf.getInt();
        tickInterval = buf.getInt();
        remainCure = buf.getInt();
        remainDamage = buf.getInt();
        remainMPCure = buf.getInt();
        remainMPDamage = buf.getInt();
        remainAbsorb = buf.getInt();
        effectTimes = buf.getInt();
    }

    public byte[] save() {
        ByteBuffer buf = ByteBuffer.allocate(66, false);
        buf.put(owner.type);
        buf.putInt(owner.id);
        buf.putInt(owner.instanceId);
        buf.put(source.type);
        buf.putInt(source.id);
        buf.putInt(source.instanceId);
        buf.putInt(level);
        buf.putLong(Time.currentTimeMillis(endTime));
        buf.putInt(multiple);
        buf.putInt(remainSeconds);
        buf.putInt(tickInterval);
        buf.putInt(remainCure);
        buf.putInt(remainDamage);
        buf.putInt(remainMPCure);
        buf.putInt(remainMPDamage);
        buf.putInt(remainAbsorb);
        buf.putInt(effectTimes);
        return buf.array();
    }

    public boolean update2(int time) {
        endTime += time;
        if (endTime <= Time.currTime) {
            return false;
        }
        return true;
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (!isActive && context.damageType == CombatContext.DAMAGE_PHYSICAL) {
            int value = multiple * reduce_physical_damage_value;
            value += context.damage * multiple * reduce_physical_damage_percent / 100.0f;
            if (value > context.damage) {
                value = context.damage;
            }
            if (context.damage > 0) {
                context.threat -= value * context.threat / context.damage;
                context.damage -= value;
            }
            effectTimes++;
        }
        if (!isActive && context.damageType == CombatContext.DAMAGE_MAGIC) {
            int value = multiple * reduce_magic_damage_value;
            value += context.damage * multiple * reduce_magic_damage_percent / 100.0f;
            if (value > context.damage) {
                value = context.damage;
            }
            if (context.damage > 0) {
                context.threat -= value * context.threat / context.damage;
                context.damage -= value;
            }
            effectTimes++;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (!isActive && context.hited() && context.isDamage()) {
            if (CommonUtil.hit(RND, (int)(multiple * 100 * bounce_rate), 10000)) {
                int dmg = bounce_value;
                dmg += context.damage * bounce_percent_of_damage / 100.0f;
                context.passiveSkills.add(new FixedDamageSkill(bounce_damage_type, dmg));
                effectTimes++;
            }
        }
    }

}
