package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_026 implements Buff, SkillBuff, PropertyEnhancer, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
    public static int[] CHANGE_MAGIC_AP_VALUE = {
        0, 30, 53, 76, 99, 122, 145, 168, 191, 214, 237
    };
    public static float[] CHANGE_MAGIC_AP_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] CHANGE_THREAT_VALUE = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static float[] CHANGE_THREAT_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    Skill skill;
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_magic_ap_value;
    float change_magic_ap_percent;
    int change_threat_value;
    float change_threat_percent;

    public AutoGeneratedBuff_026(Skill skl, int lvl) {
        int dmg = 0;
        skill = skl;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        change_magic_ap_value = CHANGE_MAGIC_AP_VALUE[level];
        change_magic_ap_percent = CHANGE_MAGIC_AP_PERCENT[level];
        change_threat_value = CHANGE_THREAT_VALUE[level];
        change_threat_percent = CHANGE_THREAT_PERCENT[level];
    }

    public int getId() {
        return skill.getId();
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "智勇双全";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("提升法术攻击力{0}点", CommonUtil.formatValue(change_magic_ap_value * multiple));
    }

    public Skill getSkill() {
        return skill;
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_026) {
            AutoGeneratedBuff_026 other = (AutoGeneratedBuff_026)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                change_magic_ap_value = other.change_magic_ap_value;
                change_magic_ap_percent = other.change_magic_ap_percent;
                change_threat_value = other.change_threat_value;
                change_threat_percent = other.change_threat_percent;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        change_magic_ap_value = CHANGE_MAGIC_AP_VALUE[level];
        change_magic_ap_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 26, "change_magic_ap_value", change_magic_ap_value);
        change_magic_ap_percent = CHANGE_MAGIC_AP_PERCENT[level];
        change_magic_ap_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 26, "change_magic_ap_percent", change_magic_ap_percent);
        change_threat_value = CHANGE_THREAT_VALUE[level];
        change_threat_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 26, "change_threat_value", change_threat_value);
        change_threat_percent = CHANGE_THREAT_PERCENT[level];
        change_threat_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 26, "change_threat_percent", change_threat_percent);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.spellpowerRate += multiple * change_magic_ap_percent / 100.0f;
        pc.spellpower += multiple * change_magic_ap_value;
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive) {
            context.threatAdd += multiple * change_threat_value;
            context.threatAddRate += multiple * change_threat_percent / 100.0f;
            effectTimes++;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

}
