package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_002 implements Buff, PropertyEnhancer, Updatable, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1, -1, -1, -1, -1
    };
    public static int[] CHANGE_MAXHP_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] CHANGE_MAXHP_PERCENT = {
        0.0f, 10.0f, 13.0f, 16.0f, 19.0f, 22.0f
    };
    public static int[] HOT_SECONDS = {
        0, 30, 30, 30, 30, 30
    };
    public static int[] HOT_TICK_TIME = {
        0, 5, 5, 5, 5, 5
    };
    public static int[] HOT_VALUE = {
        0, 400, 550, 700, 850, 1000
    };
    public static float[] HOT_PERCENT_OF_DAMAGE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] CHANGE_THREAT_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] CHANGE_THREAT_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_maxhp_value;
    float change_maxhp_percent;
    int hot_seconds;
    int hot_tick_time;
    int hot_value;
    float hot_percent_of_damage;
    int change_threat_value;
    float change_threat_percent;

    public AutoGeneratedBuff_002(int lvl, Unit src, Unit tgt, int dmg) {
        if (src != null) {
            source = src.ref();
        }
        if (tgt != null) {
            owner = tgt.ref();
        }
        instanceID = BuffUtil.getNextID();
        level = lvl;
        endTime = Time.currTime + BuffUtil.enhanceParam(src, tgt, 2, "buffTime", DURATION[level]);
        multiple = 1;
        change_maxhp_value = CHANGE_MAXHP_VALUE[level];
        change_maxhp_value = BuffUtil.enhanceParam(src, tgt, 2, "change_maxhp_value", change_maxhp_value);
        change_maxhp_percent = CHANGE_MAXHP_PERCENT[level];
        change_maxhp_percent = BuffUtil.enhanceParam(src, tgt, 2, "change_maxhp_percent", change_maxhp_percent);
        hot_seconds = HOT_SECONDS[level];
        hot_seconds = BuffUtil.enhanceParam(src, tgt, 2, "hot_seconds", hot_seconds);
        hot_tick_time = HOT_TICK_TIME[level];
        hot_tick_time = BuffUtil.enhanceParam(src, tgt, 2, "hot_tick_time", hot_tick_time);
        hot_value = HOT_VALUE[level];
        hot_value = BuffUtil.enhanceParam(src, tgt, 2, "hot_value", hot_value);
        hot_percent_of_damage = HOT_PERCENT_OF_DAMAGE[level];
        hot_percent_of_damage = BuffUtil.enhanceParam(src, tgt, 2, "hot_percent_of_damage", hot_percent_of_damage);
        change_threat_value = CHANGE_THREAT_VALUE[level];
        change_threat_value = BuffUtil.enhanceParam(src, tgt, 2, "change_threat_value", change_threat_value);
        change_threat_percent = CHANGE_THREAT_PERCENT[level];
        change_threat_percent = BuffUtil.enhanceParam(src, tgt, 2, "change_threat_percent", change_threat_percent);
        remainSeconds = hot_seconds;
        tickInterval = hot_tick_time;
        remainCure = hot_value;
        remainCure += hot_percent_of_damage * dmg / 100.0f;
    }

    public int getId() {
        return 2;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "跃空提升";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("生命上限提升{0}，每5秒回复少量生命", CommonUtil.formatPercent(change_maxhp_percent * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return Time.currTime + remainSeconds * 1000;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return true;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return 10 | 0x1000000;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_002) {
            AutoGeneratedBuff_002 other = (AutoGeneratedBuff_002)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                change_maxhp_value = other.change_maxhp_value;
                change_maxhp_percent = other.change_maxhp_percent;
                hot_seconds = other.hot_seconds;
                hot_tick_time = other.hot_tick_time;
                hot_value = other.hot_value;
                hot_percent_of_damage = other.hot_percent_of_damage;
                change_threat_value = other.change_threat_value;
                change_threat_percent = other.change_threat_percent;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
    }

    public boolean update(int diff) {
        if (((remainSeconds - 1) % tickInterval) == 0) {
            int remainTicks = (remainSeconds - 1) / tickInterval + 1;
            int cure = remainCure / remainTicks;
            int dmg = remainDamage / remainTicks;
            int mpcure = remainMPCure / remainTicks;
            int mpdmg = remainMPDamage / remainTicks;
            remainCure -= cure;
            remainDamage -= dmg;
            remainMPCure -= mpcure;
            remainMPDamage -= mpdmg;
            if (cure > 0) {
                Unit healerUnit = (Unit)ObjectAccessor.getGameObject(source);
                Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
                if (targetUnit != null && targetUnit.isAlive()) {
                    cure = targetUnit.setHp(targetUnit.hp + cure, true);
                    if (healerUnit != null && healerUnit.isAlive()) {
                        Attack.addHealThreat(healerUnit, targetUnit, CombatContext.calcHotThreat(cure), false);
                    }
                }
            }
            if (dmg > 0) {
                Unit sourceUnit = (Unit)ObjectAccessor.getGameObject(source);
                Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
                if (targetUnit != null && targetUnit.isAlive()) {
                    targetUnit.setHp(targetUnit.hp - dmg, true);
                    if (sourceUnit != null && sourceUnit.isAlive()) {
                        Attack.addDamageThreat(sourceUnit, targetUnit, dmg, false);
                    }
                    if (targetUnit.hp <= 0) {
                        targetUnit.die(sourceUnit);
                    }
                }
            }
            if (mpcure > 0) {
                Unit healerUnit = (Unit)ObjectAccessor.getGameObject(source);
                Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
                if (targetUnit != null && targetUnit.isAlive()) {
                    targetUnit.setMp(targetUnit.mp + mpcure, true);
                    if (healerUnit != null && healerUnit.isAlive()) {
                        Attack.addHealThreat(healerUnit, targetUnit, mpcure, false);
                    }
                }
            }
            if (mpdmg > 0) {
                Unit sourceUnit = (Unit)ObjectAccessor.getGameObject(source);
                Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
                if (targetUnit != null && targetUnit.isAlive()) {
                    targetUnit.setMp(targetUnit.mp - mpdmg, true);
                    if (sourceUnit != null && sourceUnit.isAlive()) {
                        Attack.addDamageThreat(sourceUnit, targetUnit, mpdmg, false);
                    }
                }
            }
        }
        remainSeconds--;
        if (remainSeconds <= 0) {
            return true;
        }
        return false;
    }

    public void load(byte[] bytes) {
        ByteBuffer buf = ByteBuffer.wrap(bytes);
        owner = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        source = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        level = buf.getInt();
        endTime = Time.elapseTime(buf.getLong());
        multiple = buf.getInt();
        change_maxhp_value = CHANGE_MAXHP_VALUE[level];
        change_maxhp_percent = CHANGE_MAXHP_PERCENT[level];
        hot_seconds = HOT_SECONDS[level];
        hot_tick_time = HOT_TICK_TIME[level];
        hot_value = HOT_VALUE[level];
        hot_percent_of_damage = HOT_PERCENT_OF_DAMAGE[level];
        change_threat_value = CHANGE_THREAT_VALUE[level];
        change_threat_percent = CHANGE_THREAT_PERCENT[level];
        remainSeconds = buf.getInt();
        tickInterval = buf.getInt();
        remainCure = buf.getInt();
        remainDamage = buf.getInt();
        remainMPCure = buf.getInt();
        remainMPDamage = buf.getInt();
        remainAbsorb = buf.getInt();
        effectTimes = buf.getInt();
    }

    public byte[] save() {
        ByteBuffer buf = ByteBuffer.allocate(66, false);
        buf.put(owner.type);
        buf.putInt(owner.id);
        buf.putInt(owner.instanceId);
        buf.put(source.type);
        buf.putInt(source.id);
        buf.putInt(source.instanceId);
        buf.putInt(level);
        buf.putLong(Time.currentTimeMillis(endTime));
        buf.putInt(multiple);
        buf.putInt(remainSeconds);
        buf.putInt(tickInterval);
        buf.putInt(remainCure);
        buf.putInt(remainDamage);
        buf.putInt(remainMPCure);
        buf.putInt(remainMPDamage);
        buf.putInt(remainAbsorb);
        buf.putInt(effectTimes);
        return buf.array();
    }

    public boolean update2(int time) {
        remainSeconds -= time / 1000;
        if (remainSeconds <= 0) {
            return false;
        }
        return true;
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.hp += multiple * change_maxhp_value;
        pc.hpRate += multiple * change_maxhp_percent / 100.0f;
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive) {
            context.threatAdd += multiple * change_threat_value;
            context.threatAddRate += multiple * change_threat_percent / 100.0f;
            effectTimes++;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

}
