package com.pip.j0ide.i18n;
/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface GenericParserConstants {

	  /** End of File. */
	  int EOF = 0;
	  /** RegularExpression Id. */
	  int BOOLEAN = 5;
	  /** RegularExpression Id. */
	  int BREAK = 6;
	  /** RegularExpression Id. */
	  int BYTE = 7;
	  /** RegularExpression Id. */
	  int CONTINUE = 8;
	  /** RegularExpression Id. */
	  int ELSE = 9;
	  /** RegularExpression Id. */
	  int IF = 10;
	  /** RegularExpression Id. */
	  int INT = 11;
	  /** RegularExpression Id. */
	  int SHORT = 12;
	  /** RegularExpression Id. */
	  int STRING = 13;
	  /** RegularExpression Id. */
	  int WHILE = 14;
	  /** RegularExpression Id. */
	  int VERSION = 15;
	  /** RegularExpression Id. */
	  int LIBRARY = 16;
	  /** RegularExpression Id. */
	  int ID = 17;
	  /** RegularExpression Id. */
	  int ATTRIBUTE = 18;
	  /** RegularExpression Id. */
	  int NAME = 19;
	  /** RegularExpression Id. */
	  int DESCRIPTION = 20;
	  /** RegularExpression Id. */
	  int DATA = 21;
	  /** RegularExpression Id. */
	  int RETURN = 22;
	  /** RegularExpression Id. */
	  int FUNCTION = 23;
	  /** RegularExpression Id. */
	  int CALLBACK = 24;
	  /** RegularExpression Id. */
	  int NEW = 25;
	  /** RegularExpression Id. */
	  int FREE = 26;
	  /** RegularExpression Id. */
	  int SPRITE = 27;
	  /** RegularExpression Id. */
	  int IMAGESET = 28;
	  /** RegularExpression Id. */
	  int STREAM = 29;
	  /** RegularExpression Id. */
	  int UWAPSEGMENT = 30;
	  /** RegularExpression Id. */
	  int VECTOR = 31;
	  /** RegularExpression Id. */
	  int HASHTABLE = 32;
	  /** RegularExpression Id. */
	  int OBJECT = 33;
	  /** RegularExpression Id. */
	  int STRUCT = 34;
	  /** RegularExpression Id. */
	  int EXTENDS = 35;
	  /** RegularExpression Id. */
	  int FOR = 36;
	  /** RegularExpression Id. */
	  int SWITCH = 37;
	  /** RegularExpression Id. */
	  int CASE = 38;
	  /** RegularExpression Id. */
	  int SWITCHDEFAULT = 39;
	  /** RegularExpression Id. */
	  int INSTANCEOF = 40;
	  /** RegularExpression Id. */
	  int NUMBER_CONSTANT = 41;
	  /** RegularExpression Id. */
	  int DECIMAL_CONSTANT = 42;
	  /** RegularExpression Id. */
	  int HEX_CONSTANT = 43;
	  /** RegularExpression Id. */
	  int STRING_CONSTANT = 44;
	  /** RegularExpression Id. */
	  int CHAR_CONSTANT = 45;
	  /** RegularExpression Id. */
	  int IDENTIFIER = 46;
	  /** RegularExpression Id. */
	  int LETTER = 47;
	  /** RegularExpression Id. */
	  int DIGIT = 48;
	  /** RegularExpression Id. */
	  int LPAREN = 49;
	  /** RegularExpression Id. */
	  int RPAREN = 50;
	  /** RegularExpression Id. */
	  int LBRACE = 51;
	  /** RegularExpression Id. */
	  int RBRACE = 52;
	  /** RegularExpression Id. */
	  int SEMICOLON = 53;
	  /** RegularExpression Id. */
	  int COMMA = 54;
	  /** RegularExpression Id. */
	  int LBRACKET = 55;
	  /** RegularExpression Id. */
	  int RBRACKET = 56;
	  /** RegularExpression Id. */
	  int FULLSTOP = 57;
	  /** RegularExpression Id. */
	  int COLON = 58;
	  /** RegularExpression Id. */
	  int ASSIGN = 59;
	  /** RegularExpression Id. */
	  int GT = 60;
	  /** RegularExpression Id. */
	  int LT = 61;
	  /** RegularExpression Id. */
	  int EQ = 62;
	  /** RegularExpression Id. */
	  int LE = 63;
	  /** RegularExpression Id. */
	  int GE = 64;
	  /** RegularExpression Id. */
	  int NE = 65;
	  /** RegularExpression Id. */
	  int PLUS = 66;
	  /** RegularExpression Id. */
	  int MINUS = 67;
	  /** RegularExpression Id. */
	  int MULTIPLY = 68;
	  /** RegularExpression Id. */
	  int DIVIDE = 69;
	  /** RegularExpression Id. */
	  int MOD = 70;
	  /** RegularExpression Id. */
	  int AND = 71;
	  /** RegularExpression Id. */
	  int OR = 72;
	  /** RegularExpression Id. */
	  int ANDB = 73;
	  /** RegularExpression Id. */
	  int ORB = 74;
	  /** RegularExpression Id. */
	  int QUESTION = 75;
	  /** RegularExpression Id. */
	  int NOT = 76;
	  /** RegularExpression Id. */
	  int NOTB = 77;
	  /** RegularExpression Id. */
	  int XOR = 78;
	  /** RegularExpression Id. */
	  int LSHIFT = 79;
	  /** RegularExpression Id. */
	  int RSHIFT = 80;
	  /** RegularExpression Id. */
	  int PLUSASSIGN = 81;
	  /** RegularExpression Id. */
	  int MINUSASSIGN = 82;
	  /** RegularExpression Id. */
	  int MULTIPLYASSIGN = 83;
	  /** RegularExpression Id. */
	  int DIVIDEASSIGN = 84;
	  /** RegularExpression Id. */
	  int MODASSIGN = 85;
	  /** RegularExpression Id. */
	  int ANDBASSIGN = 86;
	  /** RegularExpression Id. */
	  int ORBASSIGN = 87;
	  /** RegularExpression Id. */
	  int PLUSPLUS = 88;
	  /** RegularExpression Id. */
	  int MINUSMINUS = 89;
	  /** RegularExpression Id. */
	  int LSHIFTASSIGN = 90;
	  /** RegularExpression Id. */
	  int RSHIFTASSIGN = 91;
	  /** RegularExpression Id. */
	  int NOTBASSIGN = 92;
	  /** RegularExpression Id. */
	  int XORASSIGN = 93;

	  /** Lexical state. */
	  int DEFAULT = 0;

	  /** Literal token values. */
	  String[] tokenImage = {
	    "<EOF>",
	    "\" \"",
	    "\"\\t\"",
	    "\"\\n\"",
	    "\"\\r\"",
	    "\"boolean\"",
	    "\"break\"",
	    "\"byte\"",
	    "\"continue\"",
	    "\"else\"",
	    "\"if\"",
	    "\"int\"",
	    "\"short\"",
	    "\"String\"",
	    "\"while\"",
	    "\"VERSION\"",
	    "\"LIBRARY\"",
	    "\"ID\"",
	    "\"ATTRIBUTE\"",
	    "\"NAME\"",
	    "\"DESCRIPTION\"",
	    "\"DATA\"",
	    "\"return\"",
	    "\"FUNCTION\"",
	    "\"CALLBACK\"",
	    "\"new\"",
	    "\"free\"",
	    "\"Sprite\"",
	    "\"ImageSet\"",
	    "\"Stream\"",
	    "\"UWAPSegment\"",
	    "\"Vector\"",
	    "\"Hashtable\"",
	    "\"Object\"",
	    "\"STRUCT\"",
	    "\"extends\"",
	    "\"for\"",
	    "\"switch\"",
	    "\"case\"",
	    "\"default\"",
	    "\"instanceof\"",
	    "<NUMBER_CONSTANT>",
	    "<DECIMAL_CONSTANT>",
	    "<HEX_CONSTANT>",
	    "<STRING_CONSTANT>",
	    "<CHAR_CONSTANT>",
	    "<IDENTIFIER>",
	    "<LETTER>",
	    "<DIGIT>",
	    "\"(\"",
	    "\")\"",
	    "\"{\"",
	    "\"}\"",
	    "\";\"",
	    "\",\"",
	    "\"[\"",
	    "\"]\"",
	    "\".\"",
	    "\":\"",
	    "\"=\"",
	    "\">\"",
	    "\"<\"",
	    "\"==\"",
	    "\"<=\"",
	    "\">=\"",
	    "\"!=\"",
	    "\"+\"",
	    "\"-\"",
	    "\"*\"",
	    "\"/\"",
	    "\"%\"",
	    "\"&&\"",
	    "\"||\"",
	    "\"&\"",
	    "\"|\"",
	    "\"?\"",
	    "\"!\"",
	    "\"~\"",
	    "\"^\"",
	    "\"<<\"",
	    "\">>\"",
	    "\"+=\"",
	    "\"-=\"",
	    "\"*=\"",
	    "\"/=\"",
	    "\"%=\"",
	    "\"&=\"",
	    "\"|=\"",
	    "\"++\"",
	    "\"--\"",
	    "\"<<=\"",
	    "\">>=\"",
	    "\"~=\"",
	    "\"^=\"",
	  };

}
