localip=127.0.0.1
port=9761
serverpassword=itimes
receivebuffsize=524287
writebuffsize=524287
tcpnodelay=true
poolbuffer=true
directbuffer=true
feehttpurl=127.0.0.1
feehttpport=9103
connectsessionfactory=pip