/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package com.pip.sanguo.data.quest.pqe;

public interface ParserConstants {

  int EOF = 0;
  int NUMBER_CONSTANT = 5;
  int DECIMAL_CONSTANT = 6;
  int HEX_CONSTANT = 7;
  int STRING_CONSTANT = 8;
  int IDENTIFIER = 9;
  int LETTER = 10;
  int DIGIT = 11;
  int LPAREN = 12;
  int RPAREN = 13;
  int LBRACE = 14;
  int RBRACE = 15;
  int SEMICOLON = 16;
  int COMMA = 17;
  int LBRACKET = 18;
  int RBRACKET = 19;
  int FULLSTOP = 20;
  int ASSIGN = 21;
  int GT = 22;
  int LT = 23;
  int EQ = 24;
  int LE = 25;
  int GE = 26;
  int NE = 27;
  int PLUS = 28;
  int MINUS = 29;
  int MULTIPLY = 30;
  int DIVIDE = 31;
  int MOD = 32;
  int AND = 33;
  int OR = 34;
  int ANDB = 35;
  int ORB = 36;
  int LSHIFT = 37;
  int RSHIFT = 38;
  int PLUSASSIGN = 39;
  int MINUSASSIGN = 40;
  int MULTIPLYASSIGN = 41;
  int DIVIDEASSIGN = 42;
  int MODASSIGN = 43;
  int ANDBASSIGN = 44;
  int ORBASSIGN = 45;
  int PLUSPLUS = 46;
  int MINUSMINUS = 47;
  int LSHIFTASSIGN = 48;
  int RSHIFTASSIGN = 49;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NUMBER_CONSTANT>",
    "<DECIMAL_CONSTANT>",
    "<HEX_CONSTANT>",
    "<STRING_CONSTANT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&&\"",
    "\"||\"",
    "\"&\"",
    "\"|\"",
    "\"<<\"",
    "\">>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"++\"",
    "\"--\"",
    "\"<<=\"",
    "\">>=\"",
  };

}
