package com.pip.itimes.server.world;

import java.util.Date;
import java.util.List;
import java.util.Random;

import com.pip.itimes.server.bean.Player;
import com.pip.itimes.server.stage.Ability;
import com.pip.itimes.server.stage.Buf;
import com.pip.itimes.server.stage.Changed;
import com.pip.itimes.server.stage.Friend;
import com.pip.itimes.server.stage.Grid;
import com.pip.itimes.server.stage.IEquipment;
import com.pip.itimes.server.stage.IItem;
import com.pip.itimes.server.stage.IItemTemplate;
import com.pip.itimes.server.stage.Pet;
import com.pip.itimes.server.stage.PlayerData;
import com.pip.itimes.server.stage.RoleFaceData;
import com.pip.itimes.server.world.game.GameMap;

public interface IPlayerData{
	public int getId();
	public boolean inPkMap();
	public int getRealStrength();
	public int getRealVitality();
	public int getRealIntelligence();
	public int getRealAgility();
	public int getHp();
	public void setHp(int hp);
	public int getMaxMp();
	public int getMp();
	public void setMp(int mp);
	public int getMaxHp();
	public int getLevel();
	public int getLuck();
	public int getVianyType();
	public int getBufProperty(int pro);
	public IEquipment[] getUsedEquipments();
	public void addDiamondShineBuf(int[] level);
	public List getDiamondShineList();
	public int getDiamondShineBufAttri(int pro);
	public int calculateMaxHpWithoutDiamondShine();
	public String getPlayerName();
	public short getFace();
	public int getTeamState();
	public int calculateMaxHp();
	public int calculateMaxMp();
	public Pet[] getOetherPet();
	public boolean hasItem(IItem item, int count);
	public boolean containsAbility(Ability ability);
	public Pet getPet();
	public IEquipment getWeapon();
	public byte getLightLevel();
	public GameMap getMap();
	public void incCampDeadTime(int playerLevel);
	public boolean hasBuf(int pro);
	public Buf[] getBufs();
	public void removeBuf(Buf buf, Changed changed);
	public byte getCamp();
	public int getCredit();
	public int hasCampLoopTask();
	public int getClientDataVersion();
	public int addItem(IItemTemplate template, int count, Changed changed,int dataVersion);
	public void addCampWin(int win);
	public void addCampLost(int lost);
	public void addCredit(int credit,Changed changed);
	public int decCredit(int credit,Changed changed);
	public void addEnemy(int id,String name,long lastTime);
	public void addSneaks(int num);
	public void setDeadTime(int value);
	public void removeUsedEquipmentDurability(IEquipment equ, int value,
            Changed changed);
	public short getMapId();
	public int getMoeny();
	public Grid getEquipmentByInstanceid(int instanceId);
	public IItem completeRemoveItem(IItem item, int count, Changed changed);
	public boolean hasItem(int itemId);
	public void acquire();
	public void setBattle(boolean battleFlag);
	public void clearDeadTime();
	public boolean hasTask(short taskId);
	public Team getTeam();
	public void setTeamState(int state);
	public void release();
	public int  getItemCount(int itemId);
	public int getRef();
	public int calcOnlineLife();
	public void setUnlineOnlineLife(int life);
	public int getFame();
	public void setLastlogoutTime(Date lastlogoutTime);
	public int getAccountId();
	public void reset();
	public Player getPlayer();
	public List getImage();
	public void setDefaultFace ();
	public RoleFaceData completeAddRoleFace(int face, int count, Changed changed, long time);
	public void resetImage();
	public void addMoney(int money, Changed changed);
	public void setMoeny(int moeny);
	public int getFriendFavorite(PlayerData player);
	public byte getSex();
	public Friend[] getFriends();
	public boolean hasEquipmented(int itemId);
	public int getArenaV1Id();
	public void decMoney(int money, Changed changed);
	public void setArenaV1Id(int arenaV1Id);
	public int getArenaLevel();
	public void setArenaLevel(int arenaLevel);
	public int getArenaV2Id();
	public void setArenaV2Id(int arenaV2Id);
	public int getArenaV3Id();
	public void setArenaV3Id(int arenaV3Id);
	public int getTongId();
	public void setTongTitle(String tongTitle);
	public int getTongDuty();
	public void setTongDuty(int tongDuty);
	public String getTongTitle();
	public void setTongId(int tongId);
	public void setTongName(String tongName);
	public void setContribution(int contribution);
	public int getContribution();
	public void removeFavor(Pet pet, int value, Changed changed, Random rnd);
	public Buf getCampBuf(int pro);
	public void setHolyGemLightLevel(byte level);
	public byte getHolyGemLightLevel();
	public void setFantasyGemLightLevel(byte level);
	public byte getFantasyGemLightLevel();
	public void setBossRushStage(int bossRushStage);
	public int[] getSuitEffectDiamondAddValue();
	public int[] getTrainLevel();
	public int[] getTrainAttributeAddValue();
	public int[] getMagicPosLevel();
	public int[] getMagicPosFloor();
}
