package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;

public class AutoGeneratedSkill_034 extends AbstractSkill {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 0, 0, 0, 0, 0, 0, 0
    };
    public static float[] MP_USE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] ACT_TIME = {
        0, 0, 0, 0, 0, 0, 0, 0
    };
    public static int[] CD_TIME = {
        0, 0, 0, 0, 0, 0, 0, 0
    };
    public static int[] DISTANCE = {
        0, 0, 0, 0, 0, 0, 0, 0
    };
    public static int[] RANGE = {
        0, 0, 0, 0, 0, 0, 0, 0
    };

    public AutoGeneratedSkill_034(int lvl) {
        super(34, "明心见性", lvl);
        if (lvl > 7) {
            throw new IllegalArgumentException();
        }
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 0;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = 55;
        prepareAnimation = -1;
        castAnimation = -1;
        hitAnimation = -1;
        clazz = -1;
        mp = MP_USE[lvl];
        type = TYPE_PASSIVE;
        targetType = TARGET_AID_SELF;
    }

    public String getDesc(Unit owner) {
        return java.text.MessageFormat.format("法术防御力提升{0}，体力增加{1}点", CommonUtil.formatPercent(peony.game.buff.AutoGeneratedBuff_057.CHANGE_MAGIC_ARMOR_PERCENT[level]), CommonUtil.formatValue(peony.game.buff.AutoGeneratedBuff_057.CHANGE_STA_VALUE[level]));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        return null;
    }

    public Buff newBuff() {
        if (level == 0) {
            return null;
        }
        return BuffUtil.createSkillBuff(57, this);
    }

    public Buff getAreaBuff() {
        return null;
    }

}
