package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;

public class AutoGeneratedSkill_234 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] MP_USE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] ACT_TIME = {
        0, 0, 0, 0, 0, 0
    };
    public static int[] CD_TIME = {
        0, 0, 0, 0, 0, 0
    };
    public static int[] DISTANCE = {
        0, 104, 104, 104, 104, 104
    };
    public static int[] RANGE = {
        0, 0, 0, 0, 0, 0
    };
    public static int[] CURE_VALUE = {
        0, 10000, 20000, 40000, 80000, 160000
    };
    public static float[] DISPEL_ALL_DEBUFF_RATE = {
        0.0f, 60.0f, 70.0f, 80.0f, 90.0f, 100.0f
    };
    public static float[] ADD_DEBUFF_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f
    };
    public static String[] ADD_DEBUFF_RATE_VAR = {
        "", "", "", "", "", ""
    };
    public static int[] ADD_DEBUFF_ID = {
        0, 282, 282, 282, 282, 282
    };
    public static int[] ADD_DEBUFF_LEVEL = {
        0, 1, 2, 3, 4, 5
    };
    int cure_value;
    float dispel_all_debuff_rate;
    float add_debuff_rate;
    String add_debuff_rate_var;
    int add_debuff_id;
    int add_debuff_level;

    public AutoGeneratedSkill_234(int lvl) {
        super(234, "ТырІЦ№їК", lvl);
        if (lvl > 5) {
            throw new IllegalArgumentException();
        }
        cure_value = CURE_VALUE[lvl];
        dispel_all_debuff_rate = DISPEL_ALL_DEBUFF_RATE[lvl];
        add_debuff_rate = ADD_DEBUFF_RATE[lvl];
        add_debuff_rate_var = ADD_DEBUFF_RATE_VAR[lvl];
        add_debuff_id = ADD_DEBUFF_ID[lvl];
        add_debuff_level = ADD_DEBUFF_LEVEL[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 234;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = -1;
        prepareAnimation = -1;
        castAnimation = -65534;
        hitAnimation = 115;
        clazz = -1;
        mp = MP_USE[lvl];
        type = TYPE_AID;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_SINGLE_AID;
    }

    public String getDesc(Unit owner) {
        return "";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_HEAL;
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        context.attackPower += context.getSkillParam(this, "cure_value", cure_value);
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited()) {
            int rate = (int)(100 * context.getSkillParam(this, "dispel_all_debuff_rate", dispel_all_debuff_rate));
            if (CommonUtil.hit(RND, rate, 10000)) {
                context.target.buffs.dispelBadBuff(true);
            }
        }
        if (context.hited()) {
            boolean hit = false;
            if (add_debuff_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(100 * context.getSkillParam(this, "add_debuff_rate", add_debuff_rate)), 10000);
            } else {
                Float vo = context.skillParams.get(add_debuff_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(100 * (vo.floatValue() + context.getSkillParam(this, "add_debuff_rate", add_debuff_rate))), 10000);
                }
            }
            if (hit) {
                context.target.buffs.addBuff(BuffUtil.createBuff(add_debuff_id, add_debuff_level, context.source, context.target, context.damage));
            }
        }
    }

}
