package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;

public class AutoGeneratedSkill_315 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static float[] MP_USE = {
        0.0f, -1.6f, -1.65f, -1.7f, -1.75f, -1.8f, -1.85f, -1.9f, -1.95f, -2.0f, -2.05f
    };
    public static int[] ACT_TIME = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static int[] CD_TIME = {
        0, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000
    };
    public static int[] DISTANCE = {
        0, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56
    };
    public static int[] RANGE = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static int[] CHANGE_PHYSICAL_AP_VALUE = {
        0, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110
    };
    public static float[] CHANGE_PHYSICAL_AP_PERCENT = {
        0.0f, -35.0f, -30.0f, -25.0f, -20.0f, -15.0f, -10.0f, -5.0f, 0.0f, 5.0f, 10.0f
    };
    public static float[] ADD_DEBUFF_RATE = {
        0.0f, 75.0f, 75.0f, 75.0f, 75.0f, 75.0f, 75.0f, 75.0f, 75.0f, 75.0f, 75.0f
    };
    public static String[] ADD_DEBUFF_RATE_VAR = {
        "", "", "", "", "", "", "", "", "", "", ""
    };
    public static int[] ADD_DEBUFF_ID = {
        0, 402, 402, 402, 402, 402, 402, 402, 402, 402, 402
    };
    public static int[] ADD_DEBUFF_LEVEL = {
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
    };
    int change_physical_ap_value;
    float change_physical_ap_percent;
    float add_debuff_rate;
    String add_debuff_rate_var;
    int add_debuff_id;
    int add_debuff_level;

    public AutoGeneratedSkill_315(int lvl) {
        super(315, "断骨刀法", lvl);
        if (lvl > 10) {
            throw new IllegalArgumentException();
        }
        change_physical_ap_value = CHANGE_PHYSICAL_AP_VALUE[lvl];
        change_physical_ap_percent = CHANGE_PHYSICAL_AP_PERCENT[lvl];
        add_debuff_rate = ADD_DEBUFF_RATE[lvl];
        add_debuff_rate_var = ADD_DEBUFF_RATE_VAR[lvl];
        add_debuff_id = ADD_DEBUFF_ID[lvl];
        add_debuff_level = ADD_DEBUFF_LEVEL[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 315;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = 2;
        prepareAnimation = -65536;
        castAnimation = -65536;
        hitAnimation = 116;
        clazz = -1;
        mp = MP_USE[lvl];
        type = TYPE_ATTACK;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_SINGLE_ATTACK;
    }

    public String getDesc(Unit owner) {
        return java.text.MessageFormat.format("此刀法势大力沉有断骨的威力，造成{0}物理攻击力伤害和{1}点额外物理伤害；同时有{2}几率使目标流血，在10秒内损失{3}点生命", CommonUtil.formatPercent(change_physical_ap_value), CommonUtil.formatValue(change_physical_ap_value), CommonUtil.formatPercent(add_debuff_rate), CommonUtil.formatValue(peony.game.buff.AutoGeneratedBuff_402.DOT_VALUE[add_debuff_level]));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_PHYSICAL;
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        context.attackPower += context.getSkillParam(this, "change_physical_ap_value", change_physical_ap_value);
        context.attackPowerRate += context.getSkillParam(this, "change_physical_ap_percent", change_physical_ap_percent) / 100.0f;
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited()) {
            boolean hit = false;
            if (add_debuff_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(100 * context.getSkillParam(this, "add_debuff_rate", add_debuff_rate)), 10000);
            } else {
                Float vo = context.skillParams.get(add_debuff_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(100 * (vo.floatValue() + context.getSkillParam(this, "add_debuff_rate", add_debuff_rate))), 10000);
                }
            }
            if (hit) {
                context.target.buffs.addBuff(BuffUtil.createBuff(add_debuff_id, add_debuff_level, context.source, context.target, context.damage));
            }
        }
    }

}
