package peony.patchs;

import peony.game.OpCode;
import peony.game.stepserver.StepClient;

public class StepCodePatch implements Runnable {

	public void run() {
		StepClient.stepOpCodes = new short[]{OpCode.SYNC_TIME_CLIENT,OpCode.MOVE_CLIENT,OpCode.RIDE_CLIENT,
				OpCode.UNRIDE_CLIENT,OpCode.TOUCHNPC_CLIENT,OpCode.LOADING_FINISHED_CLIENT,OpCode.ITEMINFO_CLIENT,
				OpCode.USEITEM_CLIENT,OpCode.BAG_CLIENT,OpCode.SKILL_LIST_CLIENT,
				OpCode.SKILL_REFRESH_CLIENT,OpCode.SKILL_NAMELIST_CLIENT,OpCode.ITEM_DESC_CLIENT,
				OpCode.EQUIP_CLIENT,OpCode.UNEQUIP_CLIENT,OpCode.PROPERTYPOINT_ADD_CLIENT,OpCode.SKILL_DESC_CLIENT,
				OpCode.SKILL_ATTACK_CLIENT,OpCode.UNIT_INFO_CLIENT,OpCode.PLAYER_INFO_CLIENT,
				OpCode.RELIVE_CLIENT,OpCode.CANCEL_AUTOATTACK_CLIENT,OpCode.CANCEL_ATTACK_CLIENT,OpCode.CANCEL_USEITEM_CLIENT,
				OpCode.REPAIR_CLIENT,OpCode.OUT_PRISON_CLIENT,OpCode.GRID_EXCHANGE_CLIENT,OpCode.GET_MOVE_CLIENT,
				OpCode.FINDPATH_CLIENT,OpCode.TITLES_GET_CLIENT,OpCode.TITLE_SET_CLIENT,OpCode.TITLE_REMOVE_CLIENT,
				OpCode.TITLE_LIST_CLIENT,OpCode.TITLE_BUY_CLIENT,OpCode.FORGET_SKILL_CLIENT,OpCode.CONFIG_CLIENT,
				OpCode.CONFIG_SAVE_CLIENT,OpCode.HORSE_EQUIP_CLIENT,OpCode.HORSE_RIDE_CLIENT,OpCode.HORSE_FEED_CLIENT,
				OpCode.HORSE_FOOD_CLIENT,OpCode.HORSE_CHANGE_SKILL_CLIENT,OpCode.HORSE_BAG_CLIENT,OpCode.HORSE_PACK_CLIENT,
				OpCode.HORSE_UNEQU_CLIENT,OpCode.HORSE_UNRIDE_CLIENT,OpCode.GATHER_CANCEL_CLIENT,OpCode.SKILL_REFRESH_MONEY_CLIENT,
				OpCode.BAG_ARRANGE_CLIENT,OpCode.NATION_INFO_CLIENT,OpCode.TELEPORT_CLIENT,OpCode.NPC_DESC_CLIENT,
				OpCode.WORLD_TELEPORT_CLIENT,OpCode.GET_FILE_CLIENT,OpCode.GLOBAL_NPC_LIST_CLIENT,OpCode.GLOBAL_NPC_DESC_CLIENT,
				OpCode.ATTENDANT_BAG_CLIENT,OpCode.ATTENDANT_FOLLOW_CLIENT,OpCode.ATTENDANT_CANCELFOLLOW_CLIENT,
				OpCode.ATTENDANT_EQUIP_CLIENT,OpCode.ATTENDANT_UNEQUIP_CLIENT,OpCode.ATTENDANT_ADDLOYAL_CLIENT,
				OpCode.PLAYER_SET_FIND_PATH_CLIENT,OpCode.START_7_BUFF_DESC_CLIENT,OpCode.EFFECT_JEWEL_GET_CLIENT,
				OpCode.NEW_GETFILE_CLIENT,OpCode.USE_KINGITEM_CLIENT,OpCode.GETFILE_CLIENT,OpCode.SUITE_CLIENT,
				OpCode.DECORATE_GET_CONFIG_CLIENT,OpCode.CHARGE_INFO_CLIENT,OpCode.BUFF_DESC_CLIENT,OpCode.CMCC_ISHOP_LIST_CLIENT,
				OpCode.BUFF_DESC_BYID_CLIENT,OpCode.PHONE_NOTIFY_CLIENT,OpCode.LOADING_FINISHED1_CLIENT,OpCode.MAP_NPC_CLINT};
		System.out.println("__________loadStepCodeOK");
	}

}
