package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_579 implements Buff, PropertyEnhancer {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
    public static float[] ADD_JEWEL_PERCENT = {
        0.0f, 1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f, 9.0f, 10.0f, 11.0f, 12.0f, 13.0f, 14.0f, 15.0f
    };
    int instanceID;
    int realWeight;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    float add_jewel_percent;


    public AutoGeneratedBuff_579(int lvl) {
        int dmg = 0;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        add_jewel_percent = ADD_JEWEL_PERCENT[level];
    }

    public int getId() {
        return 579;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "坐骑宝石";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("增加坐骑宝石镶嵌效果{0}", CommonUtil.formatPercent(add_jewel_percent * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return true;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public int getMergeStrategy() {
        return 0;
    }

    public boolean isNeedMerge() {
        return false;
    }

    public float getchange_dembuff_rate() {
         return 0;
    }

    public boolean merge(Buff buff) {
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        add_jewel_percent = ADD_JEWEL_PERCENT[level];
        add_jewel_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 579, "add_jewel_percent", add_jewel_percent);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        if (add_jewel_percent > 0.0f) {
            pc.horseJewelEnhance += (multiple * add_jewel_percent / 100.0f);
        }
    }

}
