package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_577 implements Buff, ParamEnhancer, PropertyEnhancer {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1, -1, -1, -1, -1
    };
    public static int[] CHANGE_INT_VALUE = {
        0, 120, 144, 168, 192, 216
    };
    public static float[] CHANGE_INT_RATE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_1 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_1 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_1 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_2 = {
        "", "2,11,4", "2,11,4", "2,11,4", "2,11,4", "2,11,4"
    };
    public static float[] CHANGE_PARAM_VALUE_2 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_2 = {
        0.0f, -50.0f, -50.0f, -50.0f, -50.0f, -50.0f
    };
    public static String[] CHANGE_PARAM_3 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_3 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_3 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_4 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_4 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_4 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_5 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_5 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_5 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_6 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_6 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_6 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_7 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_7 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_7 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_8 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_8 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_8 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_9 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_9 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_9 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_10 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_10 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_10 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    int instanceID;
    int realWeight;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_int_value;
    float change_int_rate;
    String change_param_1;
    float change_param_value_1;
    float change_param_percent_1;
    String change_param_2;
    float change_param_value_2;
    float change_param_percent_2;
    String change_param_3;
    float change_param_value_3;
    float change_param_percent_3;
    String change_param_4;
    float change_param_value_4;
    float change_param_percent_4;
    String change_param_5;
    float change_param_value_5;
    float change_param_percent_5;
    String change_param_6;
    float change_param_value_6;
    float change_param_percent_6;
    String change_param_7;
    float change_param_value_7;
    float change_param_percent_7;
    String change_param_8;
    float change_param_value_8;
    float change_param_percent_8;
    String change_param_9;
    float change_param_value_9;
    float change_param_percent_9;
    String change_param_10;
    float change_param_value_10;
    float change_param_percent_10;


    public AutoGeneratedBuff_577(int lvl) {
        int dmg = 0;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        change_int_value = CHANGE_INT_VALUE[level];
        change_int_rate = CHANGE_INT_RATE[level];
        change_param_1 = CHANGE_PARAM_1[level];
        change_param_value_1 = CHANGE_PARAM_VALUE_1[level];
        change_param_percent_1 = CHANGE_PARAM_PERCENT_1[level];
        change_param_2 = CHANGE_PARAM_2[level];
        change_param_value_2 = CHANGE_PARAM_VALUE_2[level];
        change_param_percent_2 = CHANGE_PARAM_PERCENT_2[level];
        change_param_3 = CHANGE_PARAM_3[level];
        change_param_value_3 = CHANGE_PARAM_VALUE_3[level];
        change_param_percent_3 = CHANGE_PARAM_PERCENT_3[level];
        change_param_4 = CHANGE_PARAM_4[level];
        change_param_value_4 = CHANGE_PARAM_VALUE_4[level];
        change_param_percent_4 = CHANGE_PARAM_PERCENT_4[level];
        change_param_5 = CHANGE_PARAM_5[level];
        change_param_value_5 = CHANGE_PARAM_VALUE_5[level];
        change_param_percent_5 = CHANGE_PARAM_PERCENT_5[level];
        change_param_6 = CHANGE_PARAM_6[level];
        change_param_value_6 = CHANGE_PARAM_VALUE_6[level];
        change_param_percent_6 = CHANGE_PARAM_PERCENT_6[level];
        change_param_7 = CHANGE_PARAM_7[level];
        change_param_value_7 = CHANGE_PARAM_VALUE_7[level];
        change_param_percent_7 = CHANGE_PARAM_PERCENT_7[level];
        change_param_8 = CHANGE_PARAM_8[level];
        change_param_value_8 = CHANGE_PARAM_VALUE_8[level];
        change_param_percent_8 = CHANGE_PARAM_PERCENT_8[level];
        change_param_9 = CHANGE_PARAM_9[level];
        change_param_value_9 = CHANGE_PARAM_VALUE_9[level];
        change_param_percent_9 = CHANGE_PARAM_PERCENT_9[level];
        change_param_10 = CHANGE_PARAM_10[level];
        change_param_value_10 = CHANGE_PARAM_VALUE_10[level];
        change_param_percent_10 = CHANGE_PARAM_PERCENT_10[level];
    }

    public int getId() {
        return 577;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "天命套装7件谋士";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("提高智力{0}点，气血俱动耗蓝减少一半。", CommonUtil.formatValue(change_int_value * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public int getMergeStrategy() {
        return 2;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public float getchange_dembuff_rate() {
         return 0;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_577) {
            AutoGeneratedBuff_577 other = (AutoGeneratedBuff_577)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                change_int_value = other.change_int_value;
                change_int_rate = other.change_int_rate;
                change_param_1 = other.change_param_1;
                change_param_value_1 = other.change_param_value_1;
                change_param_percent_1 = other.change_param_percent_1;
                change_param_2 = other.change_param_2;
                change_param_value_2 = other.change_param_value_2;
                change_param_percent_2 = other.change_param_percent_2;
                change_param_3 = other.change_param_3;
                change_param_value_3 = other.change_param_value_3;
                change_param_percent_3 = other.change_param_percent_3;
                change_param_4 = other.change_param_4;
                change_param_value_4 = other.change_param_value_4;
                change_param_percent_4 = other.change_param_percent_4;
                change_param_5 = other.change_param_5;
                change_param_value_5 = other.change_param_value_5;
                change_param_percent_5 = other.change_param_percent_5;
                change_param_6 = other.change_param_6;
                change_param_value_6 = other.change_param_value_6;
                change_param_percent_6 = other.change_param_percent_6;
                change_param_7 = other.change_param_7;
                change_param_value_7 = other.change_param_value_7;
                change_param_percent_7 = other.change_param_percent_7;
                change_param_8 = other.change_param_8;
                change_param_value_8 = other.change_param_value_8;
                change_param_percent_8 = other.change_param_percent_8;
                change_param_9 = other.change_param_9;
                change_param_value_9 = other.change_param_value_9;
                change_param_percent_9 = other.change_param_percent_9;
                change_param_10 = other.change_param_10;
                change_param_value_10 = other.change_param_value_10;
                change_param_percent_10 = other.change_param_percent_10;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        change_int_value = CHANGE_INT_VALUE[level];
        change_int_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_int_value", change_int_value);
        change_int_rate = CHANGE_INT_RATE[level];
        change_int_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_int_rate", change_int_rate);
        change_param_value_1 = CHANGE_PARAM_VALUE_1[level];
        change_param_value_1 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_value_1", change_param_value_1);
        change_param_percent_1 = CHANGE_PARAM_PERCENT_1[level];
        change_param_percent_1 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_percent_1", change_param_percent_1);
        change_param_value_2 = CHANGE_PARAM_VALUE_2[level];
        change_param_value_2 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_value_2", change_param_value_2);
        change_param_percent_2 = CHANGE_PARAM_PERCENT_2[level];
        change_param_percent_2 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_percent_2", change_param_percent_2);
        change_param_value_3 = CHANGE_PARAM_VALUE_3[level];
        change_param_value_3 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_value_3", change_param_value_3);
        change_param_percent_3 = CHANGE_PARAM_PERCENT_3[level];
        change_param_percent_3 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_percent_3", change_param_percent_3);
        change_param_value_4 = CHANGE_PARAM_VALUE_4[level];
        change_param_value_4 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_value_4", change_param_value_4);
        change_param_percent_4 = CHANGE_PARAM_PERCENT_4[level];
        change_param_percent_4 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_percent_4", change_param_percent_4);
        change_param_value_5 = CHANGE_PARAM_VALUE_5[level];
        change_param_value_5 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_value_5", change_param_value_5);
        change_param_percent_5 = CHANGE_PARAM_PERCENT_5[level];
        change_param_percent_5 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_percent_5", change_param_percent_5);
        change_param_value_6 = CHANGE_PARAM_VALUE_6[level];
        change_param_value_6 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_value_6", change_param_value_6);
        change_param_percent_6 = CHANGE_PARAM_PERCENT_6[level];
        change_param_percent_6 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_percent_6", change_param_percent_6);
        change_param_value_7 = CHANGE_PARAM_VALUE_7[level];
        change_param_value_7 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_value_7", change_param_value_7);
        change_param_percent_7 = CHANGE_PARAM_PERCENT_7[level];
        change_param_percent_7 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_percent_7", change_param_percent_7);
        change_param_value_8 = CHANGE_PARAM_VALUE_8[level];
        change_param_value_8 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_value_8", change_param_value_8);
        change_param_percent_8 = CHANGE_PARAM_PERCENT_8[level];
        change_param_percent_8 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_percent_8", change_param_percent_8);
        change_param_value_9 = CHANGE_PARAM_VALUE_9[level];
        change_param_value_9 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_value_9", change_param_value_9);
        change_param_percent_9 = CHANGE_PARAM_PERCENT_9[level];
        change_param_percent_9 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_percent_9", change_param_percent_9);
        change_param_value_10 = CHANGE_PARAM_VALUE_10[level];
        change_param_value_10 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_value_10", change_param_value_10);
        change_param_percent_10 = CHANGE_PARAM_PERCENT_10[level];
        change_param_percent_10 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 577, "change_param_percent_10", change_param_percent_10);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.intellect *= 1.0f + multiple * change_int_rate / 100.0f;
        pc.intellect += multiple * change_int_value;
    }

    public void getEnhanceParams(ParamEnhanceSet enhanceSet) {
        switch (level) {
        case 1:
            enhanceSet.add(ParamEnhanceSet.TYPE_BUFF_OWNER, 11, "mp_shield_price", change_param_value_2, change_param_percent_2 / 100.0f);
            break;
        case 2:
            enhanceSet.add(ParamEnhanceSet.TYPE_BUFF_OWNER, 11, "mp_shield_price", change_param_value_2, change_param_percent_2 / 100.0f);
            break;
        case 3:
            enhanceSet.add(ParamEnhanceSet.TYPE_BUFF_OWNER, 11, "mp_shield_price", change_param_value_2, change_param_percent_2 / 100.0f);
            break;
        case 4:
            enhanceSet.add(ParamEnhanceSet.TYPE_BUFF_OWNER, 11, "mp_shield_price", change_param_value_2, change_param_percent_2 / 100.0f);
            break;
        case 5:
            enhanceSet.add(ParamEnhanceSet.TYPE_BUFF_OWNER, 11, "mp_shield_price", change_param_value_2, change_param_percent_2 / 100.0f);
            break;
        }
    }

    public void removeEnhanceParams(ParamEnhanceSet enhanceSet) {
        switch (level) {
        case 1:
            enhanceSet.remove(ParamEnhanceSet.TYPE_BUFF_OWNER, 11, "mp_shield_price", change_param_value_2, change_param_percent_2 / 100.0f);
            break;
        case 2:
            enhanceSet.remove(ParamEnhanceSet.TYPE_BUFF_OWNER, 11, "mp_shield_price", change_param_value_2, change_param_percent_2 / 100.0f);
            break;
        case 3:
            enhanceSet.remove(ParamEnhanceSet.TYPE_BUFF_OWNER, 11, "mp_shield_price", change_param_value_2, change_param_percent_2 / 100.0f);
            break;
        case 4:
            enhanceSet.remove(ParamEnhanceSet.TYPE_BUFF_OWNER, 11, "mp_shield_price", change_param_value_2, change_param_percent_2 / 100.0f);
            break;
        case 5:
            enhanceSet.remove(ParamEnhanceSet.TYPE_BUFF_OWNER, 11, "mp_shield_price", change_param_value_2, change_param_percent_2 / 100.0f);
            break;
        }
    }

}
