package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_033 implements Buff, SkillBuff, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1, -1, -1, -1, -1
    };
    public static String[] VAR_NAME_1 = {
        "", "霜傲昆仑减速概率", "霜傲昆仑减速概率", "霜傲昆仑减速概率", "霜傲昆仑减速概率", "霜傲昆仑减速概率"
    };
    public static float[] VAR_VALUE_1 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] VAR_NAME_2 = {
        "", "霜傲昆仑减速级别", "霜傲昆仑减速级别", "霜傲昆仑减速级别", "霜傲昆仑减速级别", "霜傲昆仑减速级别"
    };
    public static float[] VAR_VALUE_2 = {
        0.0f, 3.0f, 6.0f, 9.0f, 12.0f, 15.0f
    };
    public static String[] VAR_NAME_3 = {
        "", "霜傲昆仑减速时间", "霜傲昆仑减速时间", "霜傲昆仑减速时间", "霜傲昆仑减速时间", "霜傲昆仑减速时间"
    };
    public static float[] VAR_VALUE_3 = {
        0.0f, 10.0f, 20.0f, 30.0f, 40.0f, 50.0f
    };
    public static int[] CHANGE_THREAT_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] CHANGE_THREAT_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    Skill skill;
    int instanceID;
    int realWeight;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    String var_name_1;
    float var_value_1;
    String var_name_2;
    float var_value_2;
    String var_name_3;
    float var_value_3;
    int change_threat_value;
    float change_threat_percent;

    public AutoGeneratedBuff_033(Skill skl, int lvl) {
        int dmg = 0;
        skill = skl;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        var_name_1 = VAR_NAME_1[level];
        var_value_1 = VAR_VALUE_1[level];
        var_name_2 = VAR_NAME_2[level];
        var_value_2 = VAR_VALUE_2[level];
        var_name_3 = VAR_NAME_3[level];
        var_value_3 = VAR_VALUE_3[level];
        change_threat_value = CHANGE_THREAT_VALUE[level];
        change_threat_percent = CHANGE_THREAT_PERCENT[level];
    }

    public int getId() {
        return skill.getId();
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "霜傲昆仑";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("激活寒冰利刃和牧野流星技能的冰冻减速效果，并提升减速比率{0}，持续时间延长{1}", CommonUtil.formatPercent(var_value_2 * multiple), CommonUtil.formatPercent(var_value_3 * multiple));
    }

    public Skill getSkill() {
        return skill;
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public int getMergeStrategy() {
        return 2;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public float getchange_dembuff_rate() {
         return 0;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_033) {
            AutoGeneratedBuff_033 other = (AutoGeneratedBuff_033)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                var_name_1 = other.var_name_1;
                var_value_1 = other.var_value_1;
                var_name_2 = other.var_name_2;
                var_value_2 = other.var_value_2;
                var_name_3 = other.var_name_3;
                var_value_3 = other.var_value_3;
                change_threat_value = other.change_threat_value;
                change_threat_percent = other.change_threat_percent;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        var_value_1 = VAR_VALUE_1[level];
        var_value_1 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 33, "var_value_1", var_value_1);
        var_value_2 = VAR_VALUE_2[level];
        var_value_2 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 33, "var_value_2", var_value_2);
        var_value_3 = VAR_VALUE_3[level];
        var_value_3 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 33, "var_value_3", var_value_3);
        change_threat_value = CHANGE_THREAT_VALUE[level];
        change_threat_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 33, "change_threat_value", change_threat_value);
        change_threat_percent = CHANGE_THREAT_PERCENT[level];
        change_threat_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 33, "change_threat_percent", change_threat_percent);
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive) {
            if (var_name_1.length() > 0) {
                context.skillParams.put(var_name_1, new Float(var_value_1));
            }
            if (var_name_2.length() > 0) {
                context.skillParams.put(var_name_2, new Float(var_value_2));
            }
            if (var_name_3.length() > 0) {
                context.skillParams.put(var_name_3, new Float(var_value_3));
            }
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive) {
            context.threatAdd += multiple * change_threat_value;
            context.threatAddRate += multiple * change_threat_percent / 100.0f;
            effectTimes++;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

}
