package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_618 implements Buff, PropertyEnhancer, Updatable {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, 8000
    };
    public static int[] CHANGE_PHYSICAL_HIT_RATE = {
        0, 30
    };
    public static int[] CHANGE_MAGIC_CRIT_RATE = {
        0, 30
    };
    int instanceID;
    int realWeight;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_physical_hit_rate;
    int change_magic_crit_rate;

    public AutoGeneratedBuff_618(int lvl, Unit src, Unit tgt, int dmg) {
        if (src != null) {
            source = src.ref();
        }
        if (tgt != null) {
            owner = tgt.ref();
        }
        instanceID = BuffUtil.getNextID();
        level = lvl;
        endTime = Time.currTime + BuffUtil.enhanceParam(src, tgt, 618, "buffTime", DURATION[level]);
        multiple = 1;
        change_physical_hit_rate = CHANGE_PHYSICAL_HIT_RATE[level];
        change_physical_hit_rate = BuffUtil.enhanceParam(src, tgt, 618, "change_physical_hit_rate", change_physical_hit_rate);
        change_magic_crit_rate = CHANGE_MAGIC_CRIT_RATE[level];
        change_magic_crit_rate = BuffUtil.enhanceParam(src, tgt, 618, "change_magic_crit_rate", change_magic_crit_rate);
    }

    public int getId() {
        return 618;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "冲锋陷阵";
    }

    public String getDesc() {
        return "8秒内物理/法术命中增加30点";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return endTime;
    }

    public boolean isGood() {
        return false;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return 10 | 0x1000000;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public int getMergeStrategy() {
        return 4;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public float getchange_dembuff_rate() {
         return 0;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_618) {
            AutoGeneratedBuff_618 other = (AutoGeneratedBuff_618)buff;
            level = other.level;
            endTime = other.endTime;
            multiple = 1;
            remainSeconds = other.remainSeconds;
            tickInterval = other.tickInterval;
            remainCure = other.remainCure;
            remainDamage = other.remainDamage;
            remainMPCure = other.remainMPCure;
            remainMPDamage = other.remainMPDamage;
            remainAbsorb = other.remainAbsorb;
            effectTimes = 0;
            owner = other.owner;
            source = other.source;
            change_physical_hit_rate = other.change_physical_hit_rate;
            change_magic_crit_rate = other.change_magic_crit_rate;
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
    }

    public boolean update(int diff) {
        if (endTime <= Time.currTime) {
            return true;
        }
        return false;
    }

    public void load(byte[] bytes) {
        ByteBuffer buf = ByteBuffer.wrap(bytes);
        owner = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        source = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        level = buf.getInt();
        endTime = Time.elapseTime(buf.getLong());
        multiple = buf.getInt();
        change_physical_hit_rate = CHANGE_PHYSICAL_HIT_RATE[level];
        change_magic_crit_rate = CHANGE_MAGIC_CRIT_RATE[level];
        remainSeconds = buf.getInt();
        tickInterval = buf.getInt();
        remainCure = buf.getInt();
        remainDamage = buf.getInt();
        remainMPCure = buf.getInt();
        remainMPDamage = buf.getInt();
        remainAbsorb = buf.getInt();
        effectTimes = buf.getInt();
    }

    public byte[] save() {
        ByteBuffer buf = ByteBuffer.allocate(66, false);
        buf.put(owner.type);
        buf.putInt(owner.id);
        buf.putInt(owner.instanceId);
        buf.put(source.type);
        buf.putInt(source.id);
        buf.putInt(source.instanceId);
        buf.putInt(level);
        buf.putLong(Time.currentTimeMillis(endTime));
        buf.putInt(multiple);
        buf.putInt(remainSeconds);
        buf.putInt(tickInterval);
        buf.putInt(remainCure);
        buf.putInt(remainDamage);
        buf.putInt(remainMPCure);
        buf.putInt(remainMPDamage);
        buf.putInt(remainAbsorb);
        buf.putInt(effectTimes);
        return buf.array();
    }

    public boolean update2(int time) {
        endTime += time;
        if (endTime <= Time.currTime) {
            return false;
        }
        return true;
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.hitrating += multiple * change_physical_hit_rate;
        pc.spellhitrating += multiple * change_magic_crit_rate;
    }

}
