package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_569 implements Buff, SkillBuff, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1
    };
    public static int[] IGNORE_IGNORE_MAGIC_ARMOR_VALUE = {
        0, 0
    };
    public static float[] IGNORE_IGNORE_MAGIC_ARMOR_PERCENT = {
        0.0f, 36.0f
    };
    public static int[] IGNORE_IGNORE_ARMOR_VALUE = {
        0, 0
    };
    public static float[] IGNORE_IGNORE_ARMOR_PERCENT = {
        0.0f, 36.0f
    };
    Skill skill;
    int instanceID;
    int realWeight;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int ignore_ignore_magic_armor_value;
    float ignore_ignore_magic_armor_percent;
    int ignore_ignore_armor_value;
    float ignore_ignore_armor_percent;

    public AutoGeneratedBuff_569(Skill skl, int lvl) {
        int dmg = 0;
        skill = skl;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        ignore_ignore_magic_armor_value = IGNORE_IGNORE_MAGIC_ARMOR_VALUE[level];
        ignore_ignore_magic_armor_percent = IGNORE_IGNORE_MAGIC_ARMOR_PERCENT[level];
        ignore_ignore_armor_value = IGNORE_IGNORE_ARMOR_VALUE[level];
        ignore_ignore_armor_percent = IGNORE_IGNORE_ARMOR_PERCENT[level];
    }

    public int getId() {
        return skill.getId();
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "3级乾坤挪移(废弃)";
    }

    public String getDesc() {
        return "当被无视护甲/法防时，此技能将为你保留36%的以上2种属性。";
    }

    public Skill getSkill() {
        return skill;
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public int getMergeStrategy() {
        return 2;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public float getchange_dembuff_rate() {
         return 0;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_569) {
            AutoGeneratedBuff_569 other = (AutoGeneratedBuff_569)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                ignore_ignore_magic_armor_value = other.ignore_ignore_magic_armor_value;
                ignore_ignore_magic_armor_percent = other.ignore_ignore_magic_armor_percent;
                ignore_ignore_armor_value = other.ignore_ignore_armor_value;
                ignore_ignore_armor_percent = other.ignore_ignore_armor_percent;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        ignore_ignore_magic_armor_value = IGNORE_IGNORE_MAGIC_ARMOR_VALUE[level];
        ignore_ignore_magic_armor_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 569, "ignore_ignore_magic_armor_value", ignore_ignore_magic_armor_value);
        ignore_ignore_magic_armor_percent = IGNORE_IGNORE_MAGIC_ARMOR_PERCENT[level];
        ignore_ignore_magic_armor_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 569, "ignore_ignore_magic_armor_percent", ignore_ignore_magic_armor_percent);
        ignore_ignore_armor_value = IGNORE_IGNORE_ARMOR_VALUE[level];
        ignore_ignore_armor_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 569, "ignore_ignore_armor_value", ignore_ignore_armor_value);
        ignore_ignore_armor_percent = IGNORE_IGNORE_ARMOR_PERCENT[level];
        ignore_ignore_armor_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 569, "ignore_ignore_armor_percent", ignore_ignore_armor_percent);
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (context.damageType == CombatContext.DAMAGE_MAGIC && context.armorRate<0) {
            context.armor += multiple * ignore_ignore_magic_armor_value;
            context.armorRate *= (multiple * (1-ignore_ignore_magic_armor_percent / 100.0f));
            context.armorRate = context.armorRate>0 ? 0 : context.armorRate;
            effectTimes++;
        }
        if (context.damageType == CombatContext.DAMAGE_PHYSICAL && context.armorRate<0) {
            context.armor += multiple * ignore_ignore_armor_value;
            context.armorRate *= (multiple * (1-ignore_ignore_armor_percent / 100.0f));
            context.armorRate = context.armorRate>0 ? 0 : context.armorRate;
            effectTimes++;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

}
