package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_604 implements Buff, ParamEnhancer, PropertyEnhancer, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1
    };
    public static float[] DEC_MP_RATE = {
        0.0f, 16.0f
    };
    public static int[] DEC_MP_VALUE = {
        0, 0
    };
    public static float[] DEC_MP_PERCENT_OF_MAX = {
        0.0f, 0.0f
    };
    public static float[] DEC_MP_PERCENT_OF_DAMAGE = {
        0.0f, 35.0f
    };
    public static float[] REPEAT_RATE = {
        0.0f, 5.0f
    };
    public static float[] ADD_HP_RATE = {
        0.0f, 16.0f
    };
    public static int[] ADD_HP_VALUE = {
        0, 0
    };
    public static float[] ADD_HP_PERCENT_OF_MAX = {
        0.0f, 0.0f
    };
    public static float[] ADD_HP_PERCENT_OF_DAMAGE = {
        0.0f, 35.0f
    };
    public static float[] ADD_BUFF_RATE = {
        0.0f, 15.0f
    };
    public static String[] ADD_BUFF_RATE_VAR = {
        "", ""
    };
    public static int[] ADD_BUFF_ID = {
        0, 590
    };
    public static int[] ADD_BUFF_LEVEL = {
        0, 2
    };
    public static float[] ADD_BUFF_HITED_RATE = {
        0.0f, 15.0f
    };
    public static String[] ADD_BUFF_HITED_RATE_VAR = {
        "", ""
    };
    public static int[] ADD_BUFF_HITED_ID = {
        0, 590
    };
    public static int[] ADD_BUFF_HITED_LEVEL = {
        0, 2
    };
    public static String[] CHANGE_PARAM_1 = {
        "", "0,62,8"
    };
    public static float[] CHANGE_PARAM_VALUE_1 = {
        0.0f, 30.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_1 = {
        0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_2 = {
        "", "1,6,6"
    };
    public static float[] CHANGE_PARAM_VALUE_2 = {
        0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_2 = {
        0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_3 = {
        "", "1,42,7"
    };
    public static float[] CHANGE_PARAM_VALUE_3 = {
        0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_3 = {
        0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_4 = {
        "", "1,46,7"
    };
    public static float[] CHANGE_PARAM_VALUE_4 = {
        0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_4 = {
        0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_5 = {
        "", "1,140,2"
    };
    public static float[] CHANGE_PARAM_VALUE_5 = {
        0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_5 = {
        0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_6 = {
        "", "1,70,4"
    };
    public static float[] CHANGE_PARAM_VALUE_6 = {
        0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_6 = {
        0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_7 = {
        "", "2,51,3"
    };
    public static float[] CHANGE_PARAM_VALUE_7 = {
        0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_7 = {
        0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_8 = {
        "", "2,483,3"
    };
    public static float[] CHANGE_PARAM_VALUE_8 = {
        0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_8 = {
        0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_9 = {
        "", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_9 = {
        0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_9 = {
        0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_10 = {
        "", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_10 = {
        0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_10 = {
        0.0f, 0.0f
    };
    public static int[] CHANGE_SPCIALPARAM_1 = {
        0, 1
    };
    public static float[] CHANGE_SPCIALPARAM_PERCENT_1 = {
        0.0f, 50.0f
    };
    public static int[] CHANGE_SPCIALPARAM_2 = {
        0, 2
    };
    public static float[] CHANGE_SPCIALPARAM_PERCENT_2 = {
        0.0f, 50.0f
    };
    public static int[] CHANGE_SPCIALPARAM_3 = {
        0, 3
    };
    public static float[] CHANGE_SPCIALPARAM_PERCENT_3 = {
        0.0f, 50.0f
    };
    public static int[] CHANGE_SPCIALPARAM_4 = {
        0, 4
    };
    public static float[] CHANGE_SPCIALPARAM_PERCENT_4 = {
        0.0f, 50.0f
    };
    int instanceID;
    int realWeight;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    float dec_mp_rate;
    int dec_mp_value;
    float dec_mp_percent_of_max;
    float dec_mp_percent_of_damage;
    float repeat_rate;
    float add_hp_rate;
    int add_hp_value;
    float add_hp_percent_of_max;
    float add_hp_percent_of_damage;
    float add_buff_rate;
    String add_buff_rate_var;
    int add_buff_id;
    int add_buff_level;
    float add_buff_hited_rate;
    String add_buff_hited_rate_var;
    int add_buff_hited_id;
    int add_buff_hited_level;
    String change_param_1;
    float change_param_value_1;
    float change_param_percent_1;
    String change_param_2;
    float change_param_value_2;
    float change_param_percent_2;
    String change_param_3;
    float change_param_value_3;
    float change_param_percent_3;
    String change_param_4;
    float change_param_value_4;
    float change_param_percent_4;
    String change_param_5;
    float change_param_value_5;
    float change_param_percent_5;
    String change_param_6;
    float change_param_value_6;
    float change_param_percent_6;
    String change_param_7;
    float change_param_value_7;
    float change_param_percent_7;
    String change_param_8;
    float change_param_value_8;
    float change_param_percent_8;
    String change_param_9;
    float change_param_value_9;
    float change_param_percent_9;
    String change_param_10;
    float change_param_value_10;
    float change_param_percent_10;
    int change_spcialparam_1;
    float change_spcialparam_percent_1;
    int change_spcialparam_2;
    float change_spcialparam_percent_2;
    int change_spcialparam_3;
    float change_spcialparam_percent_3;
    int change_spcialparam_4;
    float change_spcialparam_percent_4;


    public AutoGeneratedBuff_604(int lvl) {
        int dmg = 0;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        dec_mp_rate = DEC_MP_RATE[level];
        dec_mp_value = DEC_MP_VALUE[level];
        dec_mp_percent_of_max = DEC_MP_PERCENT_OF_MAX[level];
        dec_mp_percent_of_damage = DEC_MP_PERCENT_OF_DAMAGE[level];
        repeat_rate = REPEAT_RATE[level];
        add_hp_rate = ADD_HP_RATE[level];
        add_hp_value = ADD_HP_VALUE[level];
        add_hp_percent_of_max = ADD_HP_PERCENT_OF_MAX[level];
        add_hp_percent_of_damage = ADD_HP_PERCENT_OF_DAMAGE[level];
        add_buff_rate = ADD_BUFF_RATE[level];
        add_buff_rate_var = ADD_BUFF_RATE_VAR[level];
        add_buff_id = ADD_BUFF_ID[level];
        add_buff_level = ADD_BUFF_LEVEL[level];
        add_buff_hited_rate = ADD_BUFF_HITED_RATE[level];
        add_buff_hited_rate_var = ADD_BUFF_HITED_RATE_VAR[level];
        add_buff_hited_id = ADD_BUFF_HITED_ID[level];
        add_buff_hited_level = ADD_BUFF_HITED_LEVEL[level];
        change_param_1 = CHANGE_PARAM_1[level];
        change_param_value_1 = CHANGE_PARAM_VALUE_1[level];
        change_param_percent_1 = CHANGE_PARAM_PERCENT_1[level];
        change_param_2 = CHANGE_PARAM_2[level];
        change_param_value_2 = CHANGE_PARAM_VALUE_2[level];
        change_param_percent_2 = CHANGE_PARAM_PERCENT_2[level];
        change_param_3 = CHANGE_PARAM_3[level];
        change_param_value_3 = CHANGE_PARAM_VALUE_3[level];
        change_param_percent_3 = CHANGE_PARAM_PERCENT_3[level];
        change_param_4 = CHANGE_PARAM_4[level];
        change_param_value_4 = CHANGE_PARAM_VALUE_4[level];
        change_param_percent_4 = CHANGE_PARAM_PERCENT_4[level];
        change_param_5 = CHANGE_PARAM_5[level];
        change_param_value_5 = CHANGE_PARAM_VALUE_5[level];
        change_param_percent_5 = CHANGE_PARAM_PERCENT_5[level];
        change_param_6 = CHANGE_PARAM_6[level];
        change_param_value_6 = CHANGE_PARAM_VALUE_6[level];
        change_param_percent_6 = CHANGE_PARAM_PERCENT_6[level];
        change_param_7 = CHANGE_PARAM_7[level];
        change_param_value_7 = CHANGE_PARAM_VALUE_7[level];
        change_param_percent_7 = CHANGE_PARAM_PERCENT_7[level];
        change_param_8 = CHANGE_PARAM_8[level];
        change_param_value_8 = CHANGE_PARAM_VALUE_8[level];
        change_param_percent_8 = CHANGE_PARAM_PERCENT_8[level];
        change_param_9 = CHANGE_PARAM_9[level];
        change_param_value_9 = CHANGE_PARAM_VALUE_9[level];
        change_param_percent_9 = CHANGE_PARAM_PERCENT_9[level];
        change_param_10 = CHANGE_PARAM_10[level];
        change_param_value_10 = CHANGE_PARAM_VALUE_10[level];
        change_param_percent_10 = CHANGE_PARAM_PERCENT_10[level];
        change_spcialparam_1 = CHANGE_SPCIALPARAM_1[level];
        change_spcialparam_percent_1 = CHANGE_SPCIALPARAM_PERCENT_1[level];
        change_spcialparam_2 = CHANGE_SPCIALPARAM_2[level];
        change_spcialparam_percent_2 = CHANGE_SPCIALPARAM_PERCENT_2[level];
        change_spcialparam_3 = CHANGE_SPCIALPARAM_3[level];
        change_spcialparam_percent_3 = CHANGE_SPCIALPARAM_PERCENT_3[level];
        change_spcialparam_4 = CHANGE_SPCIALPARAM_4[level];
        change_spcialparam_percent_4 = CHANGE_SPCIALPARAM_PERCENT_4[level];
    }

    public int getId() {
        return 604;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "龙啸九天（方）";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("命中目标后有{0}几率燃烧目标伤害量{1}的气力/精力；有{2}几率吸取对目标伤害的{3}作为生命恢复；攻击有一定几率触发连击；受到来自玩家的沉默，恐惧、麻痹、定身的持续时间缩短50%；冰封诅咒30%几率驱散目标的一个有益状态。命中和被命中都有一定几率触发天怒效果", CommonUtil.formatPercent(dec_mp_rate * multiple), CommonUtil.formatPercent(dec_mp_percent_of_damage * multiple), CommonUtil.formatPercent(add_hp_rate * multiple), CommonUtil.formatPercent(add_hp_percent_of_damage * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public int getMergeStrategy() {
        return 2;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public float getchange_dembuff_rate() {
         return 0;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_604) {
            AutoGeneratedBuff_604 other = (AutoGeneratedBuff_604)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                dec_mp_rate = other.dec_mp_rate;
                dec_mp_value = other.dec_mp_value;
                dec_mp_percent_of_max = other.dec_mp_percent_of_max;
                dec_mp_percent_of_damage = other.dec_mp_percent_of_damage;
                repeat_rate = other.repeat_rate;
                add_hp_rate = other.add_hp_rate;
                add_hp_value = other.add_hp_value;
                add_hp_percent_of_max = other.add_hp_percent_of_max;
                add_hp_percent_of_damage = other.add_hp_percent_of_damage;
                add_buff_rate = other.add_buff_rate;
                add_buff_rate_var = other.add_buff_rate_var;
                add_buff_id = other.add_buff_id;
                add_buff_level = other.add_buff_level;
                add_buff_hited_rate = other.add_buff_hited_rate;
                add_buff_hited_rate_var = other.add_buff_hited_rate_var;
                add_buff_hited_id = other.add_buff_hited_id;
                add_buff_hited_level = other.add_buff_hited_level;
                change_param_1 = other.change_param_1;
                change_param_value_1 = other.change_param_value_1;
                change_param_percent_1 = other.change_param_percent_1;
                change_param_2 = other.change_param_2;
                change_param_value_2 = other.change_param_value_2;
                change_param_percent_2 = other.change_param_percent_2;
                change_param_3 = other.change_param_3;
                change_param_value_3 = other.change_param_value_3;
                change_param_percent_3 = other.change_param_percent_3;
                change_param_4 = other.change_param_4;
                change_param_value_4 = other.change_param_value_4;
                change_param_percent_4 = other.change_param_percent_4;
                change_param_5 = other.change_param_5;
                change_param_value_5 = other.change_param_value_5;
                change_param_percent_5 = other.change_param_percent_5;
                change_param_6 = other.change_param_6;
                change_param_value_6 = other.change_param_value_6;
                change_param_percent_6 = other.change_param_percent_6;
                change_param_7 = other.change_param_7;
                change_param_value_7 = other.change_param_value_7;
                change_param_percent_7 = other.change_param_percent_7;
                change_param_8 = other.change_param_8;
                change_param_value_8 = other.change_param_value_8;
                change_param_percent_8 = other.change_param_percent_8;
                change_param_9 = other.change_param_9;
                change_param_value_9 = other.change_param_value_9;
                change_param_percent_9 = other.change_param_percent_9;
                change_param_10 = other.change_param_10;
                change_param_value_10 = other.change_param_value_10;
                change_param_percent_10 = other.change_param_percent_10;
                change_spcialparam_1 = other.change_spcialparam_1;
                change_spcialparam_percent_1 = other.change_spcialparam_percent_1;
                change_spcialparam_2 = other.change_spcialparam_2;
                change_spcialparam_percent_2 = other.change_spcialparam_percent_2;
                change_spcialparam_3 = other.change_spcialparam_3;
                change_spcialparam_percent_3 = other.change_spcialparam_percent_3;
                change_spcialparam_4 = other.change_spcialparam_4;
                change_spcialparam_percent_4 = other.change_spcialparam_percent_4;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        dec_mp_rate = DEC_MP_RATE[level];
        dec_mp_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "dec_mp_rate", dec_mp_rate);
        dec_mp_value = DEC_MP_VALUE[level];
        dec_mp_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "dec_mp_value", dec_mp_value);
        dec_mp_percent_of_max = DEC_MP_PERCENT_OF_MAX[level];
        dec_mp_percent_of_max = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "dec_mp_percent_of_max", dec_mp_percent_of_max);
        dec_mp_percent_of_damage = DEC_MP_PERCENT_OF_DAMAGE[level];
        dec_mp_percent_of_damage = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "dec_mp_percent_of_damage", dec_mp_percent_of_damage);
        repeat_rate = REPEAT_RATE[level];
        repeat_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "repeat_rate", repeat_rate);
        add_hp_rate = ADD_HP_RATE[level];
        add_hp_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "add_hp_rate", add_hp_rate);
        add_hp_value = ADD_HP_VALUE[level];
        add_hp_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "add_hp_value", add_hp_value);
        add_hp_percent_of_max = ADD_HP_PERCENT_OF_MAX[level];
        add_hp_percent_of_max = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "add_hp_percent_of_max", add_hp_percent_of_max);
        add_hp_percent_of_damage = ADD_HP_PERCENT_OF_DAMAGE[level];
        add_hp_percent_of_damage = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "add_hp_percent_of_damage", add_hp_percent_of_damage);
        add_buff_rate = ADD_BUFF_RATE[level];
        add_buff_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "add_buff_rate", add_buff_rate);
        add_buff_level = ADD_BUFF_LEVEL[level];
        add_buff_level = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "add_buff_level", add_buff_level);
        add_buff_hited_rate = ADD_BUFF_HITED_RATE[level];
        add_buff_hited_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "add_buff_hited_rate", add_buff_hited_rate);
        add_buff_hited_level = ADD_BUFF_HITED_LEVEL[level];
        add_buff_hited_level = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "add_buff_hited_level", add_buff_hited_level);
        change_param_value_1 = CHANGE_PARAM_VALUE_1[level];
        change_param_value_1 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_value_1", change_param_value_1);
        change_param_percent_1 = CHANGE_PARAM_PERCENT_1[level];
        change_param_percent_1 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_percent_1", change_param_percent_1);
        change_param_value_2 = CHANGE_PARAM_VALUE_2[level];
        change_param_value_2 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_value_2", change_param_value_2);
        change_param_percent_2 = CHANGE_PARAM_PERCENT_2[level];
        change_param_percent_2 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_percent_2", change_param_percent_2);
        change_param_value_3 = CHANGE_PARAM_VALUE_3[level];
        change_param_value_3 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_value_3", change_param_value_3);
        change_param_percent_3 = CHANGE_PARAM_PERCENT_3[level];
        change_param_percent_3 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_percent_3", change_param_percent_3);
        change_param_value_4 = CHANGE_PARAM_VALUE_4[level];
        change_param_value_4 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_value_4", change_param_value_4);
        change_param_percent_4 = CHANGE_PARAM_PERCENT_4[level];
        change_param_percent_4 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_percent_4", change_param_percent_4);
        change_param_value_5 = CHANGE_PARAM_VALUE_5[level];
        change_param_value_5 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_value_5", change_param_value_5);
        change_param_percent_5 = CHANGE_PARAM_PERCENT_5[level];
        change_param_percent_5 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_percent_5", change_param_percent_5);
        change_param_value_6 = CHANGE_PARAM_VALUE_6[level];
        change_param_value_6 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_value_6", change_param_value_6);
        change_param_percent_6 = CHANGE_PARAM_PERCENT_6[level];
        change_param_percent_6 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_percent_6", change_param_percent_6);
        change_param_value_7 = CHANGE_PARAM_VALUE_7[level];
        change_param_value_7 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_value_7", change_param_value_7);
        change_param_percent_7 = CHANGE_PARAM_PERCENT_7[level];
        change_param_percent_7 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_percent_7", change_param_percent_7);
        change_param_value_8 = CHANGE_PARAM_VALUE_8[level];
        change_param_value_8 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_value_8", change_param_value_8);
        change_param_percent_8 = CHANGE_PARAM_PERCENT_8[level];
        change_param_percent_8 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_percent_8", change_param_percent_8);
        change_param_value_9 = CHANGE_PARAM_VALUE_9[level];
        change_param_value_9 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_value_9", change_param_value_9);
        change_param_percent_9 = CHANGE_PARAM_PERCENT_9[level];
        change_param_percent_9 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_percent_9", change_param_percent_9);
        change_param_value_10 = CHANGE_PARAM_VALUE_10[level];
        change_param_value_10 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_value_10", change_param_value_10);
        change_param_percent_10 = CHANGE_PARAM_PERCENT_10[level];
        change_param_percent_10 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_param_percent_10", change_param_percent_10);
        change_spcialparam_1 = CHANGE_SPCIALPARAM_1[level];
        change_spcialparam_1 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_spcialparam_1", change_spcialparam_1);
        change_spcialparam_percent_1 = CHANGE_SPCIALPARAM_PERCENT_1[level];
        change_spcialparam_percent_1 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_spcialparam_percent_1", change_spcialparam_percent_1);
        change_spcialparam_2 = CHANGE_SPCIALPARAM_2[level];
        change_spcialparam_2 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_spcialparam_2", change_spcialparam_2);
        change_spcialparam_percent_2 = CHANGE_SPCIALPARAM_PERCENT_2[level];
        change_spcialparam_percent_2 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_spcialparam_percent_2", change_spcialparam_percent_2);
        change_spcialparam_3 = CHANGE_SPCIALPARAM_3[level];
        change_spcialparam_3 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_spcialparam_3", change_spcialparam_3);
        change_spcialparam_percent_3 = CHANGE_SPCIALPARAM_PERCENT_3[level];
        change_spcialparam_percent_3 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_spcialparam_percent_3", change_spcialparam_percent_3);
        change_spcialparam_4 = CHANGE_SPCIALPARAM_4[level];
        change_spcialparam_4 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_spcialparam_4", change_spcialparam_4);
        change_spcialparam_percent_4 = CHANGE_SPCIALPARAM_PERCENT_4[level];
        change_spcialparam_percent_4 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 604, "change_spcialparam_percent_4", change_spcialparam_percent_4);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        switch (level) {
        case 1:
        if(pc.unit instanceof Player){
            Player p = (Player)pc.unit;
            if(p!=null){
               p.timeRatio[change_spcialparam_1-1] *= (1-change_spcialparam_percent_1/100.0f);
            }
        }
        if(pc.unit instanceof Player){
            Player p = (Player)pc.unit;
            if(p!=null){
               p.timeRatio[change_spcialparam_2-1] *= (1-change_spcialparam_percent_2/100.0f);
            }
        }
        if(pc.unit instanceof Player){
            Player p = (Player)pc.unit;
            if(p!=null){
               p.timeRatio[change_spcialparam_3-1] *= (1-change_spcialparam_percent_3/100.0f);
            }
        }
        if(pc.unit instanceof Player){
            Player p = (Player)pc.unit;
            if(p!=null){
               p.timeRatio[change_spcialparam_4-1] *= (1-change_spcialparam_percent_4/100.0f);
            }
        }
            break;
        }
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive && context.hited() && context.isDamage()) {
            int rate = (int)(multiple * 100 * dec_mp_rate);
            if (CommonUtil.hit(RND, rate, 10000)) {
                int decmp = dec_mp_value;
                decmp += context.target.maxmp * dec_mp_percent_of_max / 100.0f;
                decmp += context.damage * dec_mp_percent_of_damage / 100.0f;
                context.activeSkills.add(new FixedDecMPSkill(decmp));
                effectTimes++;
            }
        }
        if (isActive && context.hited() && context.isDamage()) {
            if (CommonUtil.hit(RND, (int)(multiple * 100 * repeat_rate), 10000)) {
                context.activeSkills.add(context.skill);
                effectTimes++;
            }
        }
        if (isActive && context.hited() && context.isDamage() && (context.target instanceof Player || context.target instanceof Creature)) {
            int rate = (int)(multiple * 100 * add_hp_rate);
            if (CommonUtil.hit(RND, rate, 10000)) {
                int cure = add_hp_value;
                cure += context.source.maxhp * add_hp_percent_of_max / 100.0f;
                cure += context.damage * add_hp_percent_of_damage / 100.0f;
                context.activeSkills.add(new FixedHealSkill(cure));
                effectTimes++;
            }
        }
        if (isActive && context.hited() && context.isAttack()) {
            boolean hit = false;
            if (add_buff_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(multiple * 100 * add_buff_rate), 10000);
            } else {
                Float vo = context.skillParams.get(add_buff_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(multiple * 100 * (vo.floatValue() + add_buff_rate)), 10000);
                }
            }
            if (hit) {
                context.source.buffs.addBuff(BuffUtil.createBuff(add_buff_id, add_buff_level, context.source, context.source, context.damage));
                effectTimes++;
            }
        }
        if (!isActive && context.hited() && context.isAttack()) {
            boolean hit = false;
            if (add_buff_hited_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(multiple * 100 * add_buff_hited_rate), 10000);
            } else {
                Float vo = context.skillParams.get(add_buff_hited_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(multiple * 100 * (vo.floatValue() + add_buff_hited_rate)), 10000);
                }
            }
            if (hit) {
                context.target.buffs.addBuff(BuffUtil.createBuff(add_buff_hited_id, add_buff_hited_level, context.target, context.target, context.damage));
                effectTimes++;
            }
        }
    }

    public void getEnhanceParams(ParamEnhanceSet enhanceSet) {
        switch (level) {
        case 1:
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 62, "dispel_buff_rate", change_param_value_1, change_param_percent_1 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_PASSIVE, 6, "fear_time", change_param_value_2, change_param_percent_2 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_PASSIVE, 42, "paralyse_time", change_param_value_3, change_param_percent_3 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_PASSIVE, 46, "stay_time", change_param_value_4, change_param_percent_4 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_PASSIVE, 140, "dumb_time", change_param_value_5, change_param_percent_5 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_PASSIVE, 70, "fear_time", change_param_value_6, change_param_percent_6 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_BUFF_OWNER, 51, "dumb_time", change_param_value_7, change_param_percent_7 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_BUFF_OWNER, 483, "paralyse_time", change_param_value_8, change_param_percent_8 / 100.0f);
            break;
        }
    }

    public void removeEnhanceParams(ParamEnhanceSet enhanceSet) {
        switch (level) {
        case 1:
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 62, "dispel_buff_rate", change_param_value_1, change_param_percent_1 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_PASSIVE, 6, "fear_time", change_param_value_2, change_param_percent_2 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_PASSIVE, 42, "paralyse_time", change_param_value_3, change_param_percent_3 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_PASSIVE, 46, "stay_time", change_param_value_4, change_param_percent_4 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_PASSIVE, 140, "dumb_time", change_param_value_5, change_param_percent_5 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_PASSIVE, 70, "fear_time", change_param_value_6, change_param_percent_6 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_BUFF_OWNER, 51, "dumb_time", change_param_value_7, change_param_percent_7 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_BUFF_OWNER, 483, "paralyse_time", change_param_value_8, change_param_percent_8 / 100.0f);
            break;
        }
    }

}
