package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_506 implements Buff, PropertyEnhancer {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1
    };
    public static int[] CHANGE_STA_VALUE = {
        0, 15
    };
    public static float[] CHANGE_STA_RATE = {
        0.0f, 0.0f
    };
    public static int[] CHANGE_AGI_VALUE = {
        0, 15
    };
    public static float[] CHANGE_AGI_RATE = {
        0.0f, 0.0f
    };
    public static int[] CHANGE_STR_VALUE = {
        0, 15
    };
    public static float[] CHANGE_STR_RATE = {
        0.0f, 0.0f
    };
    public static int[] CHANGE_INT_VALUE = {
        0, 15
    };
    public static float[] CHANGE_INT_RATE = {
        0.0f, 0.0f
    };
    int instanceID;
    int realWeight;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_sta_value;
    float change_sta_rate;
    int change_agi_value;
    float change_agi_rate;
    int change_str_value;
    float change_str_rate;
    int change_int_value;
    float change_int_rate;


    public AutoGeneratedBuff_506(int lvl) {
        int dmg = 0;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        change_sta_value = CHANGE_STA_VALUE[level];
        change_sta_rate = CHANGE_STA_RATE[level];
        change_agi_value = CHANGE_AGI_VALUE[level];
        change_agi_rate = CHANGE_AGI_RATE[level];
        change_str_value = CHANGE_STR_VALUE[level];
        change_str_rate = CHANGE_STR_RATE[level];
        change_int_value = CHANGE_INT_VALUE[level];
        change_int_rate = CHANGE_INT_RATE[level];
    }

    public int getId() {
        return 506;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "小糖糖";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("佩戴可提高全属性{0}点。", CommonUtil.formatValue(change_sta_value * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public int getMergeStrategy() {
        return 2;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public float getchange_dembuff_rate() {
         return 0;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_506) {
            AutoGeneratedBuff_506 other = (AutoGeneratedBuff_506)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                change_sta_value = other.change_sta_value;
                change_sta_rate = other.change_sta_rate;
                change_agi_value = other.change_agi_value;
                change_agi_rate = other.change_agi_rate;
                change_str_value = other.change_str_value;
                change_str_rate = other.change_str_rate;
                change_int_value = other.change_int_value;
                change_int_rate = other.change_int_rate;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        change_sta_value = CHANGE_STA_VALUE[level];
        change_sta_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 506, "change_sta_value", change_sta_value);
        change_sta_rate = CHANGE_STA_RATE[level];
        change_sta_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 506, "change_sta_rate", change_sta_rate);
        change_agi_value = CHANGE_AGI_VALUE[level];
        change_agi_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 506, "change_agi_value", change_agi_value);
        change_agi_rate = CHANGE_AGI_RATE[level];
        change_agi_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 506, "change_agi_rate", change_agi_rate);
        change_str_value = CHANGE_STR_VALUE[level];
        change_str_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 506, "change_str_value", change_str_value);
        change_str_rate = CHANGE_STR_RATE[level];
        change_str_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 506, "change_str_rate", change_str_rate);
        change_int_value = CHANGE_INT_VALUE[level];
        change_int_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 506, "change_int_value", change_int_value);
        change_int_rate = CHANGE_INT_RATE[level];
        change_int_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 506, "change_int_rate", change_int_rate);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.stamina *= 1.0f + multiple * change_sta_rate / 100.0f;
        pc.stamina += multiple * change_sta_value;
        pc.agility *= 1.0f + multiple * change_agi_rate / 100.0f;
        pc.agility += multiple * change_agi_value;
        pc.strength *= 1.0f + multiple * change_str_rate / 100.0f;
        pc.strength += multiple * change_str_value;
        pc.intellect *= 1.0f + multiple * change_int_rate / 100.0f;
        pc.intellect += multiple * change_int_value;
    }

}
