package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_278 implements Buff, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1
    };
    public static int[] IGNORE_ARMOR_VALUE = {
        0, 0
    };
    public static float[] IGNORE_ARMOR_PERCENT = {
        0.0f, 100.0f
    };
    public static int[] IGNORE_MAGIC_ARMOR_VALUE = {
        0, 0
    };
    public static float[] IGNORE_MAGIC_ARMOR_PERCENT = {
        0.0f, 100.0f
    };
    public static float[] IMMUNE_FEAR_RATE = {
        0.0f, 100.0f
    };
    public static float[] IMMUNE_DUMB_RATE = {
        0.0f, 100.0f
    };
    public static float[] IMMUNE_BREAK_RATE = {
        0.0f, 100.0f
    };
    public static float[] IMMUNE_PARALYZE_RATE = {
        0.0f, 100.0f
    };
    public static float[] IMMUNE_STAY_RATE = {
        0.0f, 100.0f
    };
    int instanceID;
    int realWeight;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int ignore_armor_value;
    float ignore_armor_percent;
    int ignore_magic_armor_value;
    float ignore_magic_armor_percent;
    float immune_fear_rate;
    float immune_dumb_rate;
    float immune_break_rate;
    float immune_paralyze_rate;
    float immune_stay_rate;

    public AutoGeneratedBuff_278(int lvl, Unit src, Unit tgt, int dmg) {
        if (src != null) {
            source = src.ref();
        }
        if (tgt != null) {
            owner = tgt.ref();
        }
        instanceID = BuffUtil.getNextID();
        level = lvl;
        endTime = Time.currTime + BuffUtil.enhanceParam(src, tgt, 278, "buffTime", DURATION[level]);
        multiple = 1;
        ignore_armor_value = IGNORE_ARMOR_VALUE[level];
        ignore_armor_value = BuffUtil.enhanceParam(src, tgt, 278, "ignore_armor_value", ignore_armor_value);
        ignore_armor_percent = IGNORE_ARMOR_PERCENT[level];
        ignore_armor_percent = BuffUtil.enhanceParam(src, tgt, 278, "ignore_armor_percent", ignore_armor_percent);
        ignore_magic_armor_value = IGNORE_MAGIC_ARMOR_VALUE[level];
        ignore_magic_armor_value = BuffUtil.enhanceParam(src, tgt, 278, "ignore_magic_armor_value", ignore_magic_armor_value);
        ignore_magic_armor_percent = IGNORE_MAGIC_ARMOR_PERCENT[level];
        ignore_magic_armor_percent = BuffUtil.enhanceParam(src, tgt, 278, "ignore_magic_armor_percent", ignore_magic_armor_percent);
        immune_fear_rate = IMMUNE_FEAR_RATE[level];
        immune_fear_rate = BuffUtil.enhanceParam(src, tgt, 278, "immune_fear_rate", immune_fear_rate);
        immune_dumb_rate = IMMUNE_DUMB_RATE[level];
        immune_dumb_rate = BuffUtil.enhanceParam(src, tgt, 278, "immune_dumb_rate", immune_dumb_rate);
        immune_break_rate = IMMUNE_BREAK_RATE[level];
        immune_break_rate = BuffUtil.enhanceParam(src, tgt, 278, "immune_break_rate", immune_break_rate);
        immune_paralyze_rate = IMMUNE_PARALYZE_RATE[level];
        immune_paralyze_rate = BuffUtil.enhanceParam(src, tgt, 278, "immune_paralyze_rate", immune_paralyze_rate);
        immune_stay_rate = IMMUNE_STAY_RATE[level];
        immune_stay_rate = BuffUtil.enhanceParam(src, tgt, 278, "immune_stay_rate", immune_stay_rate);
    }

    public int getId() {
        return 278;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "´©´Ì¹¥»÷Ó²»¯Æ¤·ô";
    }

    public String getDesc() {
        return "¹¥»÷ÎÞÊÓÄ¿±ê100%»¤¼×·¨·À£¬100%ÃâÒß£¨¿Ö¾å¡¢³ÁÄ¬¡¢Âé±Ô¡¢¶¨Éí¡¢´ò¶Ï£©¡£";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return 17 | 0x1000000;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public int getMergeStrategy() {
        return 0;
    }

    public boolean isNeedMerge() {
        return false;
    }

    public float getchange_dembuff_rate() {
         return 0;
    }

    public boolean merge(Buff buff) {
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (!isActive && context.hited() && context.skill instanceof FearSkill) {
            int rate = (int)(multiple * 100 * immune_fear_rate);
            if (CommonUtil.hit(RND, rate, 10000)) {
                context.attackResult = CombatContext.ATTACKRESULT_IMMUNE;
                effectTimes++;
            }
        }
        if (!isActive && context.hited() && context.skill instanceof DumbSkill) {
            int rate = (int)(multiple * 100 * immune_dumb_rate);
            if (CommonUtil.hit(RND, rate, 10000)) {
                context.attackResult = CombatContext.ATTACKRESULT_IMMUNE;
                effectTimes++;
            }
        }
        if (!isActive && context.hited() && context.skill instanceof BreakAttackSkill) {
            int rate = (int)(multiple * 100 * immune_break_rate);
            if (CommonUtil.hit(RND, rate, 10000)) {
                context.attackResult = CombatContext.ATTACKRESULT_IMMUNE;
                effectTimes++;
            }
        }
        if (!isActive && context.hited() && context.skill instanceof ParalyzeSkill) {
            int rate = (int)(multiple * 100 * immune_paralyze_rate);
            if (CommonUtil.hit(RND, rate, 10000)) {
                context.attackResult = CombatContext.ATTACKRESULT_IMMUNE;
                effectTimes++;
            }
        }
        if (!isActive && context.hited() && context.skill instanceof StaySkill) {
            int rate = (int)(multiple * 100 * immune_stay_rate);
            if (CommonUtil.hit(RND, rate, 10000)) {
                context.attackResult = CombatContext.ATTACKRESULT_IMMUNE;
                effectTimes++;
            }
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive && context.damageType == CombatContext.DAMAGE_PHYSICAL) {
            context.armor -= multiple * ignore_armor_value;
            context.armorRate -= multiple * ignore_armor_percent / 100.0f;
            effectTimes++;
        }
        if (isActive && context.damageType == CombatContext.DAMAGE_MAGIC) {
            context.armor -= multiple * ignore_magic_armor_value;
            context.armorRate -= multiple * ignore_magic_armor_percent / 100.0f;
            effectTimes++;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

}
