package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_582 implements Buff, PropertyEnhancer, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1
    };
    public static int[] CHANGE_PHYSICAL_AP_VALUE = {
        0, 900
    };
    public static float[] CHANGE_PHYSICAL_AP_PERCENT = {
        0.0f, 0.0f
    };
    public static int[] CHANGE_MAGIC_AP_VALUE = {
        0, 600
    };
    public static float[] CHANGE_MAGIC_AP_PERCENT = {
        0.0f, 0.0f
    };
    public static int[] CHANGE_CURE_VALUE = {
        0, 600
    };
    public static float[] CHANGE_CURE_PERCENT = {
        0.0f, 0.0f
    };
    public static int[] CHANGE_PHYSICAL_DODGE_RATE = {
        0, 180
    };
    public static int[] CHANGE_MAGIC_DODGE_RATE = {
        0, 180
    };
    public static int[] CHANGE_MAXHP_VALUE = {
        0, 5000
    };
    public static float[] CHANGE_MAXHP_PERCENT = {
        0.0f, 0.0f
    };
    int instanceID;
    int realWeight;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_physical_ap_value;
    float change_physical_ap_percent;
    int change_magic_ap_value;
    float change_magic_ap_percent;
    int change_cure_value;
    float change_cure_percent;
    int change_physical_dodge_rate;
    int change_magic_dodge_rate;
    int change_maxhp_value;
    float change_maxhp_percent;


    public AutoGeneratedBuff_582(int lvl) {
        int dmg = 0;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        change_physical_ap_value = CHANGE_PHYSICAL_AP_VALUE[level];
        change_physical_ap_percent = CHANGE_PHYSICAL_AP_PERCENT[level];
        change_magic_ap_value = CHANGE_MAGIC_AP_VALUE[level];
        change_magic_ap_percent = CHANGE_MAGIC_AP_PERCENT[level];
        change_cure_value = CHANGE_CURE_VALUE[level];
        change_cure_percent = CHANGE_CURE_PERCENT[level];
        change_physical_dodge_rate = CHANGE_PHYSICAL_DODGE_RATE[level];
        change_magic_dodge_rate = CHANGE_MAGIC_DODGE_RATE[level];
        change_maxhp_value = CHANGE_MAXHP_VALUE[level];
        change_maxhp_percent = CHANGE_MAXHP_PERCENT[level];
    }

    public int getId() {
        return 582;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "十星星辉";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("物理攻击提升{0}点；法术攻击提升{1}点；生命上限提升{2}点；物理和法术闪避提升{3}点；使用还魂香包复活角色时恢复100%的生命值和气力/精力值。", CommonUtil.formatValue(change_physical_ap_value * multiple), CommonUtil.formatValue(change_magic_ap_value * multiple), CommonUtil.formatValue(change_maxhp_value * multiple), CommonUtil.formatValue(change_physical_dodge_rate * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return true;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public int getMergeStrategy() {
        return 4;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public float getchange_dembuff_rate() {
         return 0;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_582) {
            AutoGeneratedBuff_582 other = (AutoGeneratedBuff_582)buff;
            level = other.level;
            endTime = other.endTime;
            multiple = 1;
            remainSeconds = other.remainSeconds;
            tickInterval = other.tickInterval;
            remainCure = other.remainCure;
            remainDamage = other.remainDamage;
            remainMPCure = other.remainMPCure;
            remainMPDamage = other.remainMPDamage;
            remainAbsorb = other.remainAbsorb;
            effectTimes = 0;
            owner = other.owner;
            source = other.source;
            change_physical_ap_value = other.change_physical_ap_value;
            change_physical_ap_percent = other.change_physical_ap_percent;
            change_magic_ap_value = other.change_magic_ap_value;
            change_magic_ap_percent = other.change_magic_ap_percent;
            change_cure_value = other.change_cure_value;
            change_cure_percent = other.change_cure_percent;
            change_physical_dodge_rate = other.change_physical_dodge_rate;
            change_magic_dodge_rate = other.change_magic_dodge_rate;
            change_maxhp_value = other.change_maxhp_value;
            change_maxhp_percent = other.change_maxhp_percent;
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        change_physical_ap_value = CHANGE_PHYSICAL_AP_VALUE[level];
        change_physical_ap_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 582, "change_physical_ap_value", change_physical_ap_value);
        change_physical_ap_percent = CHANGE_PHYSICAL_AP_PERCENT[level];
        change_physical_ap_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 582, "change_physical_ap_percent", change_physical_ap_percent);
        change_magic_ap_value = CHANGE_MAGIC_AP_VALUE[level];
        change_magic_ap_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 582, "change_magic_ap_value", change_magic_ap_value);
        change_magic_ap_percent = CHANGE_MAGIC_AP_PERCENT[level];
        change_magic_ap_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 582, "change_magic_ap_percent", change_magic_ap_percent);
        change_cure_value = CHANGE_CURE_VALUE[level];
        change_cure_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 582, "change_cure_value", change_cure_value);
        change_cure_percent = CHANGE_CURE_PERCENT[level];
        change_cure_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 582, "change_cure_percent", change_cure_percent);
        change_physical_dodge_rate = CHANGE_PHYSICAL_DODGE_RATE[level];
        change_physical_dodge_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 582, "change_physical_dodge_rate", change_physical_dodge_rate);
        change_magic_dodge_rate = CHANGE_MAGIC_DODGE_RATE[level];
        change_magic_dodge_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 582, "change_magic_dodge_rate", change_magic_dodge_rate);
        change_maxhp_value = CHANGE_MAXHP_VALUE[level];
        change_maxhp_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 582, "change_maxhp_value", change_maxhp_value);
        change_maxhp_percent = CHANGE_MAXHP_PERCENT[level];
        change_maxhp_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 582, "change_maxhp_percent", change_maxhp_percent);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.attackpowerup += multiple * change_physical_ap_value;
        pc.attackpowerdown += multiple * change_physical_ap_value;
        pc.attackpowerRate += multiple * change_physical_ap_percent / 100.0f;
        pc.spellpowerRate += multiple * change_magic_ap_percent / 100.0f;
        pc.spellpower += multiple * change_magic_ap_value;
        pc.dodgerating += multiple * change_physical_dodge_rate;
        pc.spelldodgerating += multiple * change_magic_dodge_rate;
        pc.hp += multiple * change_maxhp_value;
        pc.hpRate += multiple * change_maxhp_percent / 100.0f;
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive && context.damageType == CombatContext.DAMAGE_HEAL && !context.isAdditive) {
            context.damage += context.damage * multiple * change_cure_percent / 100.0f;
            context.damage += multiple * change_cure_value;
            effectTimes++;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

}
