package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_434 implements Buff, PropertyEnhancer {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1
    };
    public static float[] CHANGE_PHYSICAL_HIT = {
        0.0f, 4.0f
    };
    public static float[] CHANGE_PHYSICAL_DODGE = {
        0.0f, 4.0f
    };
    public static float[] CHANGE_MAGIC_HIT = {
        0.0f, 4.0f
    };
    public static float[] CHANGE_MAGIC_DODGE = {
        0.0f, 4.0f
    };
    int instanceID;
    int realWeight;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    float change_physical_hit;
    float change_physical_dodge;
    float change_magic_hit;
    float change_magic_dodge;


    public AutoGeneratedBuff_434(int lvl) {
        int dmg = 0;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        change_physical_hit = CHANGE_PHYSICAL_HIT[level];
        change_physical_dodge = CHANGE_PHYSICAL_DODGE[level];
        change_magic_hit = CHANGE_MAGIC_HIT[level];
        change_magic_dodge = CHANGE_MAGIC_DODGE[level];
    }

    public int getId() {
        return 434;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "六星星辉(坐骑)";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("物理和法术命中增加{0}；闪避增加{1}", CommonUtil.formatPercent(change_physical_hit * multiple), CommonUtil.formatPercent(change_magic_hit * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public int getMergeStrategy() {
        return 2;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public float getchange_dembuff_rate() {
         return 0;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_434) {
            AutoGeneratedBuff_434 other = (AutoGeneratedBuff_434)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                change_physical_hit = other.change_physical_hit;
                change_physical_dodge = other.change_physical_dodge;
                change_magic_hit = other.change_magic_hit;
                change_magic_dodge = other.change_magic_dodge;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        change_physical_hit = CHANGE_PHYSICAL_HIT[level];
        change_physical_hit = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 434, "change_physical_hit", change_physical_hit);
        change_physical_dodge = CHANGE_PHYSICAL_DODGE[level];
        change_physical_dodge = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 434, "change_physical_dodge", change_physical_dodge);
        change_magic_hit = CHANGE_MAGIC_HIT[level];
        change_magic_hit = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 434, "change_magic_hit", change_magic_hit);
        change_magic_dodge = CHANGE_MAGIC_DODGE[level];
        change_magic_dodge = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 434, "change_magic_dodge", change_magic_dodge);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.hit += multiple * change_physical_hit / 100.0f;
        pc.dodge += multiple * change_physical_dodge / 100.0f;
        pc.spellhit += multiple * change_magic_hit / 100.0f;
        pc.spelldodge += multiple * change_magic_dodge / 100.0f;
    }

}
