package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_107 implements Buff, SkillBuff, PropertyEnhancer {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1, -1, -1, -1, -1
    };
    public static float[] CHANGE_MAGIC_CRIT = {
        0.0f, 5.0f, 6.0f, 7.0f, 8.0f, 9.0f
    };
    Skill skill;
    int instanceID;
    int realWeight;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    float change_magic_crit;

    public AutoGeneratedBuff_107(Skill skl, int lvl) {
        int dmg = 0;
        skill = skl;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        change_magic_crit = CHANGE_MAGIC_CRIT[level];
    }

    public int getId() {
        return skill.getId();
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "大浪淘沙";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("提升法术暴击率{0}", CommonUtil.formatPercent(change_magic_crit * multiple));
    }

    public Skill getSkill() {
        return skill;
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public int getMergeStrategy() {
        return 2;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public float getchange_dembuff_rate() {
         return 0;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_107) {
            AutoGeneratedBuff_107 other = (AutoGeneratedBuff_107)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                change_magic_crit = other.change_magic_crit;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        change_magic_crit = CHANGE_MAGIC_CRIT[level];
        change_magic_crit = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 107, "change_magic_crit", change_magic_crit);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.spellcritical += multiple * change_magic_crit / 100.0f;
    }

}
