package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_541 implements Buff, PropertyEnhancer, Updatable, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, 10000
    };
    public static int[] DOT_SECONDS = {
        0, 10
    };
    public static int[] DOT_TICK_TIME = {
        0, 2
    };
    public static int[] DOT_VALUE = {
        0, 5000
    };
    public static float[] DOT_PERCENT_OF_DAMAGE = {
        0.0f, 0.0f
    };
    public static int[] MPHOT_SECONDS = {
        0, 10
    };
    public static int[] MPHOT_TICK_TIME = {
        0, 2
    };
    public static int[] MPHOT_VALUE = {
        0, 5000
    };
    public static float[] MPHOT_PERCENT_OF_DAMAGE = {
        0.0f, 0.0f
    };
    public static float[] CHANGE_PHYSICAL_HIT = {
        0.0f, -50.0f
    };
    public static float[] CHANGE_MAGIC_HIT = {
        0.0f, -50.0f
    };
    public static int[] CHANGE_CURE_VALUE = {
        0, 0
    };
    public static float[] CHANGE_CURE_PERCENT = {
        0.0f, 50.0f
    };
    int instanceID;
    int realWeight;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int dot_seconds;
    int dot_tick_time;
    int dot_value;
    float dot_percent_of_damage;
    int mphot_seconds;
    int mphot_tick_time;
    int mphot_value;
    float mphot_percent_of_damage;
    float change_physical_hit;
    float change_magic_hit;
    int change_cure_value;
    float change_cure_percent;

    public AutoGeneratedBuff_541(int lvl, Unit src, Unit tgt, int dmg) {
        if (src != null) {
            source = src.ref();
        }
        if (tgt != null) {
            owner = tgt.ref();
        }
        instanceID = BuffUtil.getNextID();
        level = lvl;
        endTime = Time.currTime + BuffUtil.enhanceParam(src, tgt, 541, "buffTime", DURATION[level]);
        multiple = 1;
        dot_seconds = DOT_SECONDS[level];
        dot_seconds = BuffUtil.enhanceParam(src, tgt, 541, "dot_seconds", dot_seconds);
        dot_tick_time = DOT_TICK_TIME[level];
        dot_tick_time = BuffUtil.enhanceParam(src, tgt, 541, "dot_tick_time", dot_tick_time);
        dot_value = DOT_VALUE[level];
        dot_value = BuffUtil.enhanceParam(src, tgt, 541, "dot_value", dot_value);
        dot_percent_of_damage = DOT_PERCENT_OF_DAMAGE[level];
        dot_percent_of_damage = BuffUtil.enhanceParam(src, tgt, 541, "dot_percent_of_damage", dot_percent_of_damage);
        mphot_seconds = MPHOT_SECONDS[level];
        mphot_seconds = BuffUtil.enhanceParam(src, tgt, 541, "mphot_seconds", mphot_seconds);
        mphot_tick_time = MPHOT_TICK_TIME[level];
        mphot_tick_time = BuffUtil.enhanceParam(src, tgt, 541, "mphot_tick_time", mphot_tick_time);
        mphot_value = MPHOT_VALUE[level];
        mphot_value = BuffUtil.enhanceParam(src, tgt, 541, "mphot_value", mphot_value);
        mphot_percent_of_damage = MPHOT_PERCENT_OF_DAMAGE[level];
        mphot_percent_of_damage = BuffUtil.enhanceParam(src, tgt, 541, "mphot_percent_of_damage", mphot_percent_of_damage);
        change_physical_hit = CHANGE_PHYSICAL_HIT[level];
        change_physical_hit = BuffUtil.enhanceParam(src, tgt, 541, "change_physical_hit", change_physical_hit);
        change_magic_hit = CHANGE_MAGIC_HIT[level];
        change_magic_hit = BuffUtil.enhanceParam(src, tgt, 541, "change_magic_hit", change_magic_hit);
        change_cure_value = CHANGE_CURE_VALUE[level];
        change_cure_value = BuffUtil.enhanceParam(src, tgt, 541, "change_cure_value", change_cure_value);
        change_cure_percent = CHANGE_CURE_PERCENT[level];
        change_cure_percent = BuffUtil.enhanceParam(src, tgt, 541, "change_cure_percent", change_cure_percent);
        remainSeconds = dot_seconds;
        tickInterval = dot_tick_time;
        remainDamage = dot_value;
        remainDamage += dot_percent_of_damage * dmg / 100.0f;
        remainMPCure = mphot_value;
        remainMPCure += mphot_percent_of_damage * dmg / 100.0f;
    }

    public int getId() {
        return 541;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "小火";
    }

    public String getDesc() {
        return "10秒内造成5000伤害，降低50%命中；同时10秒内恢复5000蓝，提高50%治疗效果";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return Time.currTime + remainSeconds * 1000;
    }

    public boolean isGood() {
        return false;
    }

    public boolean dispelable() {
        return true;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return 69 | 0x1000000;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public int getMergeStrategy() {
        return 4;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public float getchange_dembuff_rate() {
         return 0;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_541) {
            AutoGeneratedBuff_541 other = (AutoGeneratedBuff_541)buff;
            level = other.level;
            endTime = other.endTime;
            multiple = 1;
            remainSeconds = other.remainSeconds;
            tickInterval = other.tickInterval;
            remainCure = other.remainCure;
            remainDamage = other.remainDamage;
            remainMPCure = other.remainMPCure;
            remainMPDamage = other.remainMPDamage;
            remainAbsorb = other.remainAbsorb;
            effectTimes = 0;
            owner = other.owner;
            source = other.source;
            dot_seconds = other.dot_seconds;
            dot_tick_time = other.dot_tick_time;
            dot_value = other.dot_value;
            dot_percent_of_damage = other.dot_percent_of_damage;
            mphot_seconds = other.mphot_seconds;
            mphot_tick_time = other.mphot_tick_time;
            mphot_value = other.mphot_value;
            mphot_percent_of_damage = other.mphot_percent_of_damage;
            change_physical_hit = other.change_physical_hit;
            change_magic_hit = other.change_magic_hit;
            change_cure_value = other.change_cure_value;
            change_cure_percent = other.change_cure_percent;
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
    }

    public boolean update(int diff) {
        if (((remainSeconds - 1) % tickInterval) == 0) {
            int remainTicks = (remainSeconds - 1) / tickInterval + 1;
            int cure = remainCure / remainTicks;
            int dmg = remainDamage / remainTicks;
            int mpcure = remainMPCure / remainTicks;
            int mpdmg = remainMPDamage / remainTicks;
            remainCure -= cure;
            remainDamage -= dmg;
            remainMPCure -= mpcure;
            remainMPDamage -= mpdmg;
            if (cure > 0) {
                Unit healerUnit = (Unit)ObjectAccessor.getGameObject(source);
                Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
                if (targetUnit != null && targetUnit.isAlive()) {
                    cure = targetUnit.setHp(targetUnit.hp + cure, true);
                    if (healerUnit != null && healerUnit.isAlive()) {
                        Attack.addHealThreat(healerUnit, targetUnit, CombatContext.calcHotThreat(cure), false);
                    }
                }
            }
            if (dmg > 0) {
                Unit sourceUnit = (Unit)ObjectAccessor.getGameObject(source);
                Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
                if (targetUnit != null && targetUnit.isAlive()) {
                    targetUnit.setHp(targetUnit.hp - dmg, true);
                    if (sourceUnit != null && sourceUnit.isAlive()) {
                        Attack.addDamageThreat(sourceUnit, targetUnit, dmg, false);
                    }
                    if (targetUnit.hp <= 0) {
                        targetUnit.die(sourceUnit);
                    }
                }
            }
            if (mpcure > 0) {
                Unit healerUnit = (Unit)ObjectAccessor.getGameObject(source);
                Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
                if (targetUnit != null && targetUnit.isAlive()) {
                    targetUnit.setMp(targetUnit.mp + mpcure, true);
                    if (healerUnit != null && healerUnit.isAlive()) {
                        Attack.addHealThreat(healerUnit, targetUnit, mpcure, false);
                    }
                }
            }
            if (mpdmg > 0) {
                Unit sourceUnit = (Unit)ObjectAccessor.getGameObject(source);
                Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
                if (targetUnit != null && targetUnit.isAlive()) {
                    targetUnit.setMp(targetUnit.mp - mpdmg, true);
                    if (sourceUnit != null && sourceUnit.isAlive()) {
                        Attack.addDamageThreat(sourceUnit, targetUnit, mpdmg, false);
                    }
                }
            }
        }
        remainSeconds--;
        if (remainSeconds <= 0) {
            return true;
        }
        if (endTime <= Time.currTime) {
            return true;
        }
        return false;
    }

    public void load(byte[] bytes) {
        ByteBuffer buf = ByteBuffer.wrap(bytes);
        owner = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        source = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        level = buf.getInt();
        endTime = Time.elapseTime(buf.getLong());
        multiple = buf.getInt();
        dot_seconds = DOT_SECONDS[level];
        dot_tick_time = DOT_TICK_TIME[level];
        dot_value = DOT_VALUE[level];
        dot_percent_of_damage = DOT_PERCENT_OF_DAMAGE[level];
        mphot_seconds = MPHOT_SECONDS[level];
        mphot_tick_time = MPHOT_TICK_TIME[level];
        mphot_value = MPHOT_VALUE[level];
        mphot_percent_of_damage = MPHOT_PERCENT_OF_DAMAGE[level];
        change_physical_hit = CHANGE_PHYSICAL_HIT[level];
        change_magic_hit = CHANGE_MAGIC_HIT[level];
        change_cure_value = CHANGE_CURE_VALUE[level];
        change_cure_percent = CHANGE_CURE_PERCENT[level];
        remainSeconds = buf.getInt();
        tickInterval = buf.getInt();
        remainCure = buf.getInt();
        remainDamage = buf.getInt();
        remainMPCure = buf.getInt();
        remainMPDamage = buf.getInt();
        remainAbsorb = buf.getInt();
        effectTimes = buf.getInt();
    }

    public byte[] save() {
        ByteBuffer buf = ByteBuffer.allocate(66, false);
        buf.put(owner.type);
        buf.putInt(owner.id);
        buf.putInt(owner.instanceId);
        buf.put(source.type);
        buf.putInt(source.id);
        buf.putInt(source.instanceId);
        buf.putInt(level);
        buf.putLong(Time.currentTimeMillis(endTime));
        buf.putInt(multiple);
        buf.putInt(remainSeconds);
        buf.putInt(tickInterval);
        buf.putInt(remainCure);
        buf.putInt(remainDamage);
        buf.putInt(remainMPCure);
        buf.putInt(remainMPDamage);
        buf.putInt(remainAbsorb);
        buf.putInt(effectTimes);
        return buf.array();
    }

    public boolean update2(int time) {
        if (remainSeconds <= 0) {
            return false;
        }
        endTime += time;
        if (endTime <= Time.currTime) {
            return false;
        }
        return true;
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.hit += multiple * change_physical_hit / 100.0f;
        pc.spellhit += multiple * change_magic_hit / 100.0f;
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive && context.damageType == CombatContext.DAMAGE_HEAL && !context.isAdditive) {
            context.damage += context.damage * multiple * change_cure_percent / 100.0f;
            context.damage += multiple * change_cure_value;
            effectTimes++;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

}
