package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_600 implements Buff, PropertyEnhancer, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, -1, -1, -1, -1, -1
    };
    public static int[] REDUCE_PHYSICAL_DAMAGE_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] REDUCE_PHYSICAL_DAMAGE_PERCENT = {
        0.0f, 5.0f, 5.0f, 6.0f, 6.0f, 6.0f
    };
    public static int[] REDUCE_MAGIC_DAMAGE_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] REDUCE_MAGIC_DAMAGE_PERCENT = {
        0.0f, 5.0f, 5.0f, 6.0f, 6.0f, 6.0f
    };
    public static int[] CHANGE_BASIC_HP_VALUE = {
        0, 1900, 2100, 2400, 2600, 2900
    };
    public static float[] CHANGE_BASIC_HP_RATE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] CHANGE_BASIC_MP_VALUE = {
        0, 1900, 2100, 2400, 2600, 2900
    };
    public static float[] CHANGE_BASIC_MP_RATE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    int instanceID;
    int realWeight;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int reduce_physical_damage_value;
    float reduce_physical_damage_percent;
    int reduce_magic_damage_value;
    float reduce_magic_damage_percent;
    int change_basic_hp_value;
    float change_basic_hp_rate;
    int change_basic_mp_value;
    float change_basic_mp_rate;


    public AutoGeneratedBuff_600(int lvl) {
        int dmg = 0;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        reduce_physical_damage_value = REDUCE_PHYSICAL_DAMAGE_VALUE[level];
        reduce_physical_damage_percent = REDUCE_PHYSICAL_DAMAGE_PERCENT[level];
        reduce_magic_damage_value = REDUCE_MAGIC_DAMAGE_VALUE[level];
        reduce_magic_damage_percent = REDUCE_MAGIC_DAMAGE_PERCENT[level];
        change_basic_hp_value = CHANGE_BASIC_HP_VALUE[level];
        change_basic_hp_rate = CHANGE_BASIC_HP_RATE[level];
        change_basic_mp_value = CHANGE_BASIC_MP_VALUE[level];
        change_basic_mp_rate = CHANGE_BASIC_MP_RATE[level];
    }

    public int getId() {
        return 600;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "天命套装4件";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("提高生命和法力上限{0}点，战斗时伤害减免增加{1}", CommonUtil.formatValue(change_basic_hp_value * multiple), CommonUtil.formatPercent(reduce_physical_damage_percent * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public int getMergeStrategy() {
        return 2;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public float getchange_dembuff_rate() {
         return 0;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_600) {
            AutoGeneratedBuff_600 other = (AutoGeneratedBuff_600)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                reduce_physical_damage_value = other.reduce_physical_damage_value;
                reduce_physical_damage_percent = other.reduce_physical_damage_percent;
                reduce_magic_damage_value = other.reduce_magic_damage_value;
                reduce_magic_damage_percent = other.reduce_magic_damage_percent;
                change_basic_hp_value = other.change_basic_hp_value;
                change_basic_hp_rate = other.change_basic_hp_rate;
                change_basic_mp_value = other.change_basic_mp_value;
                change_basic_mp_rate = other.change_basic_mp_rate;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        reduce_physical_damage_value = REDUCE_PHYSICAL_DAMAGE_VALUE[level];
        reduce_physical_damage_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 600, "reduce_physical_damage_value", reduce_physical_damage_value);
        reduce_physical_damage_percent = REDUCE_PHYSICAL_DAMAGE_PERCENT[level];
        reduce_physical_damage_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 600, "reduce_physical_damage_percent", reduce_physical_damage_percent);
        reduce_magic_damage_value = REDUCE_MAGIC_DAMAGE_VALUE[level];
        reduce_magic_damage_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 600, "reduce_magic_damage_value", reduce_magic_damage_value);
        reduce_magic_damage_percent = REDUCE_MAGIC_DAMAGE_PERCENT[level];
        reduce_magic_damage_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 600, "reduce_magic_damage_percent", reduce_magic_damage_percent);
        change_basic_hp_value = CHANGE_BASIC_HP_VALUE[level];
        change_basic_hp_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 600, "change_basic_hp_value", change_basic_hp_value);
        change_basic_hp_rate = CHANGE_BASIC_HP_RATE[level];
        change_basic_hp_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 600, "change_basic_hp_rate", change_basic_hp_rate);
        change_basic_mp_value = CHANGE_BASIC_MP_VALUE[level];
        change_basic_mp_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 600, "change_basic_mp_value", change_basic_mp_value);
        change_basic_mp_rate = CHANGE_BASIC_MP_RATE[level];
        change_basic_mp_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 600, "change_basic_mp_rate", change_basic_mp_rate);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.hp += multiple * change_basic_hp_value;
        pc.basicHpRate += multiple * change_basic_hp_rate / 100.0f;
        pc.mp += multiple * change_basic_mp_value;
        pc.basicMpRate += multiple * change_basic_mp_rate / 100.0f;
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (!isActive && context.damageType == CombatContext.DAMAGE_PHYSICAL) {
            int value = multiple * reduce_physical_damage_value;
            value += context.damage * multiple * reduce_physical_damage_percent / 100.0f;
            if (value > context.damage) {
                value = context.damage;
            }
            if (context.damage > 0) {
                context.threat -= value * context.threat / context.damage;
                context.damage -= value;
            }
            effectTimes++;
        }
        if (!isActive && context.damageType == CombatContext.DAMAGE_MAGIC) {
            int value = multiple * reduce_magic_damage_value;
            value += context.damage * multiple * reduce_magic_damage_percent / 100.0f;
            if (value > context.damage) {
                value = context.damage;
            }
            if (context.damage > 0) {
                context.threat -= value * context.threat / context.damage;
                context.damage -= value;
            }
            effectTimes++;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

}
