package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_524 implements Buff, Updatable {
    private static final int[] WEAPON = {
        
    };
    public int buffover_addbuff = 0;
    public int buffover_addbuff_level = 0;
    public static int[] DURATION = {
        0, 6000
    };
    public static float[] IGNORE_MAGIC_PERCENT = {
        0.0f, 100.0f
    };
    public static float[] IGNORE_PHYSICS_PERCENT = {
        0.0f, 100.0f
    };
    public static int[] MAX_EFFECT_TIMES = {
        0, 1
    };
    int instanceID;
    int realWeight;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    float ignore_magic_percent;
    float ignore_physics_percent;
    int max_effect_times;

    public AutoGeneratedBuff_524(int lvl, Unit src, Unit tgt, int dmg) {
        if (src != null) {
            source = src.ref();
        }
        if (tgt != null) {
            owner = tgt.ref();
        }
        instanceID = BuffUtil.getNextID();
        level = lvl;
        endTime = Time.currTime + BuffUtil.enhanceParam(src, tgt, 524, "buffTime", DURATION[level]);
        multiple = 1;
        ignore_magic_percent = IGNORE_MAGIC_PERCENT[level];
        ignore_magic_percent = BuffUtil.enhanceParam(src, tgt, 524, "ignore_magic_percent", ignore_magic_percent);
        ignore_physics_percent = IGNORE_PHYSICS_PERCENT[level];
        ignore_physics_percent = BuffUtil.enhanceParam(src, tgt, 524, "ignore_physics_percent", ignore_physics_percent);
        max_effect_times = MAX_EFFECT_TIMES[level];
        max_effect_times = BuffUtil.enhanceParam(src, tgt, 524, "max_effect_times", max_effect_times);
    }

    public int getId() {
        return 524;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "龙威";
    }

    public String getDesc() {
        return "忽略对方物理免伤和法术免伤";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return endTime;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return 9 | 0x1000000;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public int getMergeStrategy() {
        return 4;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public float getchange_dembuff_rate() {
         return 0;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_524) {
            AutoGeneratedBuff_524 other = (AutoGeneratedBuff_524)buff;
            level = other.level;
            endTime = other.endTime;
            multiple = 1;
            remainSeconds = other.remainSeconds;
            tickInterval = other.tickInterval;
            remainCure = other.remainCure;
            remainDamage = other.remainDamage;
            remainMPCure = other.remainMPCure;
            remainMPDamage = other.remainMPDamage;
            remainAbsorb = other.remainAbsorb;
            effectTimes = 0;
            owner = other.owner;
            source = other.source;
            ignore_magic_percent = other.ignore_magic_percent;
            ignore_physics_percent = other.ignore_physics_percent;
            max_effect_times = other.max_effect_times;
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
    }

    public boolean update(int diff) {
        if (endTime <= Time.currTime) {
            return true;
        }
        if (effectTimes >= max_effect_times) {
            return true;
        }
        return false;
    }

    public void load(byte[] bytes) {
        ByteBuffer buf = ByteBuffer.wrap(bytes);
        owner = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        source = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        level = buf.getInt();
        endTime = Time.elapseTime(buf.getLong());
        multiple = buf.getInt();
        ignore_magic_percent = IGNORE_MAGIC_PERCENT[level];
        ignore_physics_percent = IGNORE_PHYSICS_PERCENT[level];
        max_effect_times = MAX_EFFECT_TIMES[level];
        remainSeconds = buf.getInt();
        tickInterval = buf.getInt();
        remainCure = buf.getInt();
        remainDamage = buf.getInt();
        remainMPCure = buf.getInt();
        remainMPDamage = buf.getInt();
        remainAbsorb = buf.getInt();
        effectTimes = buf.getInt();
    }

    public byte[] save() {
        ByteBuffer buf = ByteBuffer.allocate(66, false);
        buf.put(owner.type);
        buf.putInt(owner.id);
        buf.putInt(owner.instanceId);
        buf.put(source.type);
        buf.putInt(source.id);
        buf.putInt(source.instanceId);
        buf.putInt(level);
        buf.putLong(Time.currentTimeMillis(endTime));
        buf.putInt(multiple);
        buf.putInt(remainSeconds);
        buf.putInt(tickInterval);
        buf.putInt(remainCure);
        buf.putInt(remainDamage);
        buf.putInt(remainMPCure);
        buf.putInt(remainMPDamage);
        buf.putInt(remainAbsorb);
        buf.putInt(effectTimes);
        return buf.array();
    }

    public boolean update2(int time) {
        endTime += time;
        if (endTime <= Time.currTime) {
            return false;
        }
        return true;
    }

}
