package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;

public class AutoGeneratedSkill_041 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 5, 11, 17, 23, 29, 35, 41, 47, 53, 59, 65, 71, 77, 83, 89
    };
    public static float[] MP_USE = {
        0.0f, -2.8f, -2.75f, -2.7f, -2.65f, -2.6000001f, -2.5500002f, -2.5000002f, -2.4500003f, -2.4000003f, -2.3500004f, -2.3000004f, -2.2500005f, -2.2000005f, -2.1500006f, -2.1000006f
    };
    public static int[] ACT_TIME = {
        0, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000
    };
    public static int[] CD_TIME = {
        0, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000, 4000
    };
    public static int[] DISTANCE = {
        0, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104
    };
    public static int[] RANGE = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static int[] CHANGE_MAGIC_AP_VALUE = {
        0, 70, 98, 126, 154, 182, 210, 238, 266, 294, 322, 350, 378, 406, 434, 462
    };
    public static float[] CHANGE_MAGIC_AP_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_WEAPON_MATK_VALUE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] CHANGE_THREAT_VALUE = {
        0, 70, 98, 126, 154, 182, 210, 238, 266, 294, 322, 350, 378, 406, 434, 462
    };
    public static float[] CHANGE_THREAT_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] ADD_DEBUFF_RATE = {
        0.0f, 18.0f, 18.0f, 18.0f, 18.0f, 18.0f, 18.0f, 18.0f, 18.0f, 18.0f, 18.0f, 18.0f, 18.0f, 18.0f, 18.0f, 18.0f
    };
    public static String[] ADD_DEBUFF_RATE_VAR = {
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""
    };
    public static int[] ADD_DEBUFF_ID = {
        0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10
    };
    public static int[] ADD_DEBUFF_LEVEL = {
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
    };
    int change_magic_ap_value;
    float change_magic_ap_percent;
    float change_weapon_matk_value;
    int change_threat_value;
    float change_threat_percent;
    float add_debuff_rate;
    String add_debuff_rate_var;
    int add_debuff_id;
    int add_debuff_level;

    public AutoGeneratedSkill_041(int lvl) {
        super(41, "天罡烈焰", lvl);
        if (lvl > 15) {
            throw new IllegalArgumentException();
        }
        change_magic_ap_value = CHANGE_MAGIC_AP_VALUE[lvl];
        change_magic_ap_percent = CHANGE_MAGIC_AP_PERCENT[lvl];
        change_weapon_matk_value = CHANGE_WEAPON_MATK_VALUE[lvl];
        change_threat_value = CHANGE_THREAT_VALUE[lvl];
        change_threat_percent = CHANGE_THREAT_PERCENT[lvl];
        add_debuff_rate = ADD_DEBUFF_RATE[lvl];
        add_debuff_rate_var = ADD_DEBUFF_RATE_VAR[lvl];
        add_debuff_id = ADD_DEBUFF_ID[lvl];
        add_debuff_level = ADD_DEBUFF_LEVEL[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 41;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = 26;
        prepareAnimation = -65534;
        castAnimation = -65534;
        hitAnimation = 106;
        clazz = Unit.CLASS_3;
        mp = MP_USE[lvl];
        type = TYPE_ATTACK;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_SINGLE_ATTACK;
    }

    public String getDesc(Unit owner) {
        return java.text.MessageFormat.format("召喚出火龍纏繞並灼燒對方,造成普通法術傷害及{0}點法術傷害;並有18%幾率造成焚燒效果,使目標在3秒內受到{1}點傷害", CommonUtil.formatValue(change_magic_ap_value), CommonUtil.formatValue(peony.game.buff.AutoGeneratedBuff_010.DOT_VALUE[add_debuff_level]));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public boolean isAutoLearn() {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_MAGIC;
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        context.attackPower += context.getSkillParam(this, "change_magic_ap_value", change_magic_ap_value);
        context.attackPowerRate += context.getSkillParam(this, "change_magic_ap_percent", change_magic_ap_percent) / 100.0f;
        if (context.source.equipments != null && context.source.equipments.getWeapon() != null) {
            GameItem weapon = context.source.equipments.getWeapon();
            context.attackPower += weapon.getMagicPower() * context.getSkillParam(this, "change_weapon_matk_value", change_weapon_matk_value) / 100.0f;
        }
        context.threatAdd += context.getSkillParam(this, "change_threat_value", change_threat_value);
        context.threatAddRate += context.getSkillParam(this, "change_threat_percent", change_threat_percent) / 100.0f;
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited()) {
            boolean hit = false;
            if (add_debuff_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(100 * context.getSkillParam(this, "add_debuff_rate", add_debuff_rate)), 10000);
            } else {
                Float vo = context.skillParams.get(add_debuff_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(100 * (vo.floatValue() + context.getSkillParam(this, "add_debuff_rate", add_debuff_rate))), 10000);
                }
            }
            if (hit) {
                context.target.buffs.addBuff(BuffUtil.createBuff(add_debuff_id, add_debuff_level, context.source, context.target, context.damage));
            }
        }
    }

}
