package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;

public class AutoGeneratedSkill_046 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 27, 35, 43, 51, 59, 67, 75, 83, 91, 99
    };
    public static float[] MP_USE = {
        0.0f, -2.95f, -2.95f, -2.95f, -2.95f, -2.95f, -2.95f, -2.95f, -2.95f, -2.95f, -2.95f
    };
    public static int[] ACT_TIME = {
        0, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000
    };
    public static int[] CD_TIME = {
        0, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000
    };
    public static int[] DISTANCE = {
        0, 104, 104, 104, 104, 104, 104, 104, 104, 104, 104
    };
    public static int[] RANGE = {
        0, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64
    };
    public static int[] CHANGE_MAGIC_AP_VALUE = {
        0, 60, 85, 110, 135, 160, 185, 210, 235, 260, 285
    };
    public static float[] CHANGE_MAGIC_AP_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_WEAPON_MATK_VALUE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] CHANGE_THREAT_VALUE = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static float[] CHANGE_THREAT_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] STAY_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f
    };
    public static String[] STAY_RATE_VAR = {
        "", "", "", "", "", "", "", "", "", "", ""
    };
    public static int[] STAY_TIME = {
        0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000
    };
    int change_magic_ap_value;
    float change_magic_ap_percent;
    float change_weapon_matk_value;
    int change_threat_value;
    float change_threat_percent;
    float stay_rate;
    String stay_rate_var;
    int stay_time;

    public AutoGeneratedSkill_046(int lvl) {
        super(46, "巧借東風", lvl);
        if (lvl > 10) {
            throw new IllegalArgumentException();
        }
        change_magic_ap_value = CHANGE_MAGIC_AP_VALUE[lvl];
        change_magic_ap_percent = CHANGE_MAGIC_AP_PERCENT[lvl];
        change_weapon_matk_value = CHANGE_WEAPON_MATK_VALUE[lvl];
        change_threat_value = CHANGE_THREAT_VALUE[lvl];
        change_threat_percent = CHANGE_THREAT_PERCENT[lvl];
        stay_rate = STAY_RATE[lvl];
        stay_rate_var = STAY_RATE_VAR[lvl];
        stay_time = STAY_TIME[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 46;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = 28;
        prepareAnimation = -65534;
        castAnimation = -65534;
        hitAnimation = 111;
        clazz = Unit.CLASS_3;
        mp = MP_USE[lvl];
        type = TYPE_ATTACK;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_AOE_ATTACK_TARGET;
    }

    public String getDesc(Unit owner) {
        return java.text.MessageFormat.format("在目標所在位置召喚一股颶風,對其周圍{0}碼範圍內的所有敵方目標造成普通法術傷害及{1}點法術傷害,並陷入定身狀態無法移動,持續{2}", CommonUtil.formatValue(getRange(owner) / 8.0f), CommonUtil.formatValue(change_magic_ap_value), CommonUtil.formatMillSecond(stay_time));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public boolean isAutoLearn() {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_MAGIC;
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        context.attackPower += context.getSkillParam(this, "change_magic_ap_value", change_magic_ap_value);
        context.attackPowerRate += context.getSkillParam(this, "change_magic_ap_percent", change_magic_ap_percent) / 100.0f;
        if (context.source.equipments != null && context.source.equipments.getWeapon() != null) {
            GameItem weapon = context.source.equipments.getWeapon();
            context.attackPower += weapon.getMagicPower() * context.getSkillParam(this, "change_weapon_matk_value", change_weapon_matk_value) / 100.0f;
        }
        context.threatAdd += context.getSkillParam(this, "change_threat_value", change_threat_value);
        context.threatAddRate += context.getSkillParam(this, "change_threat_percent", change_threat_percent) / 100.0f;
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited()) {
            boolean hit = false;
            if (stay_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(100 * context.getSkillParam(this, "stay_rate", stay_rate)), 10000);
            } else {
                Float vo = context.skillParams.get(stay_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(100 * (vo.floatValue() + context.getSkillParam(this, "stay_rate", stay_rate))), 10000);
                }
            }
            if (hit) {
                context.activeSkills.add(new StaySkill(context.getSkillParam(this, "stay_time", stay_time)));
            }
        }
    }

}
