package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_016 implements Buff, SkillBuff, PropertyEnhancer, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
    public static int[] CHANGE_ARMOR_VALUE = {
        0, 224, 375, 526, 677, 828, 979, 1130, 1281, 1432, 1583, 1734, 1885, 2036, 2187, 2338
    };
    public static float[] CHANGE_ARMOR_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] CHANGE_MAGIC_ARMOR_VALUE = {
        0, 11, 23, 35, 47, 59, 71, 83, 95, 107, 119, 131, 143, 155, 167, 179
    };
    public static float[] CHANGE_MAGIC_ARMOR_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] ADD_BUFF_HITED_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f
    };
    public static String[] ADD_BUFF_HITED_RATE_VAR = {
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""
    };
    public static int[] ADD_BUFF_HITED_ID = {
        0, 142, 142, 142, 142, 142, 142, 142, 142, 142, 142, 142, 142, 142, 142, 142
    };
    public static int[] ADD_BUFF_HITED_LEVEL = {
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
    };
    public static int[] CHANGE_THREAT_VALUE = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static float[] CHANGE_THREAT_PERCENT = {
        0.0f, 300.0f, 300.0f, 300.0f, 300.0f, 300.0f, 300.0f, 300.0f, 300.0f, 300.0f, 300.0f, 300.0f, 300.0f, 300.0f, 300.0f, 300.0f
    };
    Skill skill;
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_armor_value;
    float change_armor_percent;
    int change_magic_armor_value;
    float change_magic_armor_percent;
    float add_buff_hited_rate;
    String add_buff_hited_rate_var;
    int add_buff_hited_id;
    int add_buff_hited_level;
    int change_threat_value;
    float change_threat_percent;

    public AutoGeneratedBuff_016(Skill skl, int lvl) {
        int dmg = 0;
        skill = skl;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        change_armor_value = CHANGE_ARMOR_VALUE[level];
        change_armor_percent = CHANGE_ARMOR_PERCENT[level];
        change_magic_armor_value = CHANGE_MAGIC_ARMOR_VALUE[level];
        change_magic_armor_percent = CHANGE_MAGIC_ARMOR_PERCENT[level];
        add_buff_hited_rate = ADD_BUFF_HITED_RATE[level];
        add_buff_hited_rate_var = ADD_BUFF_HITED_RATE_VAR[level];
        add_buff_hited_id = ADD_BUFF_HITED_ID[level];
        add_buff_hited_level = ADD_BUFF_HITED_LEVEL[level];
        change_threat_value = CHANGE_THREAT_VALUE[level];
        change_threat_percent = CHANGE_THREAT_PERCENT[level];
    }

    public int getId() {
        return skill.getId();
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "固若金汤";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("提升{0}点护甲及{1}点法防，每次受到攻击击后3秒内恢复{2}点气力值", CommonUtil.formatValue(change_armor_value * multiple), CommonUtil.formatValue(change_magic_armor_value * multiple), CommonUtil.formatValue(peony.game.buff.AutoGeneratedBuff_142.MPHOT_VALUE[add_buff_hited_level] * multiple));
    }

    public Skill getSkill() {
        return skill;
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_016) {
            AutoGeneratedBuff_016 other = (AutoGeneratedBuff_016)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                change_armor_value = other.change_armor_value;
                change_armor_percent = other.change_armor_percent;
                change_magic_armor_value = other.change_magic_armor_value;
                change_magic_armor_percent = other.change_magic_armor_percent;
                add_buff_hited_rate = other.add_buff_hited_rate;
                add_buff_hited_rate_var = other.add_buff_hited_rate_var;
                add_buff_hited_id = other.add_buff_hited_id;
                add_buff_hited_level = other.add_buff_hited_level;
                change_threat_value = other.change_threat_value;
                change_threat_percent = other.change_threat_percent;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        change_armor_value = CHANGE_ARMOR_VALUE[level];
        change_armor_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 16, "change_armor_value", change_armor_value);
        change_armor_percent = CHANGE_ARMOR_PERCENT[level];
        change_armor_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 16, "change_armor_percent", change_armor_percent);
        change_magic_armor_value = CHANGE_MAGIC_ARMOR_VALUE[level];
        change_magic_armor_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 16, "change_magic_armor_value", change_magic_armor_value);
        change_magic_armor_percent = CHANGE_MAGIC_ARMOR_PERCENT[level];
        change_magic_armor_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 16, "change_magic_armor_percent", change_magic_armor_percent);
        add_buff_hited_rate = ADD_BUFF_HITED_RATE[level];
        add_buff_hited_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 16, "add_buff_hited_rate", add_buff_hited_rate);
        add_buff_hited_level = ADD_BUFF_HITED_LEVEL[level];
        add_buff_hited_level = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 16, "add_buff_hited_level", add_buff_hited_level);
        change_threat_value = CHANGE_THREAT_VALUE[level];
        change_threat_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 16, "change_threat_value", change_threat_value);
        change_threat_percent = CHANGE_THREAT_PERCENT[level];
        change_threat_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 16, "change_threat_percent", change_threat_percent);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.defenseRate += multiple * change_armor_percent / 100.0f;
        pc.defense += multiple * change_armor_value;
        if (pc.defense < 0) {
            pc.defense = 0;
        }
        pc.spellDefenseRate += multiple * change_magic_armor_percent / 100.0f;
        pc.spelldefense += multiple * change_magic_armor_value;
        if (pc.spelldefense < 0) {
            pc.spelldefense = 0;
        }
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive) {
            context.threatAdd += multiple * change_threat_value;
            context.threatAddRate += multiple * change_threat_percent / 100.0f;
            effectTimes++;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (!isActive && context.hited() && context.isAttack()) {
            boolean hit = false;
            if (add_buff_hited_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(multiple * 100 * add_buff_hited_rate), 10000);
            } else {
                Float vo = context.skillParams.get(add_buff_hited_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(multiple * 100 * (vo.floatValue() + add_buff_hited_rate)), 10000);
                }
            }
            if (hit) {
                context.target.buffs.addBuff(BuffUtil.createBuff(add_buff_hited_id, add_buff_hited_level, context.target, context.target, context.damage));
                effectTimes++;
            }
        }
    }

}
