package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_244 implements Buff, Updatable, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, 2500
    };
    public static float[] DOUBLE_DAMAGE_RATE = {
        0.0f, 100.0f
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    float double_damage_rate;

    public AutoGeneratedBuff_244(int lvl, Unit src, Unit tgt, int dmg) {
        if (src != null) {
            source = src.ref();
        }
        if (tgt != null) {
            owner = tgt.ref();
        }
        instanceID = BuffUtil.getNextID();
        level = lvl;
        endTime = Time.currTime + BuffUtil.enhanceParam(src, tgt, 244, "buffTime", DURATION[level]);
        multiple = 1;
        double_damage_rate = DOUBLE_DAMAGE_RATE[level];
        double_damage_rate = BuffUtil.enhanceParam(src, tgt, 244, "double_damage_rate", double_damage_rate);
    }

    public int getId() {
        return 244;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "双倍攻击";
    }

    public String getDesc() {
        return "在2.5秒时间内拥有双倍攻击力";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return endTime;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return true;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return 74 | 0x1000000;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_244) {
            AutoGeneratedBuff_244 other = (AutoGeneratedBuff_244)buff;
            if (source.equals(other.source)) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure += other.remainCure;
                remainDamage += other.remainDamage;
                remainMPCure += other.remainMPCure;
                remainMPDamage += other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                double_damage_rate = other.double_damage_rate;
                return true;
            }
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
    }

    public boolean update(int diff) {
        if (endTime <= Time.currTime) {
            return true;
        }
        return false;
    }

    public void load(byte[] bytes) {
        ByteBuffer buf = ByteBuffer.wrap(bytes);
        owner = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        source = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        level = buf.getInt();
        endTime = Time.elapseTime(buf.getLong());
        multiple = buf.getInt();
        double_damage_rate = DOUBLE_DAMAGE_RATE[level];
        remainSeconds = buf.getInt();
        tickInterval = buf.getInt();
        remainCure = buf.getInt();
        remainDamage = buf.getInt();
        remainMPCure = buf.getInt();
        remainMPDamage = buf.getInt();
        remainAbsorb = buf.getInt();
        effectTimes = buf.getInt();
    }

    public byte[] save() {
        ByteBuffer buf = ByteBuffer.allocate(66, false);
        buf.put(owner.type);
        buf.putInt(owner.id);
        buf.putInt(owner.instanceId);
        buf.put(source.type);
        buf.putInt(source.id);
        buf.putInt(source.instanceId);
        buf.putInt(level);
        buf.putLong(Time.currentTimeMillis(endTime));
        buf.putInt(multiple);
        buf.putInt(remainSeconds);
        buf.putInt(tickInterval);
        buf.putInt(remainCure);
        buf.putInt(remainDamage);
        buf.putInt(remainMPCure);
        buf.putInt(remainMPDamage);
        buf.putInt(remainAbsorb);
        buf.putInt(effectTimes);
        return buf.array();
    }

    public boolean update2(int time) {
        endTime += time;
        if (endTime <= Time.currTime) {
            return false;
        }
        return true;
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive && context.isDamage()) {
            int rate = (int)(multiple * 100 * double_damage_rate);
            if (CommonUtil.hit(RND, rate, 10000)) {
                context.damage *= 2;
                context.threat *= 2;
                effectTimes++;
            }
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

}
