package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_213 implements Buff, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, -1, -1, -1, -1
    };
    public static int[] CHANGE_THREAT_VALUE = {
        0, 0, 0, 0, 0
    };
    public static float[] CHANGE_THREAT_PERCENT = {
        0.0f, -20.0f, -25.0f, -30.0f, -35.0f
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_threat_value;
    float change_threat_percent;

    public AutoGeneratedBuff_213(int lvl) {
        int dmg = 0;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        change_threat_value = CHANGE_THREAT_VALUE[level];
        change_threat_percent = CHANGE_THREAT_PERCENT[level];
    }

    public int getId() {
        return 213;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "套装治疗3";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("所有技能的仇恨降低{0}", CommonUtil.formatPercent(change_threat_percent * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return false;
    }

    public boolean merge(Buff buff) {
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        change_threat_value = CHANGE_THREAT_VALUE[level];
        change_threat_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 213, "change_threat_value", change_threat_value);
        change_threat_percent = CHANGE_THREAT_PERCENT[level];
        change_threat_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 213, "change_threat_percent", change_threat_percent);
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive) {
            context.threatAdd += multiple * change_threat_value;
            context.threatAddRate += multiple * change_threat_percent / 100.0f;
            effectTimes++;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

}
