package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_375 implements Buff, Updatable, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, 5000, 5000, 5000, 5000, 5000
    };
    public static int[] CHANGE_B_PHYSICAL_AP_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] CHANGE_B_PHYSICAL_AP_PERCENT = {
        0.0f, -5.0f, -10.0f, -15.0f, -20.0f, -25.0f
    };
    public static int[] CHANGE_B_MAGIC_AP_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] CHANGE_B_MAGIC_AP_PERCENT = {
        0.0f, -5.0f, -10.0f, -15.0f, -20.0f, -25.0f
    };
    public static float[] CHANGE_B_PHYSICAL_HIT = {
        0.0f, -5.0f, -10.0f, -15.0f, -20.0f, -25.0f
    };
    public static float[] CHANGE_B_MAGIC_HIT = {
        0.0f, -5.0f, -10.0f, -15.0f, -20.0f, -25.0f
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_b_physical_ap_value;
    float change_b_physical_ap_percent;
    int change_b_magic_ap_value;
    float change_b_magic_ap_percent;
    float change_b_physical_hit;
    float change_b_magic_hit;

    public AutoGeneratedBuff_375(int lvl, Unit src, Unit tgt, int dmg) {
        if (src != null) {
            source = src.ref();
        }
        if (tgt != null) {
            owner = tgt.ref();
        }
        instanceID = BuffUtil.getNextID();
        level = lvl;
        endTime = Time.currTime + BuffUtil.enhanceParam(src, tgt, 375, "buffTime", DURATION[level]);
        multiple = 1;
        change_b_physical_ap_value = CHANGE_B_PHYSICAL_AP_VALUE[level];
        change_b_physical_ap_value = BuffUtil.enhanceParam(src, tgt, 375, "change_b_physical_ap_value", change_b_physical_ap_value);
        change_b_physical_ap_percent = CHANGE_B_PHYSICAL_AP_PERCENT[level];
        change_b_physical_ap_percent = BuffUtil.enhanceParam(src, tgt, 375, "change_b_physical_ap_percent", change_b_physical_ap_percent);
        change_b_magic_ap_value = CHANGE_B_MAGIC_AP_VALUE[level];
        change_b_magic_ap_value = BuffUtil.enhanceParam(src, tgt, 375, "change_b_magic_ap_value", change_b_magic_ap_value);
        change_b_magic_ap_percent = CHANGE_B_MAGIC_AP_PERCENT[level];
        change_b_magic_ap_percent = BuffUtil.enhanceParam(src, tgt, 375, "change_b_magic_ap_percent", change_b_magic_ap_percent);
        change_b_physical_hit = CHANGE_B_PHYSICAL_HIT[level];
        change_b_physical_hit = BuffUtil.enhanceParam(src, tgt, 375, "change_b_physical_hit", change_b_physical_hit);
        change_b_magic_hit = CHANGE_B_MAGIC_HIT[level];
        change_b_magic_hit = BuffUtil.enhanceParam(src, tgt, 375, "change_b_magic_hit", change_b_magic_hit);
    }

    public int getId() {
        return 375;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "削弱";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("攻击命中降低了{0}", CommonUtil.formatPercent(change_b_physical_ap_percent * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return endTime;
    }

    public boolean isGood() {
        return false;
    }

    public boolean dispelable() {
        return true;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return 73 | 0x1000000;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_375) {
            AutoGeneratedBuff_375 other = (AutoGeneratedBuff_375)buff;
            if (source.equals(other.source)) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure += other.remainCure;
                remainDamage += other.remainDamage;
                remainMPCure += other.remainMPCure;
                remainMPDamage += other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                change_b_physical_ap_value = other.change_b_physical_ap_value;
                change_b_physical_ap_percent = other.change_b_physical_ap_percent;
                change_b_magic_ap_value = other.change_b_magic_ap_value;
                change_b_magic_ap_percent = other.change_b_magic_ap_percent;
                change_b_physical_hit = other.change_b_physical_hit;
                change_b_magic_hit = other.change_b_magic_hit;
                return true;
            }
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
    }

    public boolean update(int diff) {
        if (endTime <= Time.currTime) {
            return true;
        }
        return false;
    }

    public void load(byte[] bytes) {
        ByteBuffer buf = ByteBuffer.wrap(bytes);
        owner = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        source = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        level = buf.getInt();
        endTime = Time.elapseTime(buf.getLong());
        multiple = buf.getInt();
        change_b_physical_ap_value = CHANGE_B_PHYSICAL_AP_VALUE[level];
        change_b_physical_ap_percent = CHANGE_B_PHYSICAL_AP_PERCENT[level];
        change_b_magic_ap_value = CHANGE_B_MAGIC_AP_VALUE[level];
        change_b_magic_ap_percent = CHANGE_B_MAGIC_AP_PERCENT[level];
        change_b_physical_hit = CHANGE_B_PHYSICAL_HIT[level];
        change_b_magic_hit = CHANGE_B_MAGIC_HIT[level];
        remainSeconds = buf.getInt();
        tickInterval = buf.getInt();
        remainCure = buf.getInt();
        remainDamage = buf.getInt();
        remainMPCure = buf.getInt();
        remainMPDamage = buf.getInt();
        remainAbsorb = buf.getInt();
        effectTimes = buf.getInt();
    }

    public byte[] save() {
        ByteBuffer buf = ByteBuffer.allocate(66, false);
        buf.put(owner.type);
        buf.putInt(owner.id);
        buf.putInt(owner.instanceId);
        buf.put(source.type);
        buf.putInt(source.id);
        buf.putInt(source.instanceId);
        buf.putInt(level);
        buf.putLong(Time.currentTimeMillis(endTime));
        buf.putInt(multiple);
        buf.putInt(remainSeconds);
        buf.putInt(tickInterval);
        buf.putInt(remainCure);
        buf.putInt(remainDamage);
        buf.putInt(remainMPCure);
        buf.putInt(remainMPDamage);
        buf.putInt(remainAbsorb);
        buf.putInt(effectTimes);
        return buf.array();
    }

    public boolean update2(int time) {
        endTime += time;
        if (endTime <= Time.currTime) {
            return false;
        }
        return true;
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive && context.damageType == CombatContext.DAMAGE_PHYSICAL) {
            context.hitRate += change_b_physical_hit / 100.0f;
            effectTimes++;
        }
        if (isActive && context.damageType != CombatContext.DAMAGE_PHYSICAL) {
            context.hitRate += change_b_magic_hit / 100.0f;
            effectTimes++;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive && context.damageType == CombatContext.DAMAGE_PHYSICAL) {
            context.attackPower += change_b_physical_ap_value;
            context.attackPowerRate += change_b_physical_ap_percent / 100.0f;
            effectTimes++;
        }
        if (isActive && (context.damageType == CombatContext.DAMAGE_MAGIC || context.damageType == CombatContext.DAMAGE_DECMP)) {
            context.attackPower += change_b_magic_ap_value;
            context.attackPowerRate += change_b_magic_ap_percent / 100.0f;
            effectTimes++;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

}
