package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_266 implements Buff, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, -1, -1, -1, -1, -1
    };
    public static float[] CRITED_BUFF_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f
    };
    public static int[] CRITED_BUFF_ID = {
        0, 267, 267, 267, 267, 267
    };
    public static int[] CRITED_BUFF_LEVEL = {
        0, 1, 2, 3, 4, 5
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    float crited_buff_rate;
    int crited_buff_id;
    int crited_buff_level;

    public AutoGeneratedBuff_266(int lvl) {
        int dmg = 0;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        crited_buff_rate = CRITED_BUFF_RATE[level];
        crited_buff_id = CRITED_BUFF_ID[level];
        crited_buff_level = CRITED_BUFF_LEVEL[level];
    }

    public int getId() {
        return 266;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "被暴偷攻击";
    }

    public String getDesc() {
        return "被爆击后5秒内命中目标偷取目标攻击力";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return false;
    }

    public boolean merge(Buff buff) {
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        crited_buff_rate = CRITED_BUFF_RATE[level];
        crited_buff_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 266, "crited_buff_rate", crited_buff_rate);
        crited_buff_level = CRITED_BUFF_LEVEL[level];
        crited_buff_level = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 266, "crited_buff_level", crited_buff_level);
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (!isActive && context.critical() && context.isAttack()) {
            boolean hit = CommonUtil.hit(RND, (int)(multiple * 100 * crited_buff_rate), 10000);
            if (hit) {
                context.target.buffs.addBuff(BuffUtil.createBuff(crited_buff_id, crited_buff_level, context.target, context.target, context.damage));
                effectTimes++;
            }
        }
    }

}
