package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_369 implements Buff, ParamEnhancer {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, -1, -1, -1, -1, -1
    };
    public static String[] CHANGE_PARAM_1 = {
        "", "0,6,16", "0,6,16", "0,6,16", "0,6,16", "0,6,16"
    };
    public static float[] CHANGE_PARAM_VALUE_1 = {
        0.0f, 10.0f, 20.0f, 25.0f, 30.0f, 35.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_1 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_2 = {
        "", "0,6,4", "0,6,4", "0,6,4", "0,6,4", "0,6,4"
    };
    public static float[] CHANGE_PARAM_VALUE_2 = {
        0.0f, 10.0f, 20.0f, 25.0f, 30.0f, 35.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_2 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_3 = {
        "", "0,2,17", "0,2,17", "0,2,17", "0,2,17", "0,2,17"
    };
    public static float[] CHANGE_PARAM_VALUE_3 = {
        0.0f, 30.0f, 45.0f, 60.0f, 75.0f, 90.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_3 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_4 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_4 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_4 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_5 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_5 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_5 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_6 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_6 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_6 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_7 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_7 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_7 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_8 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_8 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_8 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_9 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_9 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_9 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static String[] CHANGE_PARAM_10 = {
        "", "0,0,0", "0,0,0", "0,0,0", "0,0,0", "0,0,0"
    };
    public static float[] CHANGE_PARAM_VALUE_10 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] CHANGE_PARAM_PERCENT_10 = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    String change_param_1;
    float change_param_value_1;
    float change_param_percent_1;
    String change_param_2;
    float change_param_value_2;
    float change_param_percent_2;
    String change_param_3;
    float change_param_value_3;
    float change_param_percent_3;
    String change_param_4;
    float change_param_value_4;
    float change_param_percent_4;
    String change_param_5;
    float change_param_value_5;
    float change_param_percent_5;
    String change_param_6;
    float change_param_value_6;
    float change_param_percent_6;
    String change_param_7;
    float change_param_value_7;
    float change_param_percent_7;
    String change_param_8;
    float change_param_value_8;
    float change_param_percent_8;
    String change_param_9;
    float change_param_value_9;
    float change_param_percent_9;
    String change_param_10;
    float change_param_value_10;
    float change_param_percent_10;

    public AutoGeneratedBuff_369(int lvl) {
        int dmg = 0;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        change_param_1 = CHANGE_PARAM_1[level];
        change_param_value_1 = CHANGE_PARAM_VALUE_1[level];
        change_param_percent_1 = CHANGE_PARAM_PERCENT_1[level];
        change_param_2 = CHANGE_PARAM_2[level];
        change_param_value_2 = CHANGE_PARAM_VALUE_2[level];
        change_param_percent_2 = CHANGE_PARAM_PERCENT_2[level];
        change_param_3 = CHANGE_PARAM_3[level];
        change_param_value_3 = CHANGE_PARAM_VALUE_3[level];
        change_param_percent_3 = CHANGE_PARAM_PERCENT_3[level];
        change_param_4 = CHANGE_PARAM_4[level];
        change_param_value_4 = CHANGE_PARAM_VALUE_4[level];
        change_param_percent_4 = CHANGE_PARAM_PERCENT_4[level];
        change_param_5 = CHANGE_PARAM_5[level];
        change_param_value_5 = CHANGE_PARAM_VALUE_5[level];
        change_param_percent_5 = CHANGE_PARAM_PERCENT_5[level];
        change_param_6 = CHANGE_PARAM_6[level];
        change_param_value_6 = CHANGE_PARAM_VALUE_6[level];
        change_param_percent_6 = CHANGE_PARAM_PERCENT_6[level];
        change_param_7 = CHANGE_PARAM_7[level];
        change_param_value_7 = CHANGE_PARAM_VALUE_7[level];
        change_param_percent_7 = CHANGE_PARAM_PERCENT_7[level];
        change_param_8 = CHANGE_PARAM_8[level];
        change_param_value_8 = CHANGE_PARAM_VALUE_8[level];
        change_param_percent_8 = CHANGE_PARAM_PERCENT_8[level];
        change_param_9 = CHANGE_PARAM_9[level];
        change_param_value_9 = CHANGE_PARAM_VALUE_9[level];
        change_param_percent_9 = CHANGE_PARAM_PERCENT_9[level];
        change_param_10 = CHANGE_PARAM_10[level];
        change_param_value_10 = CHANGE_PARAM_VALUE_10[level];
        change_param_percent_10 = CHANGE_PARAM_PERCENT_10[level];
    }

    public int getId() {
        return 369;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "强化霸王翔吼";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("施放霸王翔吼时，有{0}几率使自己在10秒内减伤增加15%，恐惧目标的概率提升{1}；使嗜血飞斧有{2}几率驱散目标身上的一个有益状态", CommonUtil.formatPercent(change_param_value_1 * multiple), CommonUtil.formatPercent(change_param_value_2 * multiple), CommonUtil.formatPercent(change_param_value_3 * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_369) {
            AutoGeneratedBuff_369 other = (AutoGeneratedBuff_369)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                change_param_1 = other.change_param_1;
                change_param_value_1 = other.change_param_value_1;
                change_param_percent_1 = other.change_param_percent_1;
                change_param_2 = other.change_param_2;
                change_param_value_2 = other.change_param_value_2;
                change_param_percent_2 = other.change_param_percent_2;
                change_param_3 = other.change_param_3;
                change_param_value_3 = other.change_param_value_3;
                change_param_percent_3 = other.change_param_percent_3;
                change_param_4 = other.change_param_4;
                change_param_value_4 = other.change_param_value_4;
                change_param_percent_4 = other.change_param_percent_4;
                change_param_5 = other.change_param_5;
                change_param_value_5 = other.change_param_value_5;
                change_param_percent_5 = other.change_param_percent_5;
                change_param_6 = other.change_param_6;
                change_param_value_6 = other.change_param_value_6;
                change_param_percent_6 = other.change_param_percent_6;
                change_param_7 = other.change_param_7;
                change_param_value_7 = other.change_param_value_7;
                change_param_percent_7 = other.change_param_percent_7;
                change_param_8 = other.change_param_8;
                change_param_value_8 = other.change_param_value_8;
                change_param_percent_8 = other.change_param_percent_8;
                change_param_9 = other.change_param_9;
                change_param_value_9 = other.change_param_value_9;
                change_param_percent_9 = other.change_param_percent_9;
                change_param_10 = other.change_param_10;
                change_param_value_10 = other.change_param_value_10;
                change_param_percent_10 = other.change_param_percent_10;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        change_param_value_1 = CHANGE_PARAM_VALUE_1[level];
        change_param_value_1 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_value_1", change_param_value_1);
        change_param_percent_1 = CHANGE_PARAM_PERCENT_1[level];
        change_param_percent_1 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_percent_1", change_param_percent_1);
        change_param_value_2 = CHANGE_PARAM_VALUE_2[level];
        change_param_value_2 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_value_2", change_param_value_2);
        change_param_percent_2 = CHANGE_PARAM_PERCENT_2[level];
        change_param_percent_2 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_percent_2", change_param_percent_2);
        change_param_value_3 = CHANGE_PARAM_VALUE_3[level];
        change_param_value_3 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_value_3", change_param_value_3);
        change_param_percent_3 = CHANGE_PARAM_PERCENT_3[level];
        change_param_percent_3 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_percent_3", change_param_percent_3);
        change_param_value_4 = CHANGE_PARAM_VALUE_4[level];
        change_param_value_4 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_value_4", change_param_value_4);
        change_param_percent_4 = CHANGE_PARAM_PERCENT_4[level];
        change_param_percent_4 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_percent_4", change_param_percent_4);
        change_param_value_5 = CHANGE_PARAM_VALUE_5[level];
        change_param_value_5 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_value_5", change_param_value_5);
        change_param_percent_5 = CHANGE_PARAM_PERCENT_5[level];
        change_param_percent_5 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_percent_5", change_param_percent_5);
        change_param_value_6 = CHANGE_PARAM_VALUE_6[level];
        change_param_value_6 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_value_6", change_param_value_6);
        change_param_percent_6 = CHANGE_PARAM_PERCENT_6[level];
        change_param_percent_6 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_percent_6", change_param_percent_6);
        change_param_value_7 = CHANGE_PARAM_VALUE_7[level];
        change_param_value_7 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_value_7", change_param_value_7);
        change_param_percent_7 = CHANGE_PARAM_PERCENT_7[level];
        change_param_percent_7 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_percent_7", change_param_percent_7);
        change_param_value_8 = CHANGE_PARAM_VALUE_8[level];
        change_param_value_8 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_value_8", change_param_value_8);
        change_param_percent_8 = CHANGE_PARAM_PERCENT_8[level];
        change_param_percent_8 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_percent_8", change_param_percent_8);
        change_param_value_9 = CHANGE_PARAM_VALUE_9[level];
        change_param_value_9 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_value_9", change_param_value_9);
        change_param_percent_9 = CHANGE_PARAM_PERCENT_9[level];
        change_param_percent_9 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_percent_9", change_param_percent_9);
        change_param_value_10 = CHANGE_PARAM_VALUE_10[level];
        change_param_value_10 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_value_10", change_param_value_10);
        change_param_percent_10 = CHANGE_PARAM_PERCENT_10[level];
        change_param_percent_10 = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 369, "change_param_percent_10", change_param_percent_10);
    }

    public void getEnhanceParams(ParamEnhanceSet enhanceSet) {
        switch (level) {
        case 1:
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "add_buff_rate", change_param_value_1, change_param_percent_1 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "fear_rate", change_param_value_2, change_param_percent_2 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 2, "dispel_buff_rate", change_param_value_3, change_param_percent_3 / 100.0f);
            break;
        case 2:
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "add_buff_rate", change_param_value_1, change_param_percent_1 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "fear_rate", change_param_value_2, change_param_percent_2 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 2, "dispel_buff_rate", change_param_value_3, change_param_percent_3 / 100.0f);
            break;
        case 3:
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "add_buff_rate", change_param_value_1, change_param_percent_1 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "fear_rate", change_param_value_2, change_param_percent_2 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 2, "dispel_buff_rate", change_param_value_3, change_param_percent_3 / 100.0f);
            break;
        case 4:
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "add_buff_rate", change_param_value_1, change_param_percent_1 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "fear_rate", change_param_value_2, change_param_percent_2 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 2, "dispel_buff_rate", change_param_value_3, change_param_percent_3 / 100.0f);
            break;
        case 5:
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "add_buff_rate", change_param_value_1, change_param_percent_1 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "fear_rate", change_param_value_2, change_param_percent_2 / 100.0f);
            enhanceSet.add(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 2, "dispel_buff_rate", change_param_value_3, change_param_percent_3 / 100.0f);
            break;
        }
    }

    public void removeEnhanceParams(ParamEnhanceSet enhanceSet) {
        switch (level) {
        case 1:
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "add_buff_rate", change_param_value_1, change_param_percent_1 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "fear_rate", change_param_value_2, change_param_percent_2 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 2, "dispel_buff_rate", change_param_value_3, change_param_percent_3 / 100.0f);
            break;
        case 2:
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "add_buff_rate", change_param_value_1, change_param_percent_1 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "fear_rate", change_param_value_2, change_param_percent_2 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 2, "dispel_buff_rate", change_param_value_3, change_param_percent_3 / 100.0f);
            break;
        case 3:
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "add_buff_rate", change_param_value_1, change_param_percent_1 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "fear_rate", change_param_value_2, change_param_percent_2 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 2, "dispel_buff_rate", change_param_value_3, change_param_percent_3 / 100.0f);
            break;
        case 4:
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "add_buff_rate", change_param_value_1, change_param_percent_1 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "fear_rate", change_param_value_2, change_param_percent_2 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 2, "dispel_buff_rate", change_param_value_3, change_param_percent_3 / 100.0f);
            break;
        case 5:
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "add_buff_rate", change_param_value_1, change_param_percent_1 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 6, "fear_rate", change_param_value_2, change_param_percent_2 / 100.0f);
            enhanceSet.remove(ParamEnhanceSet.TYPE_SKILL_ACTIVE, 2, "dispel_buff_rate", change_param_value_3, change_param_percent_3 / 100.0f);
            break;
        }
    }

}
