package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_218 implements Buff, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, -1
    };
    public static int[] REDUCE_MAGIC_DAMAGE_VALUE = {
        0, 0
    };
    public static float[] REDUCE_MAGIC_DAMAGE_PERCENT = {
        0.0f, 10.0f
    };
    public static float[] CHANGE_B_PHYSICAL_CRITED = {
        0.0f, 2.0f
    };
    public static float[] CHANGE_B_MAGIC_CRITED = {
        0.0f, 2.0f
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int reduce_magic_damage_value;
    float reduce_magic_damage_percent;
    float change_b_physical_crited;
    float change_b_magic_crited;

    public AutoGeneratedBuff_218(int lvl) {
        int dmg = 0;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        reduce_magic_damage_value = REDUCE_MAGIC_DAMAGE_VALUE[level];
        reduce_magic_damage_percent = REDUCE_MAGIC_DAMAGE_PERCENT[level];
        change_b_physical_crited = CHANGE_B_PHYSICAL_CRITED[level];
        change_b_magic_crited = CHANGE_B_MAGIC_CRITED[level];
    }

    public int getId() {
        return 218;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "法减免暴";
    }

    public String getDesc() {
        return "战斗中法术伤害减免额外增加8%，战斗时降低目标暴击率2%";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return false;
    }

    public boolean merge(Buff buff) {
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        reduce_magic_damage_value = REDUCE_MAGIC_DAMAGE_VALUE[level];
        reduce_magic_damage_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 218, "reduce_magic_damage_value", reduce_magic_damage_value);
        reduce_magic_damage_percent = REDUCE_MAGIC_DAMAGE_PERCENT[level];
        reduce_magic_damage_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 218, "reduce_magic_damage_percent", reduce_magic_damage_percent);
        change_b_physical_crited = CHANGE_B_PHYSICAL_CRITED[level];
        change_b_physical_crited = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 218, "change_b_physical_crited", change_b_physical_crited);
        change_b_magic_crited = CHANGE_B_MAGIC_CRITED[level];
        change_b_magic_crited = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 218, "change_b_magic_crited", change_b_magic_crited);
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (!isActive && context.damageType == CombatContext.DAMAGE_PHYSICAL) {
            context.critRate += change_b_physical_crited / 100.0f;
            effectTimes++;
        }
        if (!isActive && context.damageType != CombatContext.DAMAGE_PHYSICAL) {
            context.critRate += change_b_magic_crited / 100.0f;
            effectTimes++;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (!isActive && context.damageType == CombatContext.DAMAGE_MAGIC) {
            int value = multiple * reduce_magic_damage_value;
            value += context.damage * multiple * reduce_magic_damage_percent / 100.0f;
            if (value > context.damage) {
                value = context.damage;
            }
            if (context.damage > 0) {
                context.threat -= value * context.threat / context.damage;
                context.damage -= value;
            }
            effectTimes++;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

}
