package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_146 implements Buff, PropertyEnhancer, Updatable, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, 12000, 12000, 12000
    };
    public static int[] CHANGE_ARMOR_VALUE = {
        0, 600, 1200, 1800
    };
    public static float[] CHANGE_ARMOR_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] ADD_DEBUFF_HITED_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f
    };
    public static String[] ADD_DEBUFF_HITED_RATE_VAR = {
        "", "", "", ""
    };
    public static int[] ADD_DEBUFF_HITED_ID = {
        0, 150, 150, 150
    };
    public static int[] ADD_DEBUFF_HITED_LEVEL = {
        0, 1, 2, 3
    };
    public static int[] CHANGE_THREAT_VALUE = {
        0, 0, 0, 0
    };
    public static float[] CHANGE_THREAT_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_armor_value;
    float change_armor_percent;
    float add_debuff_hited_rate;
    String add_debuff_hited_rate_var;
    int add_debuff_hited_id;
    int add_debuff_hited_level;
    int change_threat_value;
    float change_threat_percent;

    public AutoGeneratedBuff_146(int lvl, Unit src, Unit tgt, int dmg) {
        if (src != null) {
            source = src.ref();
        }
        if (tgt != null) {
            owner = tgt.ref();
        }
        instanceID = BuffUtil.getNextID();
        level = lvl;
        endTime = Time.currTime + BuffUtil.enhanceParam(src, tgt, 146, "buffTime", DURATION[level]);
        multiple = 1;
        change_armor_value = CHANGE_ARMOR_VALUE[level];
        change_armor_value = BuffUtil.enhanceParam(src, tgt, 146, "change_armor_value", change_armor_value);
        change_armor_percent = CHANGE_ARMOR_PERCENT[level];
        change_armor_percent = BuffUtil.enhanceParam(src, tgt, 146, "change_armor_percent", change_armor_percent);
        add_debuff_hited_rate = ADD_DEBUFF_HITED_RATE[level];
        add_debuff_hited_rate = BuffUtil.enhanceParam(src, tgt, 146, "add_debuff_hited_rate", add_debuff_hited_rate);
        add_debuff_hited_rate_var = ADD_DEBUFF_HITED_RATE_VAR[level];
        add_debuff_hited_id = ADD_DEBUFF_HITED_ID[level];
        add_debuff_hited_level = ADD_DEBUFF_HITED_LEVEL[level];
        add_debuff_hited_level = BuffUtil.enhanceParam(src, tgt, 146, "add_debuff_hited_level", add_debuff_hited_level);
        change_threat_value = CHANGE_THREAT_VALUE[level];
        change_threat_value = BuffUtil.enhanceParam(src, tgt, 146, "change_threat_value", change_threat_value);
        change_threat_percent = CHANGE_THREAT_PERCENT[level];
        change_threat_percent = BuffUtil.enhanceParam(src, tgt, 146, "change_threat_percent", change_threat_percent);
    }

    public int getId() {
        return 146;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "寒冰护体";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("护甲提高{0}点，被攻击时使攻击者5秒内移动速度降低{1}", CommonUtil.formatValue(change_armor_value * multiple), CommonUtil.formatPercent(peony.game.buff.AutoGeneratedBuff_150.CHANGE_SPEED_PERCENT[add_debuff_hited_level] * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return endTime;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return true;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return 118 | 0x1000000;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_146) {
            AutoGeneratedBuff_146 other = (AutoGeneratedBuff_146)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                change_armor_value = other.change_armor_value;
                change_armor_percent = other.change_armor_percent;
                add_debuff_hited_rate = other.add_debuff_hited_rate;
                add_debuff_hited_rate_var = other.add_debuff_hited_rate_var;
                add_debuff_hited_id = other.add_debuff_hited_id;
                add_debuff_hited_level = other.add_debuff_hited_level;
                change_threat_value = other.change_threat_value;
                change_threat_percent = other.change_threat_percent;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
    }

    public boolean update(int diff) {
        if (endTime <= Time.currTime) {
            return true;
        }
        return false;
    }

    public void load(byte[] bytes) {
        ByteBuffer buf = ByteBuffer.wrap(bytes);
        owner = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        source = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        level = buf.getInt();
        endTime = Time.elapseTime(buf.getLong());
        multiple = buf.getInt();
        change_armor_value = CHANGE_ARMOR_VALUE[level];
        change_armor_percent = CHANGE_ARMOR_PERCENT[level];
        add_debuff_hited_rate = ADD_DEBUFF_HITED_RATE[level];
        add_debuff_hited_rate_var = ADD_DEBUFF_HITED_RATE_VAR[level];
        add_debuff_hited_id = ADD_DEBUFF_HITED_ID[level];
        add_debuff_hited_level = ADD_DEBUFF_HITED_LEVEL[level];
        change_threat_value = CHANGE_THREAT_VALUE[level];
        change_threat_percent = CHANGE_THREAT_PERCENT[level];
        remainSeconds = buf.getInt();
        tickInterval = buf.getInt();
        remainCure = buf.getInt();
        remainDamage = buf.getInt();
        remainMPCure = buf.getInt();
        remainMPDamage = buf.getInt();
        remainAbsorb = buf.getInt();
        effectTimes = buf.getInt();
    }

    public byte[] save() {
        ByteBuffer buf = ByteBuffer.allocate(66, false);
        buf.put(owner.type);
        buf.putInt(owner.id);
        buf.putInt(owner.instanceId);
        buf.put(source.type);
        buf.putInt(source.id);
        buf.putInt(source.instanceId);
        buf.putInt(level);
        buf.putLong(Time.currentTimeMillis(endTime));
        buf.putInt(multiple);
        buf.putInt(remainSeconds);
        buf.putInt(tickInterval);
        buf.putInt(remainCure);
        buf.putInt(remainDamage);
        buf.putInt(remainMPCure);
        buf.putInt(remainMPDamage);
        buf.putInt(remainAbsorb);
        buf.putInt(effectTimes);
        return buf.array();
    }

    public boolean update2(int time) {
        endTime += time;
        if (endTime <= Time.currTime) {
            return false;
        }
        return true;
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.defenseRate += multiple * change_armor_percent / 100.0f;
        pc.defense += multiple * change_armor_value;
        if (pc.defense < 0) {
            pc.defense = 0;
        }
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive) {
            context.threatAdd += multiple * change_threat_value;
            context.threatAddRate += multiple * change_threat_percent / 100.0f;
            effectTimes++;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (!isActive && context.hited() && context.isAttack()) {
            boolean hit = false;
            if (add_debuff_hited_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(multiple * 100 * add_debuff_hited_rate), 10000);
            } else {
                Float vo = context.skillParams.get(add_debuff_hited_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(multiple * 100 * (vo.floatValue() + add_debuff_hited_rate)), 10000);
                }
            }
            if (hit) {
                context.source.buffs.addBuff(BuffUtil.createBuff(add_debuff_hited_id, add_debuff_hited_level, context.target, context.source, context.damage));
                effectTimes++;
            }
        }
    }

}
