package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_282 implements Buff, PropertyEnhancer, Updatable {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, 8000, 8000, 8000, 8000, 8000
    };
    public static int[] CHANGE_MAGIC_AP_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] CHANGE_MAGIC_AP_PERCENT = {
        0.0f, -30.0f, -50.0f, -70.0f, -90.0f, -100.0f
    };
    public static int[] CHANGE_HP_RENEW = {
        0, 2000, 4000, 8000, 16000, 32000
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_magic_ap_value;
    float change_magic_ap_percent;
    int change_hp_renew;

    public AutoGeneratedBuff_282(int lvl, Unit src, Unit tgt, int dmg) {
        if (src != null) {
            source = src.ref();
        }
        if (tgt != null) {
            owner = tgt.ref();
        }
        instanceID = BuffUtil.getNextID();
        level = lvl;
        endTime = Time.currTime + BuffUtil.enhanceParam(src, tgt, 282, "buffTime", DURATION[level]);
        multiple = 1;
        change_magic_ap_value = CHANGE_MAGIC_AP_VALUE[level];
        change_magic_ap_value = BuffUtil.enhanceParam(src, tgt, 282, "change_magic_ap_value", change_magic_ap_value);
        change_magic_ap_percent = CHANGE_MAGIC_AP_PERCENT[level];
        change_magic_ap_percent = BuffUtil.enhanceParam(src, tgt, 282, "change_magic_ap_percent", change_magic_ap_percent);
        change_hp_renew = CHANGE_HP_RENEW[level];
        change_hp_renew = BuffUtil.enhanceParam(src, tgt, 282, "change_hp_renew", change_hp_renew);
    }

    public int getId() {
        return 282;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "回血降攻击";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("8秒内法术攻击力下降了{0}，5秒回血提升了{1}点", CommonUtil.formatPercent(change_magic_ap_percent * multiple), CommonUtil.formatValue(change_hp_renew * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return endTime;
    }

    public boolean isGood() {
        return false;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return 73 | 0x1000000;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return false;
    }

    public boolean merge(Buff buff) {
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
    }

    public boolean update(int diff) {
        if (endTime <= Time.currTime) {
            return true;
        }
        return false;
    }

    public void load(byte[] bytes) {
        ByteBuffer buf = ByteBuffer.wrap(bytes);
        owner = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        source = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        level = buf.getInt();
        endTime = Time.elapseTime(buf.getLong());
        multiple = buf.getInt();
        change_magic_ap_value = CHANGE_MAGIC_AP_VALUE[level];
        change_magic_ap_percent = CHANGE_MAGIC_AP_PERCENT[level];
        change_hp_renew = CHANGE_HP_RENEW[level];
        remainSeconds = buf.getInt();
        tickInterval = buf.getInt();
        remainCure = buf.getInt();
        remainDamage = buf.getInt();
        remainMPCure = buf.getInt();
        remainMPDamage = buf.getInt();
        remainAbsorb = buf.getInt();
        effectTimes = buf.getInt();
    }

    public byte[] save() {
        ByteBuffer buf = ByteBuffer.allocate(66, false);
        buf.put(owner.type);
        buf.putInt(owner.id);
        buf.putInt(owner.instanceId);
        buf.put(source.type);
        buf.putInt(source.id);
        buf.putInt(source.instanceId);
        buf.putInt(level);
        buf.putLong(Time.currentTimeMillis(endTime));
        buf.putInt(multiple);
        buf.putInt(remainSeconds);
        buf.putInt(tickInterval);
        buf.putInt(remainCure);
        buf.putInt(remainDamage);
        buf.putInt(remainMPCure);
        buf.putInt(remainMPDamage);
        buf.putInt(remainAbsorb);
        buf.putInt(effectTimes);
        return buf.array();
    }

    public boolean update2(int time) {
        endTime += time;
        if (endTime <= Time.currTime) {
            return false;
        }
        return true;
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.spellpowerRate += multiple * change_magic_ap_percent / 100.0f;
        pc.spellpower += multiple * change_magic_ap_value;
        pc.healthrestore += multiple * change_hp_renew;
    }

}
