package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_401 implements Buff, Updatable {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, -1
    };
    public static int[] HP_SECONDS = {
        0, 15
    };
    public static int[] HP_TICK_TIME = {
        0, 3
    };
    public static float[] MAXHPPERCENT = {
        0.0f, 10.0f
    };
    public static int[] MP_SECONDS = {
        0, 15
    };
    public static int[] MP_TICK_TIME = {
        0, 3
    };
    public static float[] MAXMPPERCENT = {
        0.0f, 10.0f
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int ownerMap;
    int ownerX;
    int ownerY;
    int hp_seconds;
    int hp_tick_time;
    float maxhppercent;
    int mp_seconds;
    int mp_tick_time;
    float maxmppercent;

    public AutoGeneratedBuff_401(int lvl, Unit src, Unit tgt, int dmg) {
        if (src != null) {
            source = src.ref();
        }
        if (tgt != null) {
            owner = tgt.ref();
        }
        instanceID = BuffUtil.getNextID();
        level = lvl;
        endTime = Time.currTime + BuffUtil.enhanceParam(src, tgt, 401, "buffTime", DURATION[level]);
        multiple = 1;
        hp_seconds = HP_SECONDS[level];
        hp_seconds = BuffUtil.enhanceParam(src, tgt, 401, "hp_seconds", hp_seconds);
        hp_tick_time = HP_TICK_TIME[level];
        hp_tick_time = BuffUtil.enhanceParam(src, tgt, 401, "hp_tick_time", hp_tick_time);
        maxhppercent = MAXHPPERCENT[level];
        maxhppercent = BuffUtil.enhanceParam(src, tgt, 401, "maxhppercent", maxhppercent);
        mp_seconds = MP_SECONDS[level];
        mp_seconds = BuffUtil.enhanceParam(src, tgt, 401, "mp_seconds", mp_seconds);
        mp_tick_time = MP_TICK_TIME[level];
        mp_tick_time = BuffUtil.enhanceParam(src, tgt, 401, "mp_tick_time", mp_tick_time);
        maxmppercent = MAXMPPERCENT[level];
        maxmppercent = BuffUtil.enhanceParam(src, tgt, 401, "maxmppercent", maxmppercent);
        remainSeconds = hp_seconds;
        tickInterval = hp_tick_time;
        maxhppercent = maxhppercent / 100.0f;
        maxmppercent = maxmppercent / 100.0f;
        try {
            ownerMap = tgt.map.id;
        } catch (Exception e) {}
        ownerX = tgt.x;
        ownerY = tgt.y;
    }

    public int getId() {
        return 401;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "东海鱼翅";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("{0}内每{1}秒恢复生命上限{2}的生命值和气力上限{3}的气力值，进入战斗自动取消", CommonUtil.formatSecond(hp_seconds), CommonUtil.formatValue(hp_tick_time * multiple), CommonUtil.formatPercent(maxhppercent * multiple), CommonUtil.formatPercent(maxmppercent * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return Time.currTime + remainSeconds * 1000;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return 48 | 0x1000000;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_401) {
            AutoGeneratedBuff_401 other = (AutoGeneratedBuff_401)buff;
            level = other.level;
            endTime = other.endTime;
            multiple = 1;
            remainSeconds = other.remainSeconds;
            tickInterval = other.tickInterval;
            remainCure = other.remainCure;
            remainDamage = other.remainDamage;
            remainMPCure = other.remainMPCure;
            remainMPDamage = other.remainMPDamage;
            remainAbsorb = other.remainAbsorb;
            effectTimes = 0;
            owner = other.owner;
            source = other.source;
            hp_seconds = other.hp_seconds;
            hp_tick_time = other.hp_tick_time;
            maxhppercent = other.maxhppercent;
            mp_seconds = other.mp_seconds;
            mp_tick_time = other.mp_tick_time;
            maxmppercent = other.maxmppercent;
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
    }

    public boolean update(int diff) {
        if (((remainSeconds - 1) % tickInterval) == 0) {
            int remainTicks = (remainSeconds - 1) / tickInterval + 1;
            int cure = remainCure / remainTicks;
            int dmg = remainDamage / remainTicks;
            int mpcure = remainMPCure / remainTicks;
            int mpdmg = remainMPDamage / remainTicks;
            remainCure -= cure;
            remainDamage -= dmg;
            remainMPCure -= mpcure;
            remainMPDamage -= mpdmg;
            if (cure > 0) {
                Unit healerUnit = (Unit)ObjectAccessor.getGameObject(source);
                Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
                if (targetUnit != null && targetUnit.isAlive()) {
                    cure = targetUnit.setHp(targetUnit.hp + cure, true);
                    if (healerUnit != null && healerUnit.isAlive()) {
                        Attack.addHealThreat(healerUnit, targetUnit, CombatContext.calcHotThreat(cure), false);
                    }
                }
            }
            if (dmg > 0) {
                Unit sourceUnit = (Unit)ObjectAccessor.getGameObject(source);
                Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
                if (targetUnit != null && targetUnit.isAlive()) {
                    targetUnit.setHp(targetUnit.hp - dmg, true);
                    if (sourceUnit != null && sourceUnit.isAlive()) {
                        Attack.addDamageThreat(sourceUnit, targetUnit, dmg, false);
                    }
                    if (targetUnit.hp <= 0) {
                        targetUnit.die(sourceUnit);
                    }
                }
            }
            if (mpcure > 0) {
                Unit healerUnit = (Unit)ObjectAccessor.getGameObject(source);
                Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
                if (targetUnit != null && targetUnit.isAlive()) {
                    targetUnit.setMp(targetUnit.mp + mpcure, true);
                    if (healerUnit != null && healerUnit.isAlive()) {
                        Attack.addHealThreat(healerUnit, targetUnit, mpcure, false);
                    }
                }
            }
            if (mpdmg > 0) {
                Unit sourceUnit = (Unit)ObjectAccessor.getGameObject(source);
                Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
                if (targetUnit != null && targetUnit.isAlive()) {
                    targetUnit.setMp(targetUnit.mp - mpdmg, true);
                    if (sourceUnit != null && sourceUnit.isAlive()) {
                        Attack.addDamageThreat(sourceUnit, targetUnit, mpdmg, false);
                    }
                }
            }
            if (maxhppercent > 0) {
                Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
                if (targetUnit != null && targetUnit.isAlive()) {
                    float addHp = targetUnit.hp + targetUnit.maxhp * maxhppercent;
                    targetUnit.setHp((int) Math.min(addHp, targetUnit.maxhp), true);
                }
            }
            if (maxmppercent > 0) {
                Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
                if (targetUnit != null && targetUnit.isAlive()) {
                    float addMp = targetUnit.mp + targetUnit.maxmp * maxmppercent;
                    targetUnit.setMp((int) Math.min(addMp, targetUnit.maxmp), true);
                }
            }
        }
        remainSeconds--;
        if (remainSeconds <= 0) {
            return true;
        }
        Unit targetUnit = (Unit)ObjectAccessor.getGameObject(owner);
        if (targetUnit == null || targetUnit.map == null) {
            return true;
        }
        if (targetUnit.getThreatCount() > 0) {
            return true;
        }
        return false;
    }

    public void load(byte[] bytes) {
        ByteBuffer buf = ByteBuffer.wrap(bytes);
        owner = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        source = new GameObjectRef(buf.get(), buf.getInt(), buf.getInt());
        level = buf.getInt();
        endTime = Time.elapseTime(buf.getLong());
        multiple = buf.getInt();
        hp_seconds = HP_SECONDS[level];
        hp_tick_time = HP_TICK_TIME[level];
        maxhppercent = MAXHPPERCENT[level];
        mp_seconds = MP_SECONDS[level];
        mp_tick_time = MP_TICK_TIME[level];
        maxmppercent = MAXMPPERCENT[level];
        remainSeconds = buf.getInt();
        tickInterval = buf.getInt();
        remainCure = buf.getInt();
        remainDamage = buf.getInt();
        remainMPCure = buf.getInt();
        remainMPDamage = buf.getInt();
        remainAbsorb = buf.getInt();
        effectTimes = buf.getInt();
    }

    public byte[] save() {
        ByteBuffer buf = ByteBuffer.allocate(66, false);
        buf.put(owner.type);
        buf.putInt(owner.id);
        buf.putInt(owner.instanceId);
        buf.put(source.type);
        buf.putInt(source.id);
        buf.putInt(source.instanceId);
        buf.putInt(level);
        buf.putLong(Time.currentTimeMillis(endTime));
        buf.putInt(multiple);
        buf.putInt(remainSeconds);
        buf.putInt(tickInterval);
        buf.putInt(remainCure);
        buf.putInt(remainDamage);
        buf.putInt(remainMPCure);
        buf.putInt(remainMPDamage);
        buf.putInt(remainAbsorb);
        buf.putInt(effectTimes);
        return buf.array();
    }

    public boolean update2(int time) {
        if (remainSeconds <= 0) {
            return false;
        }
        return true;
    }

}
