package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;
import peony.game.itemenhance.ItemEnhance;

public class AutoGeneratedBuff_019 implements Buff, SkillBuff, PropertyEnhancer, CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, -1, -1, -1, -1, -1
    };
    public static int[] CHANGE_MAXHP_VALUE = {
        0, 150, 300, 450, 600, 750
    };
    public static float[] CHANGE_MAXHP_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] BOUNCE_RATE = {
        0.0f, 25.0f, 25.0f, 25.0f, 25.0f, 25.0f
    };
    public static int[] BOUNCE_DAMAGE_TYPE = {
        0, 0, 0, 0, 0, 0
    };
    public static int[] BOUNCE_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] BOUNCE_PERCENT_OF_DAMAGE = {
        0.0f, 8.0f, 11.0f, 14.0f, 17.0f, 20.0f
    };
    public static int[] CHANGE_THREAT_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] CHANGE_THREAT_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    Skill skill;
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_maxhp_value;
    float change_maxhp_percent;
    float bounce_rate;
    int bounce_damage_type;
    int bounce_value;
    float bounce_percent_of_damage;
    int change_threat_value;
    float change_threat_percent;

    public AutoGeneratedBuff_019(Skill skl, int lvl) {
        int dmg = 0;
        skill = skl;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        change_maxhp_value = CHANGE_MAXHP_VALUE[level];
        change_maxhp_percent = CHANGE_MAXHP_PERCENT[level];
        bounce_rate = BOUNCE_RATE[level];
        bounce_damage_type = BOUNCE_DAMAGE_TYPE[level];
        bounce_value = BOUNCE_VALUE[level];
        bounce_percent_of_damage = BOUNCE_PERCENT_OF_DAMAGE[level];
        change_threat_value = CHANGE_THREAT_VALUE[level];
        change_threat_percent = CHANGE_THREAT_PERCENT[level];
    }

    public int getId() {
        return skill.getId();
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "霸气阴灭阵";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("生命上限提升{0}，在受到伤害时有{1}几率反弹所受伤害的{2}", CommonUtil.formatValue(change_maxhp_value * multiple), CommonUtil.formatPercent(bounce_rate * multiple), CommonUtil.formatPercent(bounce_percent_of_damage * multiple));
    }

    public Skill getSkill() {
        return skill;
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_019) {
            AutoGeneratedBuff_019 other = (AutoGeneratedBuff_019)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                change_maxhp_value = other.change_maxhp_value;
                change_maxhp_percent = other.change_maxhp_percent;
                bounce_rate = other.bounce_rate;
                bounce_damage_type = other.bounce_damage_type;
                bounce_value = other.bounce_value;
                bounce_percent_of_damage = other.bounce_percent_of_damage;
                change_threat_value = other.change_threat_value;
                change_threat_percent = other.change_threat_percent;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        change_maxhp_value = CHANGE_MAXHP_VALUE[level];
        change_maxhp_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 19, "change_maxhp_value", change_maxhp_value);
        change_maxhp_percent = CHANGE_MAXHP_PERCENT[level];
        change_maxhp_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 19, "change_maxhp_percent", change_maxhp_percent);
        bounce_rate = BOUNCE_RATE[level];
        bounce_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 19, "bounce_rate", bounce_rate);
        bounce_damage_type = BOUNCE_DAMAGE_TYPE[level];
        bounce_damage_type = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 19, "bounce_damage_type", bounce_damage_type);
        bounce_value = BOUNCE_VALUE[level];
        bounce_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 19, "bounce_value", bounce_value);
        bounce_percent_of_damage = BOUNCE_PERCENT_OF_DAMAGE[level];
        bounce_percent_of_damage = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 19, "bounce_percent_of_damage", bounce_percent_of_damage);
        change_threat_value = CHANGE_THREAT_VALUE[level];
        change_threat_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 19, "change_threat_value", change_threat_value);
        change_threat_percent = CHANGE_THREAT_PERCENT[level];
        change_threat_percent = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 19, "change_threat_percent", change_threat_percent);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.hp += multiple * change_maxhp_value;
        pc.hpRate += multiple * change_maxhp_percent / 100.0f;
    }

    public void preHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (isActive) {
            context.threatAdd += multiple * change_threat_value;
            context.threatAddRate += multiple * change_threat_percent / 100.0f;
            effectTimes++;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(isActive ? context.source : context.target)) {
            return;
        }
        if (!isActive && context.hited() && context.isDamage()) {
            if (CommonUtil.hit(RND, (int)(multiple * 100 * bounce_rate), 10000)) {
                int dmg = bounce_value;
                dmg += context.damage * bounce_percent_of_damage / 100.0f;
                context.passiveSkills.add(new FixedDamageSkill(bounce_damage_type, dmg));
                effectTimes++;
            }
        }
    }

}
