port=8760
adminport=2264
authip=192.168.0.54
authport=7103
authreceivebuffsize=32767
authwritebuffsize=32767
serverid=itimes_meng
serverpassword=itimes
receivebuffsize=32767
writebuffsize=32767
tcpnodelay=true
poolbuffer=true
directbuffer=true
localip=192.168.50.73
datadir=D:/workspace/iTimes1.0-Editor/dev/data
gamecode=itimes_meng
connectsessionfactory=pip
webport=8761
cmccauthip=221.179.50.73
cmccauthport=6663
cmccserverpassword=itimes
arenaip=127.0.0.1
arenaport=9760
arenashowname=sky-
arenareceivebuffersize=32767
arenawritebuffersize=32767