package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;

public class AutoGeneratedSkill_132 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 50, 59, 68
    };
    public static float[] MP_USE = {
        0.0f, -4.02f, -5.1f, -6.18f
    };
    public static int[] ACT_TIME = {
        0, 0, 0, 0
    };
    public static int[] CD_TIME = {
        0, 300000, 300000, 300000
    };
    public static int[] DISTANCE = {
        0, 0, 0, 0
    };
    public static int[] RANGE = {
        0, 0, 0, 0
    };
    public static float[] ADD_DEBUFF_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f
    };
    public static String[] ADD_DEBUFF_RATE_VAR = {
        "", "", "", ""
    };
    public static int[] ADD_DEBUFF_ID = {
        0, 149, 149, 149
    };
    public static int[] ADD_DEBUFF_LEVEL = {
        0, 1, 2, 3
    };
    float add_debuff_rate;
    String add_debuff_rate_var;
    int add_debuff_id;
    int add_debuff_level;

    public AutoGeneratedSkill_132(int lvl) {
        super(132, "坚盾反击", lvl);
        if (lvl > 3) {
            throw new IllegalArgumentException();
        }
        add_debuff_rate = ADD_DEBUFF_RATE[lvl];
        add_debuff_rate_var = ADD_DEBUFF_RATE_VAR[lvl];
        add_debuff_id = ADD_DEBUFF_ID[lvl];
        add_debuff_level = ADD_DEBUFF_LEVEL[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 132;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = 113;
        prepareAnimation = -1;
        castAnimation = -1;
        hitAnimation = -1;
        clazz = Unit.CLASS_1;
        mp = MP_USE[lvl];
        type = TYPE_AID;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_AID_SELF;
    }

    public String getDesc(Unit owner) {
        return java.text.MessageFormat.format("在30秒内100%反弹<c3333EE>（不免疫）</c>{0}次任何形式的攻击伤害的30%", CommonUtil.formatValue(peony.game.buff.AutoGeneratedBuff_149.MAX_EFFECT_TIMES[add_debuff_level]));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public boolean isAutoLearn() {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_BUFF;
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited()) {
            boolean hit = false;
            if (add_debuff_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(100 * context.getSkillParam(this, "add_debuff_rate", add_debuff_rate)), 10000);
            } else {
                Float vo = context.skillParams.get(add_debuff_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(100 * (vo.floatValue() + context.getSkillParam(this, "add_debuff_rate", add_debuff_rate))), 10000);
                }
            }
            if (hit) {
                context.target.buffs.addBuff(BuffUtil.createBuff(add_debuff_id, add_debuff_level, context.source, context.target, context.damage));
            }
        }
    }

}
