package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;

public class AutoGeneratedSkill_145 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 0, 0
    };
    public static float[] MP_USE = {
        0.0f, 0.0f, 0.0f
    };
    public static int[] ACT_TIME = {
        0, 0, 0
    };
    public static int[] CD_TIME = {
        0, 0, 0
    };
    public static int[] DISTANCE = {
        0, 88, 88
    };
    public static int[] RANGE = {
        0, 0, 0
    };
    public static int[] CHANGE_PHYSICAL_AP_VALUE = {
        0, 1200, 2400
    };
    public static float[] CHANGE_PHYSICAL_AP_PERCENT = {
        0.0f, 10.0f, 10.0f
    };
    public static float[] PARALYZE_RATE = {
        0.0f, 100.0f, 100.0f
    };
    public static String[] PARALYZE_RATE_VAR = {
        "", "", ""
    };
    public static int[] PARALYSE_TIME = {
        0, 2000, 2000
    };
    public static float[] CHANGE_PHYSICAL_CRIT = {
        0.0f, -100.0f, -100.0f
    };
    int change_physical_ap_value;
    float change_physical_ap_percent;
    float paralyze_rate;
    String paralyze_rate_var;
    int paralyse_time;
    float change_physical_crit;

    public AutoGeneratedSkill_145(int lvl) {
        super(145, "H攻击附加麻痹", lvl);
        if (lvl > 2) {
            throw new IllegalArgumentException();
        }
        change_physical_ap_value = CHANGE_PHYSICAL_AP_VALUE[lvl];
        change_physical_ap_percent = CHANGE_PHYSICAL_AP_PERCENT[lvl];
        paralyze_rate = PARALYZE_RATE[lvl];
        paralyze_rate_var = PARALYZE_RATE_VAR[lvl];
        paralyse_time = PARALYSE_TIME[lvl];
        change_physical_crit = CHANGE_PHYSICAL_CRIT[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 145;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = -1;
        prepareAnimation = -1;
        castAnimation = -1;
        hitAnimation = 8;
        clazz = -1;
        mp = MP_USE[lvl];
        type = TYPE_ATTACK;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_SINGLE_ATTACK;
    }

    public String getDesc(Unit owner) {
        return "";
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_PHYSICAL;
        if (!checkWeapon(context.source)) {
            return;
        }
        context.critRate += context.getSkillParam(this, "change_physical_crit", change_physical_crit) / 100.0f;
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        context.attackPower += context.getSkillParam(this, "change_physical_ap_value", change_physical_ap_value);
        context.attackPowerRate += context.getSkillParam(this, "change_physical_ap_percent", change_physical_ap_percent) / 100.0f;
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited()) {
            boolean hit = false;
            if (paralyze_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(100 * context.getSkillParam(this, "paralyze_rate", paralyze_rate)), 10000);
            } else {
                Float vo = context.skillParams.get(paralyze_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(100 * (vo.floatValue() + context.getSkillParam(this, "paralyze_rate", paralyze_rate))), 10000);
                }
            }
            if (hit) {
                context.activeSkills.add(new ParalyzeSkill(context.getSkillParam(this, "paralyse_time", paralyse_time)));
            }
        }
    }

}
