package peony.game.skill;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;

public class AutoGeneratedSkill_026 extends AbstractSkill implements CombatEffect {
    private static final int[] WEAPON = {
        
    };
    public static int[] REQUIRE_LEVEL = {
        0, 27, 35, 43, 51, 59, 67, 75, 83, 91, 99
    };
    public static float[] MP_USE = {
        0.0f, -2.5f, -2.5f, -2.5f, -2.5f, -2.5f, -2.5f, -2.5f, -2.5f, -2.5f, -2.5f
    };
    public static int[] ACT_TIME = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static int[] CD_TIME = {
        0, 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000, 60000
    };
    public static int[] DISTANCE = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static int[] RANGE = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static int[] CHANGE_THREAT_VALUE = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    };
    public static float[] CHANGE_THREAT_PERCENT = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static float[] ADD_BUFF_RATE = {
        0.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f, 100.0f
    };
    public static String[] ADD_BUFF_RATE_VAR = {
        "", "", "", "", "", "", "", "", "", "", ""
    };
    public static int[] ADD_BUFF_ID = {
        0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8
    };
    public static int[] ADD_BUFF_LEVEL = {
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
    };
    int change_threat_value;
    float change_threat_percent;
    float add_buff_rate;
    String add_buff_rate_var;
    int add_buff_id;
    int add_buff_level;

    public AutoGeneratedSkill_026(int lvl) {
        super(26, "偷天换日", lvl);
        if (lvl > 10) {
            throw new IllegalArgumentException();
        }
        change_threat_value = CHANGE_THREAT_VALUE[lvl];
        change_threat_percent = CHANGE_THREAT_PERCENT[lvl];
        add_buff_rate = ADD_BUFF_RATE[lvl];
        add_buff_rate_var = ADD_BUFF_RATE_VAR[lvl];
        add_buff_id = ADD_BUFF_ID[lvl];
        add_buff_level = ADD_BUFF_LEVEL[lvl];
        distance = DISTANCE[lvl];
        actTime = ACT_TIME[lvl];
        CDGroup = 26;
        CDTime = CD_TIME[lvl];
        range = RANGE[lvl];
        iconId = 22;
        prepareAnimation = -65534;
        castAnimation = -65534;
        hitAnimation = 1;
        clazz = Unit.CLASS_2;
        mp = MP_USE[lvl];
        type = TYPE_AID;
        type |= TYPE_VISIBLE;
        type |= TYPE_RIDE_USE;
        targetType = TARGET_AID_SELF;
    }

    public String getDesc(Unit owner) {
        return java.text.MessageFormat.format("激活后，{0}内任何攻击命中目标后都可将对敌伤害的{1}转化为自己的生命值", CommonUtil.formatMillSecond(peony.game.buff.AutoGeneratedBuff_008.DURATION[add_buff_level]), CommonUtil.formatPercent(peony.game.buff.AutoGeneratedBuff_008.ADD_HP_PERCENT_OF_DAMAGE[add_buff_level]));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public boolean isAutoLearn() {
        return true;
    }

    public int getRequireLevel() {
        return REQUIRE_LEVEL[level];
    }

    protected CombatEffect createActEffect() {
        if (level == 0) {
            return null;
        }
        return this;
    }

    public Buff newBuff() {
        return null;
    }

    public Buff getAreaBuff() {
        return null;
    }

    public void preHit(CombatContext context, boolean isActive) {
        context.damageType = CombatContext.DAMAGE_BUFF;
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void postHit(CombatContext context, boolean isActive) {}

    public void preDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        context.threatAdd += context.getSkillParam(this, "change_threat_value", change_threat_value);
        context.threatAddRate += context.getSkillParam(this, "change_threat_percent", change_threat_percent) / 100.0f;
    }

    public void postDamage(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
    }

    public void finished(CombatContext context, boolean isActive) {
        if (!checkWeapon(context.source)) {
            return;
        }
        if (context.hited()) {
            boolean hit = false;
            if (add_buff_rate_var.length() == 0) {
                hit = CommonUtil.hit(RND, (int)(100 * context.getSkillParam(this, "add_buff_rate", add_buff_rate)), 10000);
            } else {
                Float vo = context.skillParams.get(add_buff_rate_var);
                if (vo != null) {
                    hit = CommonUtil.hit(RND, (int)(100 * (vo.floatValue() + context.getSkillParam(this, "add_buff_rate", add_buff_rate))), 10000);
                }
            }
            if (hit) {
                context.source.buffs.addBuff(BuffUtil.createBuff(add_buff_id, add_buff_level, context.source, context.source, context.damage));
            }
        }
    }

}
