package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;

public class AutoGeneratedBuff_197 implements Buff, PropertyEnhancer {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, -1, -1, -1, -1
    };
    public static int[] CHANGE_STR_VALUE = {
        0, 40, 65, 90, 115
    };
    public static float[] CHANGE_STR_RATE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_str_value;
    float change_str_rate;

    public AutoGeneratedBuff_197(int lvl) {
        int dmg = 0;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        change_str_value = CHANGE_STR_VALUE[level];
        change_str_rate = CHANGE_STR_RATE[level];
    }

    public int getId() {
        return 197;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "終極力量";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("力量提升{0}點", CommonUtil.formatValue(change_str_value * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return false;
    }

    public boolean merge(Buff buff) {
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        change_str_value = CHANGE_STR_VALUE[level];
        change_str_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 197, "change_str_value", change_str_value);
        change_str_rate = CHANGE_STR_RATE[level];
        change_str_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 197, "change_str_rate", change_str_rate);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.strength *= 1.0f + multiple * change_str_rate / 100.0f;
        pc.strength += multiple * change_str_value;
    }

}
