package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;

public class AutoGeneratedBuff_054 implements Buff, SkillBuff, PropertyEnhancer {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, -1, -1, -1, -1, -1, -1, -1
    };
    public static int[] CHANGE_AGI_VALUE = {
        0, 15, 15, 20, 25, 30, 35, 40
    };
    public static float[] CHANGE_AGI_RATE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    public static int[] CHANGE_STA_VALUE = {
        0, 0, 30, 60, 90, 120, 150, 180
    };
    public static float[] CHANGE_STA_RATE = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };
    Skill skill;
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_agi_value;
    float change_agi_rate;
    int change_sta_value;
    float change_sta_rate;

    public AutoGeneratedBuff_054(Skill skl, int lvl) {
        int dmg = 0;
        skill = skl;
        instanceID = BuffUtil.getNextID();
        level = lvl;
        multiple = 1;
        change_agi_value = CHANGE_AGI_VALUE[level];
        change_agi_rate = CHANGE_AGI_RATE[level];
        change_sta_value = CHANGE_STA_VALUE[level];
        change_sta_rate = CHANGE_STA_RATE[level];
    }

    public int getId() {
        return skill.getId();
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "敏捷增加";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("敏捷增加{0}點,體力增加{1}點", CommonUtil.formatValue(change_agi_value * multiple), CommonUtil.formatValue(change_sta_value * multiple));
    }

    public Skill getSkill() {
        return skill;
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return false;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_054) {
            AutoGeneratedBuff_054 other = (AutoGeneratedBuff_054)buff;
            if (level <= other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                change_agi_value = other.change_agi_value;
                change_agi_rate = other.change_agi_rate;
                change_sta_value = other.change_sta_value;
                change_sta_rate = other.change_sta_rate;
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
        change_agi_value = CHANGE_AGI_VALUE[level];
        change_agi_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 54, "change_agi_value", change_agi_value);
        change_agi_rate = CHANGE_AGI_RATE[level];
        change_agi_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 54, "change_agi_rate", change_agi_rate);
        change_sta_value = CHANGE_STA_VALUE[level];
        change_sta_value = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 54, "change_sta_value", change_sta_value);
        change_sta_rate = CHANGE_STA_RATE[level];
        change_sta_rate = owner.buffs.getParamEnhances().enhance(ParamEnhanceSet.TYPE_BUFF_OWNER, 54, "change_sta_rate", change_sta_rate);
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.agility *= 1.0f + multiple * change_agi_rate / 100.0f;
        pc.agility += multiple * change_agi_value;
        pc.stamina *= 1.0f + multiple * change_sta_rate / 100.0f;
        pc.stamina += multiple * change_sta_value;
    }

}
