package peony.game.buff;

import java.util.*;
import peony.game.*;
import peony.game.buff.*;
import peony.game.skill.*;
import peony.util.*;
import com.pip.util.*;
import org.apache.mina.common.ByteBuffer;

public class AutoGeneratedBuff_128 implements Buff, PropertyEnhancer {
    private static final int[] WEAPON = {
        
    };
    public static int[] DURATION = {
        0, -1, -1, -1, -1, -1
    };
    public static int[] CHANGE_PHYSICAL_AP_VALUE = {
        0, 0, 0, 0, 0, 0
    };
    public static float[] CHANGE_PHYSICAL_AP_PERCENT = {
        0.0f, 10.0f, 20.0f, 30.0f, 40.0f, 50.0f
    };
    int instanceID;
    int level;
    int endTime;
    int multiple;
    int remainSeconds;
    int tickInterval;
    int remainCure;
    int remainDamage;
    int remainMPCure;
    int remainMPDamage;
    int remainAbsorb;
    int effectTimes;
    GameObjectRef owner;
    GameObjectRef source;
    int change_physical_ap_value;
    float change_physical_ap_percent;

    public AutoGeneratedBuff_128(int lvl, Unit src, Unit tgt, int dmg) {
        if (src != null) {
            source = src.ref();
        }
        if (tgt != null) {
            owner = tgt.ref();
        }
        instanceID = BuffUtil.getNextID();
        level = lvl;
        endTime = Time.currTime + BuffUtil.enhanceParam(src, tgt, 128, "buffTime", DURATION[level]);
        multiple = 1;
        change_physical_ap_value = CHANGE_PHYSICAL_AP_VALUE[level];
        change_physical_ap_value = BuffUtil.enhanceParam(src, tgt, 128, "change_physical_ap_value", change_physical_ap_value);
        change_physical_ap_percent = CHANGE_PHYSICAL_AP_PERCENT[level];
        change_physical_ap_percent = BuffUtil.enhanceParam(src, tgt, 128, "change_physical_ap_percent", change_physical_ap_percent);
    }

    public int getId() {
        return 128;
    }

    public int getInstanceID() {
        return instanceID;
    }

    public String getName() {
        return "攻擊增加";
    }

    public String getDesc() {
        return java.text.MessageFormat.format("每次強化提升自身{0}物理攻擊力", CommonUtil.formatPercent(change_physical_ap_percent * multiple));
    }

    private boolean checkWeapon(Unit unit) {
        return true;
    }

    public int getEndTime() {
        return -1;
    }

    public boolean isGood() {
        return true;
    }

    public boolean dispelable() {
        return true;
    }

    public boolean keepOnDie() {
        return false;
    }

    public int getIconID() {
        return -1;
    }

    public boolean isAreaBuff() {
        return false;
    }

    public boolean isNeedMerge() {
        return true;
    }

    public boolean merge(Buff buff) {
        if (buff instanceof AutoGeneratedBuff_128) {
            AutoGeneratedBuff_128 other = (AutoGeneratedBuff_128)buff;
            if (level < other.level) {
                level = other.level;
                endTime = other.endTime;
                multiple = 1;
                remainSeconds = other.remainSeconds;
                tickInterval = other.tickInterval;
                remainCure = other.remainCure;
                remainDamage = other.remainDamage;
                remainMPCure = other.remainMPCure;
                remainMPDamage = other.remainMPDamage;
                remainAbsorb = other.remainAbsorb;
                effectTimes = 0;
                owner = other.owner;
                source = other.source;
                change_physical_ap_value = other.change_physical_ap_value;
                change_physical_ap_percent = other.change_physical_ap_percent;
            } else if (level == other.level) {
                endTime = other.endTime;
                if (multiple < 3) {
                    multiple++;
                }
            }
            return true;
        }
        return false;
    }

    public GameObjectRef getSource() {
        return source;
    }

    public void setOwner(GameObjectRef o) {
        owner = o;
        if (source == null) {
            source = owner;
        }
    }

    public void resetParams(Unit owner) {
    }

    public void enhance(PropertyCalculator pc) {
        if (!checkWeapon(pc.unit)) {
            return;
        }
        pc.attackpowerup += multiple * change_physical_ap_value;
        pc.attackpowerdown += multiple * change_physical_ap_value;
        pc.attackpowerRate += multiple * change_physical_ap_percent / 100.0f;
    }

}
