worldip=192.168.50.73
worldport=8760
localip=192.168.50.73
port=7777
servertype=socket
serverid=sky-
serverpassword=itimes
worldreceivebuffsize=32767
worldwritebuffsize=32767
clientreceivebuffsize=32767
clientwritebuffsize=32767
clientacceptornum = 2
tcpnodelay=true
poolbuffer=true
directbuffer=false
maxplayer=300
datadir=D:/workspace/iTimes1.0-Editor/dev/data
ipd=http://218.206.80.185:7070/testipd/report
clientsessionfactory=pip
proxy1=192.168.0.55,7001,proxy@pip2008,1000