#!/usr/bin/env node
/*
 * Generate web/client/src/net/opcodes.js from the server's OpCode.java.
 *
 * OpCode.java is the single source of truth for opcode IDs only (NOT payload layout).
 * Each constant looks like:  public static final short ACCOUNT_LOGIN_CLIENT = 166;
 * Naming convention encodes direction: *_CLIENT = client->server, *_SERVER = server->client.
 *
 * The generator FAILS LOUDLY on: no matches or a duplicate NAME. ID collisions are NOT an
 * error — this protocol deliberately reuses numeric IDs (e.g. CANCEL_ATTACK_CLIENT and
 * CANCEL_ATTACK_SERVER are both 318; even two *_SERVER names can share an ID). They are
 * disambiguated by direction/context, so the reverse map is id -> [names]. Run:
 *   node tools/gen_opcodes.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const ROOT = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'Game/sangobuildVn/server/src/peony/game/OpCode.java');
const OUT = path.join(ROOT, 'web/client/src/net/opcodes.js');

const text = fs.readFileSync(SRC, 'utf8');
const re = /public\s+static\s+final\s+short\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(-?0x[0-9a-fA-F]+|-?\d+)\s*;/g;

const entries = [];
const byName = new Map();
const idToNames = new Map();
const errors = [];
const collisions = [];

let m;
while ((m = re.exec(text)) !== null) {
  const name = m[1];
  const raw = m[2];
  const value = raw.startsWith('0x') || raw.startsWith('-0x') ? parseInt(raw, 16) : parseInt(raw, 10);
  if (byName.has(name)) { errors.push(`duplicate name ${name} (=${value})`); continue; }
  byName.set(name, value);
  if (idToNames.has(value)) { idToNames.get(value).push(name); collisions.push(`${value}: ${idToNames.get(value).join(', ')}`); }
  else idToNames.set(value, [name]);
  const dir = name.endsWith('_CLIENT') ? 'c2s' : name.endsWith('_SERVER') ? 's2c' : 'other';
  entries.push({ name, value, dir });
}

if (entries.length === 0) errors.push('no opcode constants matched — OpCode.java format changed?');

if (errors.length) {
  console.error('[gen_opcodes] FAILED:');
  for (const e of errors) console.error('  - ' + e);
  process.exit(1);
}
if (collisions.length) console.warn(`[gen_opcodes] note: ${collisions.length} ID collisions (expected; disambiguated by direction/context)`);

entries.sort((a, b) => a.value - b.value);

const counts = entries.reduce((a, e) => ((a[e.dir] = (a[e.dir] || 0) + 1), a), {});
const banner = `// AUTO-GENERATED by tools/gen_opcodes.mjs from Game/sangobuildVn/server/src/peony/game/OpCode.java\n` +
  `// Source of truth for opcode IDs only — NOT payload layout. Do not edit by hand.\n` +
  `// ${entries.length} opcodes (c2s=${counts.c2s || 0}, s2c=${counts.s2c || 0}, other=${counts.other || 0}).\n`;

let js = banner + '\n';
js += 'export const OpCode = Object.freeze({\n';
for (const e of entries) js += `  ${e.name}: ${e.value},\n`;
js += '});\n\n';

js += '// id -> [names]  (IDs are reused across messages; disambiguate by direction/context)\n';
js += 'export const OpCodeNames = Object.freeze({\n';
for (const [id, names] of [...idToNames.entries()].sort((a, b) => a[0] - b[0])) {
  js += `  "${id}": ${JSON.stringify(names)},\n`;
}
js += '});\n\n';

js += '// id -> sorted unique directions seen for that id ("c2s","s2c","other").\n';
js += '// A received id with only "s2c" is unambiguously server->client; ids with both\n';
js += '// directions are disambiguated by whether you are sending or receiving.\n';
js += 'export const OpCodeDirs = Object.freeze({\n';
for (const [id, names] of [...idToNames.entries()].sort((a, b) => a[0] - b[0])) {
  const dirs = [...new Set(names.map(n => n.endsWith('_CLIENT') ? 'c2s' : n.endsWith('_SERVER') ? 's2c' : 'other'))].sort();
  js += `  "${id}": ${JSON.stringify(dirs)},\n`;
}
js += '});\n\n';

js += '/** Direction implied by an opcode NAME suffix. */\n';
js += 'export function directionOf(name) {\n';
js += "  return name.endsWith('_CLIENT') ? 'c2s' : name.endsWith('_SERVER') ? 's2c' : 'other';\n";
js += '}\n';

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, js);
console.log(`[gen_opcodes] wrote ${path.relative(ROOT, OUT)} — ${entries.length} opcodes (c2s=${counts.c2s || 0}, s2c=${counts.s2c || 0}, other=${counts.other || 0})`);
