worldip=localhost
worldport=2260
authip=localhost
authport=2261
localip=192.168.0.66
port=2259
serverid=connect1
serverpassword=itimes
worldreceivebuffsize=32767
worldwritebuffsize=32767
authreceivebuffsize=32767
authwritebuffsize=32767
clientreceivebuffsize=32767
clientwritebuffsize=32767
clientacceptornum = 2
tcpnodelay=true
maxplayer=300
datadir=E:/cvshome/projects/iTimes1.0/iTimes1.0-Editor/dev/data